---

- name: restart nginx
  service: name=nginx state=restarted enabled=yes
  become: yes
  become_method: sudo

- name: reload nginx
  service: name=nginx state=reloaded
  become: yes
  become_method: sudo
  listen: reload_nginx
