# Generated by Django 2.1.3 on 2018-12-03 14:51

from django.db import migrations, models
import learning.models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_auto_20181108_0820'),
    ]

    operations = [
        migrations.RenameField('studentassignment', 'first_submission_at', 'first_student_comment_at'),
        migrations.AlterField(
            model_name='studentassignment',
            name='first_student_comment_at',
            field=models.DateTimeField(editable=False, null=True,
                                       verbose_name='First Student Comment At'),
        ),
    ]
