# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-12 14:02
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.timezone import now

import learning.models


# TODO: remove this after data migration
def update_completion_date(apps, schema_editor):
    from learning.utils import get_current_semester_pair
    from learning.utils import get_term_index, get_term_by_index, get_term_start

    def get_next_term_start(year, term_type):
        term_index = get_term_index(year, term_type)
        _, next_term = get_term_by_index(term_index + 1)
        return get_term_start(year, next_term)

    current_year, current_term_type = get_current_semester_pair()
    CourseOffering = apps.get_model("learning", "CourseOffering")
    for co in CourseOffering.objects.select_related("semester").all():
        if co.semester.year == current_year and co.semester.type == current_term_type:
            if co.is_completed:
                # Текущий день
                completed_at = now()
            else:
                # Конец семестра
                completed_at = get_next_term_start(co.semester.year, co.semester.type)
        else:
            # Выставляем конец
            completed_at = get_next_term_start(co.semester.year, co.semester.type)
        (co.__class__.objects
         .filter(pk=co.pk)
         .update(completion_date=completed_at.date()))


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_auto_20170331_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='completion_date',
            field=models.DateField(default=learning.models.next_term_starts_at, help_text='Consider the course as completed from the specified day (inclusive).', verbose_name='Date of completion'),
        ),
        migrations.RunPython(update_completion_date),
    ]
