# Generated by Django 2.1.1 on 2018-10-30 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_auto_20181019_1339'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='MetaCourse',
        ),
    ]
