# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-12 14:02
from __future__ import unicode_literals

import pytz
from django.db import migrations, models

import learning.models
import learning.utils


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_auto_20170331_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='completion_date',
            field=models.DateField(default=learning.utils.next_term_starts_at, help_text='Consider the course as completed from the specified day (inclusive).', verbose_name='Date of completion'),
        ),
    ]
