# Generated by Django 2.1.1 on 2018-10-30 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180730_1437'),
        ('learning', '0003_auto_20181030_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseoffering',
            options={'ordering': ['-semester', 'meta_course__created'], 'verbose_name': 'Course offering', 'verbose_name_plural': 'Course offerings'},
        ),
        migrations.RenameField(
            model_name='courseoffering',
            old_name='course',
            new_name='meta_course',
        ),
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together={('meta_course', 'semester', 'city')},
        ),
    ]
