# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-15 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_courseoffering_completion_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoffering',
            name='is_completed',
        ),
        migrations.RenameField(
            model_name='courseoffering',
            old_name='completion_date',
            new_name='completed_at',
        ),
    ]
