# Generated by Django 2.1.3 on 2018-12-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_auto_20181203_1451'),
    ]

    database_operations = [
        migrations.AlterModelTable('InternshipCategory',
                                   'internships_categories'),
        migrations.AlterModelTable('Internship', 'internships'),
    ]

    state_operations = [
        migrations.DeleteModel('InternshipCategory'),
        migrations.DeleteModel('Internship'),
    ]

    operations = [
      migrations.SeparateDatabaseAndState(
        database_operations=database_operations,
        state_operations=state_operations)
    ]
