# Generated by Django 2.1.3 on 2018-12-28 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_auto_20181227_1603'),
    ]

    state_operations = [
        migrations.DeleteModel('InternationalSchool'),
    ]

    operations = [
      migrations.SeparateDatabaseAndState(
        state_operations=state_operations)
    ]
