# Generated by Django 2.1.1 on 2018-10-31 11:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180730_1437'),
        ('surveys', '0002_data'),
        ('gallery', '0002_image_course_offering'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0004_auto_20181030_1352'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseOffering',
            new_name='Course',
        ),
    ]
