# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-14 08:34
from __future__ import unicode_literals

import bitfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_remove_courseoffering_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='directions',
            field=models.TextField(blank=True, null=True, verbose_name='Directions'),
        ),
        migrations.AddField(
            model_name='venue',
            name='flags',
            field=bitfield.models.BitField((('lecture', 'Class'), ('interview', 'Interview')), default=1, help_text='Set purpose of this place', verbose_name='Flags'),
        ),
    ]
