# Generated by Django 2.1.5 on 2019-01-09 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_delete_internationalschool'),
        ('users', '0001_initial'),
    ]

    database_operations = [
        migrations.AlterModelTable('AreaOfStudy',
                                   'areas_of_study'),
        migrations.AlterModelTable('StudyProgram',
                                   'study_programs'),
        migrations.AlterModelTable('StudyProgramCourseGroup',
                                   'study_programs_groups'),
    ]

    state_operations = [
        migrations.DeleteModel('AreaOfStudy'),
        migrations.DeleteModel('StudyProgram'),
        migrations.DeleteModel('StudyProgramCourseGroup'),
    ]

    operations = [
      migrations.SeparateDatabaseAndState(
        database_operations=database_operations,
        state_operations=state_operations)
    ]
