# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('learning', '0006_enrollment_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Category name')),
                ('sort', models.SmallIntegerField(blank=True, null=True, verbose_name='Sort order')),
                ('site', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Site')),
            ],
            options={
                'ordering': ['sort'],
                'verbose_name_plural': 'Internship categories',
                'verbose_name': 'Internship category',
            },
        ),
        migrations.RemoveField(
            model_name='internship',
            name='site',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='The student left the course'),
        ),
    ]
