# Generated by Django 2.1.1 on 2018-10-31 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_auto_20181031_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseteacher',
            name='course_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_teachers', to='learning.Course'),
        ),
    ]
