# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_auto_20170710_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.InternshipCategory', verbose_name='Internship category'),
        ),
    ]
