# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_internship_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.InternshipCategory', verbose_name='Internship category'),
        ),
    ]
