# Generated by Django 2.1.1 on 2018-10-31 13:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0008_auto_20181031_1208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseOfferingNewsNotification',
            new_name='CourseNewsNotification',
        ),
    ]
