# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_auto_20170710_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoffering',
            name='enrolled_students',
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='city',
            field=models.ForeignKey(default='spb', on_delete=django.db.models.deletion.CASCADE, to='core.City', verbose_name='City'),
        ),
    ]
