# Generated by Django 2.1.1 on 2018-10-31 15:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0009_auto_20181031_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseteacher',
            options={'verbose_name': 'Course Teacher', 'verbose_name_plural': 'Course Teachers'},
        ),
        migrations.RenameField(
            model_name='courseteacher',
            old_name='course_offering',
            new_name='course',
        ),
        migrations.AlterUniqueTogether(
            name='courseteacher',
            unique_together={('teacher', 'course')},
        ),
    ]
