# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_auto_20170809_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='city',
            field=models.ForeignKey(blank=True, default='spb', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.City', verbose_name='City'),
        ),
    ]
