# Generated by Django 2.1.1 on 2018-10-31 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_auto_20181031_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursenews',
            old_name='course_offering',
            new_name='course',
        ),
        migrations.AlterField(
            model_name='coursenews',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    to='learning.Course',
                                    verbose_name='Course'),
        ),
    ]
