# Generated by Django 2.1.1 on 2018-10-31 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_auto_20181031_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseclass',
            old_name='course_offering',
            new_name='course',
        ),
        migrations.AlterModelOptions(
            name='courseclass',
            options={'ordering': ['-date', 'course', '-starts_at'],
                     'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    to='learning.Course',
                                    verbose_name='Course'),
        ),
    ]
