# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-01 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_auto_20170825_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='materials_files',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='materials_slides',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='materials_video',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
