# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-07 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_auto_20170901_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoffering',
            name='completed_at',
            field=models.DateField(blank=True, help_text='Consider the course as completed from the specified day (inclusive).', verbose_name='Date of completion'),
        ),
    ]
