# Generated by Django 2.1.1 on 2018-11-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_auto_20181101_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='grade_min',
            new_name='passing_score',
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='type',
            field=models.CharField(choices=[('lecture', 'Lecture'), ('seminar', 'Seminar')], max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='grade',
            field=models.CharField(choices=[('not_graded', 'Not graded'), ('unsatisfactory', 'Enrollment|Unsatisfactory'), ('pass', 'Enrollment|Pass'), ('good', 'Good'), ('excellent', 'Excellent')], default='not_graded', max_length=100, verbose_name='Enrollment|grade'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='type',
            field=models.CharField(choices=[('spring', 'spring'), ('summer', 'summer'), ('autumn', 'autumn')], max_length=100, verbose_name='Semester|type'),
        ),
    ]
