# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_auto_20171107_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='is_correspondence',
            field=models.BooleanField(default=False, verbose_name='Correspondence course'),
        ),
    ]
