# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('learning', '0015_courseoffering_is_correspondence'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together=set([('course', 'semester', 'city')]),
        ),
    ]
