# Generated by Django 2.1.1 on 2018-11-06 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0015_auto_20181106_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='grade_max',
            new_name='maximum_score',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='passing_score',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MaxValueValidator(1000)], verbose_name='Assignment|passing_score'),
        ),
    ]
