# Generated by Django 2.1.1 on 2018-11-06 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0016_auto_20181106_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='maximum_score',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(1000)], verbose_name='Maximum score'),
        ),
    ]
