# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0016_courseoffering_capacity'),
    ]

    # Add custom database_operations
    database_operations = [
        # You have to use Django's database table naming defaults to get the
        # name 'tires_tires'. It is basically <app_name>_<model_name>.
        migrations.AlterModelTable('studentproject',
                                   'projects_studentproject'),
    ]

    # Don't modify the Django 'state' yet
    state_operations = []

    operations = [
        migrations.AlterField(
            model_name='courseoffering',
            name='city',
            field=models.ForeignKey(blank=True, default='RU SPB', null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='core.City'),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='language',
            field=models.CharField(
                choices=[('ru', 'Russian'), ('en', 'English')], db_index=True,
                default='ru', max_length=5),
        ),
        migrations.AlterField(
            model_name='venue',
            name='city',
            field=models.ForeignKey(blank=True, default='RU SPB', null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='core.City'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
