# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-13 08:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0016_auto_20180115_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Grade'),
        ),
    ]
