# Generated by Django 2.1.1 on 2018-11-06 11:24

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0017_auto_20181106_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentassignment',
            old_name='grade',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='studentassignment',
            old_name='grade_changed',
            new_name='score_changed',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='notify_teachers',
            field=models.ManyToManyField(blank=True, help_text='Leave blank if you want to populate list from the course settings', to='learning.CourseTeacher', verbose_name='Assignment|notify_settings'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='passing_score',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MaxValueValidator(1000)], verbose_name='Passing score'),
        ),
    ]
