# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-30 14:55
from __future__ import unicode_literals

import core.db.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0018_auto_20180213_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoffering',
            name='city',
            field=models.ForeignKey(default='spb', on_delete=django.db.models.deletion.PROTECT, to='core.City', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.InternshipCategory', verbose_name='Internship category'),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='grade',
            field=core.db.models.GradeField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)], verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='city',
            field=models.ForeignKey(blank=True, default='spb', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.City', verbose_name='City'),
        ),
    ]
