# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0018_auto_20160714_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoffering',
            name='city',
            field=models.ForeignKey(default='RU SPB', on_delete=django.db.models.deletion.CASCADE, to='core.City'),
        ),
    ]
