# Generated by Django 2.1.1 on 2018-11-06 12:27

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0018_auto_20181106_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=140, verbose_name='Assignment|name'),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='score_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='score', verbose_name='Assignment|grade changed'),
        ),
    ]
