# Generated by Django 2.1.1 on 2018-09-03 13:54

import core.db.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0019_auto_20180730_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='reason_entry',
            field=models.TextField(blank=True, verbose_name='Entry reason'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='reason_leave',
            field=models.TextField(blank=True, verbose_name='Leave reason'),
        ),
    ]
