# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0019_auto_20160715_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='report_ends_at',
            field=models.DateField(blank=True, help_text='End point of project report period.', null=True, verbose_name='Report end'),
        ),
        migrations.AddField(
            model_name='semester',
            name='report_starts_at',
            field=models.DateField(blank=True, help_text='Start point of project report period.', null=True, verbose_name='Report start'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='index',
            field=models.PositiveSmallIntegerField(editable=False, help_text='System field. Used for sort order and filter.', verbose_name='Semester index'),
        ),
    ]
