# Generated by Django 2.1.1 on 2018-11-06 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20181019_1339'),
        ('users', '0005_auto_20181031_0910'),
        # ('surveys', '0004_auto_20181031_1428'),
        ('gallery', '0003_auto_20181031_1514'),
        # ('admission', '0003_create_templates'),
        ('learning', '0019_auto_20181106_1227'),
    ]

    database_operations = [
        migrations.AlterModelTable('Semester', 'courses_semester'),
        migrations.AlterModelTable('Venue', 'courses_venue'),
        migrations.AlterModelTable('MetaCourse', 'courses_metacourse'),
        migrations.AlterModelTable('Course', 'courses_course'),
        migrations.AlterModelTable('CourseTeacher', 'courses_courseteacher'),
        migrations.AlterModelTable('CourseNews', 'courses_coursenews'),
        migrations.AlterModelTable('CourseClass', 'courses_courseclass'),
        migrations.AlterModelTable('Assignment', 'courses_assignment'),
        migrations.AlterModelTable('AssignmentAttachment',
                                   'courses_assignmentattachment'),
        migrations.AlterModelTable('CourseClassAttachment',
                                   'courses_courseclassattachment'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations
        )
    ]
