# Generated by Django 2.1.1 on 2018-11-06 18:28

import django.db
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0020_auto_20181106_1827'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursenewsnotification',
            name='course_offering_news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='courses.CourseNews',
                                    verbose_name='Course offering news'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='courses.Course',
                                    verbose_name='Course offering'),
        ),
        migrations.AlterField(
            model_name='noncourseevent',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    to='courses.Venue',
                                    verbose_name='CourseClass|Venue'),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='courses.Assignment',
                                    verbose_name='StudentAssignment|assignment'),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='last_comment_from',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'NOBODY'), (1, 'STUDENT'), (2, 'TEACHER')],
                default=0, editable=False,
                verbose_name='The author type of the latest comment'),
        ),
        migrations.AlterField(
            model_name='studyprogramcoursegroup',
            name='courses',
            field=models.ManyToManyField(
                help_text='Courses will be grouped with boolean OR',
                to='courses.MetaCourse',
                verbose_name='StudyProgramCourseGroup|courses'),
        ),
    ]
