# Generated by Django 2.1.1 on 2018-11-06 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0021_auto_20181106_1828'),
    ]

    state_operations = [
        migrations.DeleteModel(
            name='Semester',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='AssignmentAttachment',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseClass',
        ),
        migrations.DeleteModel(
            name='CourseClassAttachment',
        ),
        migrations.DeleteModel(
            name='CourseNews',
        ),
        migrations.DeleteModel(
            name='CourseTeacher',
        ),
        migrations.DeleteModel(
            name='MetaCourse',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]

    operations = [
      migrations.SeparateDatabaseAndState(
        state_operations=state_operations)
    ]
