# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-01 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0021_recalc_term_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentassignment',
            name='last_commented',
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='last_comment_from',
            field=models.PositiveSmallIntegerField(default=0, editable=False, help_text='0 - no comments yet, 1 - from student, 2 - from teacher', verbose_name='Last comment from'),
        ),
    ]
