# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-14 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0022_auto_20161001_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='first_submission_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Assignment|first_submission'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='text',
            field=models.TextField(help_text='How to style text read <a href="/commenting-the-right-way/" target="_blank">here</a>. Partially HTML is enabled too.', verbose_name='Assignment|text'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(help_text='How to style text read <a href="/commenting-the-right-way/" target="_blank">here</a>. Partially HTML is enabled too.', verbose_name='Course|description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description_en',
            field=models.TextField(help_text='How to style text read <a href="/commenting-the-right-way/" target="_blank">here</a>. Partially HTML is enabled too.', null=True, verbose_name='Course|description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description_ru',
            field=models.TextField(help_text='How to style text read <a href="/commenting-the-right-way/" target="_blank">here</a>. Partially HTML is enabled too.', null=True, verbose_name='Course|description'),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='description',
            field=models.TextField(blank=True, help_text='How to style text read <a href="/commenting-the-right-way/" target="_blank">here</a>. Partially HTML is enabled too.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='other_materials',
            field=models.TextField(blank=True, help_text='How to style text read <a href="/commenting-the-right-way/" target="_blank">here</a>. Partially HTML is enabled too.', verbose_name='CourseClass|Other materials'),
        ),
        migrations.AlterField(
            model_name='courseofferingnews',
            name='text',
            field=models.TextField(help_text='How to style text read <a href="/commenting-the-right-way/" target="_blank">here</a>. Partially HTML is enabled too.', verbose_name='CourseNews|text'),
        ),
        migrations.AlterField(
            model_name='noncourseevent',
            name='description',
            field=models.TextField(blank=True, help_text='How to style text read <a href="/commenting-the-right-way/" target="_blank">here</a>. Partially HTML is enabled too.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='onlinecourse',
            name='description',
            field=models.TextField(help_text='How to style text read <a href="/commenting-the-right-way/" target="_blank">here</a>. Partially HTML is enabled too.', verbose_name='Online Course|description'),
        ),
        migrations.AlterField(
            model_name='onlinecourse',
            name='teachers',
            field=models.TextField(help_text='How to style text read <a href="/commenting-the-right-way/" target="_blank">here</a>. Partially HTML is enabled too.', verbose_name='Online Course|teachers'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='description',
            field=models.TextField(help_text='How to style text read <a href="/commenting-the-right-way/" target="_blank">here</a>. Partially HTML is enabled too.', verbose_name='Description'),
        ),
    ]
