# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-15 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0023_first_submission_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentassignment',
            name='is_passed',
        ),
    ]
