# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-22 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0024_remove_studentassignment_is_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='projects_grade_excellent',
            field=models.SmallIntegerField(blank=True, help_text='Semester|projects_grade_excellent', null=True, verbose_name='Projects|Border for excellent'),
        ),
        migrations.AddField(
            model_name='semester',
            name='projects_grade_good',
            field=models.SmallIntegerField(blank=True, help_text='Semester|projects_grade_good', null=True, verbose_name='Projects|Border for good'),
        ),
        migrations.AddField(
            model_name='semester',
            name='projects_grade_pass',
            field=models.SmallIntegerField(blank=True, help_text='Semester|projects_grade_pass', null=True, verbose_name='Projects|Border for pass'),
        ),
    ]
