# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-11 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0025_auto_20161222_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='reviews',
            field=models.TextField(blank=True, null=True, verbose_name='Reviews'),
        ),
    ]
