# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-12 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('learning', '0026_courseoffering_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('sort', models.SmallIntegerField(blank=True, null=True, verbose_name='Sort order')),
                ('site', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Intership',
                'ordering': ['sort'],
                'verbose_name_plural': 'Interships',
            },
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='reviews',
            field=models.TextField(blank=True, null=True, verbose_name='Course reviews'),
        ),
    ]
