# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-12 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0027_auto_20170112_1356'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Intership',
            new_name='Internship',
        ),
        migrations.AlterModelOptions(
            name='internship',
            options={'ordering': ['sort'], 'verbose_name': 'Internship', 'verbose_name_plural': 'Internships'},
        ),
    ]
