# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-20 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0029_auto_20170112_1446'),
    ]

    operations = [
        migrations.RenameModel("StudyProgram", "AreaOfStudy"),
    ]
