# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-20 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0030_areaofstudy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaofstudy',
            options={'ordering': ['name'], 'verbose_name': 'Area of study', 'verbose_name_plural': 'Areas of study'},
        ),
        migrations.AlterField(
            model_name='areaofstudy',
            name='name',
            field=models.CharField(max_length=255, verbose_name='AreaOfStudy|Name'),
        ),
        migrations.AlterField(
            model_name='areaofstudy',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='AreaOfStudy|Name'),
        ),
        migrations.AlterField(
            model_name='areaofstudy',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='AreaOfStudy|Name'),
        ),
    ]
