# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-20 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0031_auto_20170220_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaofstudy',
            name='description',
            field=models.TextField(default='', help_text='How to style text read <a href="/commenting-the-right-way/" target="_blank">here</a>. Partially HTML is enabled too.', verbose_name='AreaOfStudy|description'),
            preserve_default=False,
        ),
    ]
