# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-20 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0032_areaofstudy_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaofstudy',
            name='description_en',
            field=models.TextField(help_text='How to style text read <a href="/commenting-the-right-way/" target="_blank">here</a>. Partially HTML is enabled too.', null=True, verbose_name='AreaOfStudy|description'),
        ),
        migrations.AddField(
            model_name='areaofstudy',
            name='description_ru',
            field=models.TextField(help_text='How to style text read <a href="/commenting-the-right-way/" target="_blank">here</a>. Partially HTML is enabled too.', null=True, verbose_name='AreaOfStudy|description'),
        ),
    ]
