# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-22 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0034_studyprogram_studyprogramcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyprogram',
            name='name',
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='city',
            field=models.ForeignKey(default='RU SPB', on_delete=django.db.models.deletion.CASCADE, to='core.City', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='studyprogramcourse',
            name='group',
            field=models.PositiveSmallIntegerField(help_text='Courses within the same group are combined using the boolean OR.', verbose_name='Group'),
        ),
    ]
