# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-22 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0036_auto_20170222_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyprogramcoursegroup',
            name='courses',
            field=models.ManyToManyField(related_name='study_programs', to='learning.Course', verbose_name='StudyProgramCourseGroup|courses'),
        ),
    ]
