# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-06 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0037_auto_20170222_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyprogram',
            name='sort',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Sort order'),
        ),
        migrations.AlterField(
            model_name='studyprogramcoursegroup',
            name='courses',
            field=models.ManyToManyField(help_text='Courses will be grouped with boolean OR', to='learning.Course', verbose_name='StudyProgramCourseGroup|courses'),
        ),
        migrations.AlterField(
            model_name='studyprogramcoursegroup',
            name='study_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_groups', to='learning.StudyProgram', verbose_name='Study Program'),
        ),
    ]
