# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-06 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0038_auto_20170306_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyprogram',
            name='description',
            field=models.TextField(blank=True, help_text='How to style text read <a href="/commenting-the-right-way/" target="_blank">here</a>. Partially HTML is enabled too.', null=True, verbose_name='StudyProgram|description'),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='sort',
            field=models.SmallIntegerField(blank=True, help_text='StudyProgram|sort', null=True, verbose_name='Sort order'),
        ),
    ]
