# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-07 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0039_auto_20170306_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyprogram',
            name='sort',
        ),
    ]
