# Generated by Django 2.1.5 on 2019-01-09 13:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('core', '0002_auto_20180730_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfStudy',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='PK|Code')),
                ('name', models.CharField(max_length=255, verbose_name='AreaOfStudy|Name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='AreaOfStudy|Name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='AreaOfStudy|Name')),
                ('description', models.TextField(verbose_name='AreaOfStudy|description')),
                ('description_ru', models.TextField(null=True, verbose_name='AreaOfStudy|description')),
                ('description_en', models.TextField(null=True, verbose_name='AreaOfStudy|description')),
            ],
            options={
                'verbose_name': 'Area of study',
                'verbose_name_plural': 'Areas of study',
                'db_table': 'areas_of_study',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudyProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1990)], verbose_name='Year')),
                ('description', models.TextField(blank=True, null=True, verbose_name='StudyProgram|description')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_programs.AreaOfStudy', verbose_name='Area of Study')),
                ('city', models.ForeignKey(default='spb', on_delete=django.db.models.deletion.CASCADE, to='core.City', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Study Program',
                'verbose_name_plural': 'Study Programs',
                'db_table': 'study_programs',
            },
        ),
        migrations.CreateModel(
            name='StudyProgramCourseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(help_text='Courses will be grouped with boolean OR', to='courses.MetaCourse', verbose_name='StudyProgramCourseGroup|courses')),
                ('study_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_groups', to='study_programs.StudyProgram', verbose_name='Study Program')),
            ],
            options={
                'verbose_name': 'Study Program Course',
                'verbose_name_plural': 'Study Program Courses',
                'db_table': 'study_programs_groups',
            },
        ),
    ]
