# Generated by Django 2.2.4 on 2019-08-30 08:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import publications.models
import users.thumbnails


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('is_draft', models.BooleanField(default=False, verbose_name='Draft')),
                ('type', models.CharField(choices=[('practice', 'StudentProject|Practice'), ('research', 'StudentProject|Research')], editable=False, max_length=10)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('external_links', models.TextField(blank=True, verbose_name='External Links')),
            ],
            options={
                'verbose_name': 'Project Publication',
                'verbose_name_plural': 'Project Publications',
                'db_table': 'publications_projects',
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Surname')),
                ('patronymic', models.CharField(blank=True, max_length=255, verbose_name='Patronymic')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('o', 'Other/Prefer Not to Say')], default='o', max_length=1, verbose_name='Gender')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('photo', models.ImageField(blank=True, help_text='Aspect ratio 5:7. Min size: 176x246', null=True, upload_to=publications.models.lecturer_photo_upload_to, verbose_name='Photo')),
                ('workplace', models.CharField(blank=True, max_length=255, null=True, verbose_name='Workplace')),
            ],
            options={
                'verbose_name': 'Speaker',
                'verbose_name_plural': 'Speakers',
            },
            bases=(users.thumbnails.UserThumbnailMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RecordedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(max_length=70, unique=True, verbose_name='Slug')),
                ('date_at', models.DateField(verbose_name='Event Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('video_url', models.URLField(blank=True, help_text='https://support.google.com/youtube/answer/171780?hl=en', null=True, verbose_name='Video URL')),
                ('slides_url', models.URLField(blank=True, verbose_name='Slides URL')),
                ('speakers', models.ManyToManyField(related_name='recorded_events', to='publications.Speaker', verbose_name='Speakers')),
            ],
            options={
                'verbose_name': 'Recorded Event',
                'verbose_name_plural': 'Recorded Events',
            },
        ),
        migrations.CreateModel(
            name='ProjectPublicationAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Short Description')),
                ('project_publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.ProjectPublication')),
            ],
            options={
                'verbose_name': 'Project Publication Author',
                'verbose_name_plural': 'Project Publication Authors',
            },
        ),
    ]
