# Generated by Django 2.1.8 on 2019-04-11 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0005_auto_20190410_1407'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('external_links', models.TextField(blank=True, verbose_name='External Links')),
            ],
            options={
                'verbose_name': 'Project Publication',
                'verbose_name_plural': 'Project Publications',
                'db_table': 'publications_projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectPublicationAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.ProjectPublication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Publication Author',
                'verbose_name_plural': 'Project Publication Authors',
            },
        ),
        migrations.AddField(
            model_name='projectpublication',
            name='authors',
            field=models.ManyToManyField(related_name='_projectpublication_authors_+', through='publications.ProjectPublicationAuthor', to=settings.AUTH_USER_MODEL, verbose_name='Authors'),
        ),
        migrations.AddField(
            model_name='projectpublication',
            name='projects',
            field=models.ManyToManyField(related_name='publications', to='projects.Project', verbose_name='Projects'),
        ),
        migrations.AlterUniqueTogether(
            name='projectpublicationauthor',
            unique_together={('user', 'project_publication')},
        ),
    ]
