# Generated by Django 2.2 on 2019-04-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_projectpublicationauthor_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpublication',
            name='type',
            field=models.CharField(choices=[('practice', 'StudentProject|Practice'), ('research', 'StudentProject|Research')], default='practice', editable=False, max_length=10),
            preserve_default=False,
        ),
    ]
