# Generated by Django 2.2 on 2019-04-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_projectpublication_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpublication',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='Draft'),
        ),
    ]
