# Generated by Django 3.0.9 on 2020-09-02 09:15

from django.db import migrations, models
import publications.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_projectpublication_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpublication',
            name='cover',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Min height - 180px', max_length=200, upload_to=publications.models.publication_photo_upload_to, verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='photo',
            field=models.ImageField(blank=True, default='', help_text='Aspect ratio 5:7. Min size: 176x246', max_length=200, upload_to=publications.models.lecturer_photo_upload_to, verbose_name='Photo'),
            preserve_default=False,
        ),
    ]
