# Generated by Django 2.2.1 on 2019-06-20 13:41

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import publications.models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_projectpublication_is_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Surname')),
                ('patronymic', models.CharField(blank=True, max_length=255, verbose_name='Patronymic')),
                ('description', models.TextField(blank=True, verbose_name='About Lecturer')),
                ('photo', models.ImageField(blank=True, help_text='Aspect ratio 5:7. Min size: 176x246', null=True, upload_to=publications.models.lecturer_photo_upload_to, verbose_name='Photo')),
                ('workplace', models.CharField(blank=True, max_length=255, null=True, verbose_name='Workplace')),
            ],
            options={
                'verbose_name': 'Speaker',
                'verbose_name_plural': 'Speakers',
            },
        ),
        migrations.CreateModel(
            name='OpenLecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(max_length=70, unique=True, verbose_name='Slug')),
                ('date_at', models.DateField(verbose_name='Event Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('video_url', models.URLField(blank=True, help_text='https://support.google.com/youtube/answer/171780?hl=en', null=True, verbose_name='Video URL')),
                ('slides_url', models.URLField(blank=True, verbose_name='Slides URL')),
                ('speakers', models.ManyToManyField(related_name='open_lectures', to='publications.Speaker', verbose_name='Speakers')),
            ],
            options={
                'verbose_name': 'Open Lecture',
                'verbose_name_plural': 'Open Lectures',
            },
        ),
    ]
