# Generated by Django 2.2.1 on 2019-06-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_openlecture_speaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('o', 'Other/Prefer Not to Say')], default='o', max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
