# Generated by Django 2.2.1 on 2019-06-27 12:42

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_auto_20190620_1542'),
    ]

    operations = [
        migrations.RenameModel('OpenLecture', 'RecordedEvent'),
        migrations.AlterModelOptions(
            name='recordedevent',
            options={'verbose_name': 'Recorded Event',
                     'verbose_name_plural': 'Recorded Events'},
        ),
        migrations.AlterField(
            model_name='recordedevent',
            name='speakers',
            field=models.ManyToManyField(related_name='recorded_events',
                                         to='publications.Speaker',
                                         verbose_name='Speakers'),
        ),
    ]
