---
aws_vpc_id: vpc-2b11e042
aws_subnet_id: subnet-c5be5abe
aws_elastic_ip: 52.28.201.159

aws_ec2_host: tag_Name_cscweb
aws_ec2_new_instance_tag: cscweb_new
aws_ec2_host_new: tag_Name_{{ aws_ec2_new_instance_tag }}

security_groups:
  - name: ssh
    desc: the security group for ssh-available server
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0

  - name: web
    desc: the security group for the web server
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
