# Generated by Django 3.0.9 on 2020-09-22 08:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0027_auto_20200922_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('name', models.CharField(max_length=80, verbose_name='CheckingSystem|Name')),
                ('type', models.CharField(choices=[('ya', 'Yandex.Contest')], max_length=42, verbose_name='CheckingSystem|Type')),
                ('description', models.TextField(blank=True, verbose_name='What can it be used for?')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Access token, etc', verbose_name='CheckingSystem|Details')),
            ],
            options={
                'verbose_name': 'Checking System',
                'verbose_name_plural': 'Checking Systems',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(1, 'New'), (20, 'Not Submitted'), (30, 'Checking'), (40, 'Wrong Answer'), (50, 'Correct Answer')], default=1, verbose_name='Status')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Selected compiler, etc', verbose_name='Settings')),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Returned submission id or error details', verbose_name='Meta')),
                ('assignment_submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='learning.AssignmentComment', verbose_name='Assignment Submission')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
            },
        ),
        migrations.CreateModel(
            name='Checker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, verbose_name='Checker|URL')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Contest id, problem id, etc', verbose_name='Checker|Settings')),
                ('checking_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.CheckingSystem', verbose_name='Checking System')),
            ],
            options={
                'verbose_name': 'Checker',
                'verbose_name_plural': 'Checkers',
            },
        ),
    ]
