# Generated by Django 3.2.18 on 2025-03-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (20, 'Not Submitted'), (30, 'Checking'), (40, 'Wrong Answer'), (50, 'Correct Answer'), (60, 'Retrying')], default=1, verbose_name='Status'),
        ),
    ]
