# Generated by Django 2.2.4 on 2019-08-30 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('courses', '0002_auto_20190830_0814'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Project reviewer'),
        ),
        migrations.AddField(
            model_name='reportingperiod',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='reportingperiod',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_periods', to='courses.Semester', verbose_name='Semester'),
        ),
        migrations.AddField(
            model_name='reportcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='reportcomment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.Report'),
        ),
        migrations.AddField(
            model_name='report',
            name='project_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='projects.ProjectStudent'),
        ),
        migrations.AddField(
            model_name='report',
            name='reporting_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='projects.ReportingPeriod'),
        ),
        migrations.AddField(
            model_name='projectstudent',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='projectstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='project',
            name='reviewers',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('group__role', 9), ('is_staff', True), _connector='OR'), related_name='project_reviewers', to=settings.AUTH_USER_MODEL, verbose_name='Reviewers'),
        ),
        migrations.AddField(
            model_name='project',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Semester', verbose_name='Semester'),
        ),
        migrations.AddField(
            model_name='project',
            name='students',
            field=models.ManyToManyField(through='projects.ProjectStudent', to=settings.AUTH_USER_MODEL, verbose_name='Students'),
        ),
        migrations.AddField(
            model_name='project',
            name='supervisors',
            field=models.ManyToManyField(related_name='projects', to='projects.Supervisor', verbose_name='Supervisors'),
        ),
        migrations.AddField(
            model_name='practicecriteria',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='projects.Review', verbose_name='Review'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('report', 'reviewer')},
        ),
        migrations.AddConstraint(
            model_name='reportingperiod',
            constraint=models.CheckConstraint(check=models.Q(score_excellent__gt=django.db.models.expressions.F('score_good')), name='good_score_lt_excellent'),
        ),
        migrations.AddConstraint(
            model_name='reportingperiod',
            constraint=models.CheckConstraint(check=models.Q(score_good__gt=django.db.models.expressions.F('score_pass')), name='pass_score_lt_good'),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('project_student', 'reporting_period')},
        ),
        migrations.AlterUniqueTogether(
            name='projectstudent',
            unique_together={('student', 'project')},
        ),
    ]
