# Generated by Django 2.2.5 on 2019-09-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190830_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='last_name',
            field=models.CharField(default='stub', max_length=150, verbose_name='Last Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervisor',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, verbose_name='Patronymic'),
        ),
        migrations.RenameField(
            model_name='supervisor',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='supervisor',
            old_name='workplace',
            new_name='occupation',
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='First Name'),
        ),
    ]
