# Generated by Django 2.2.5 on 2019-09-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190911_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='supervisor',
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='first_name',
            field=models.CharField(max_length=45, verbose_name='First Name'),
        ),
    ]
