# Generated by Django 2.1.8 on 2019-04-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_canceled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='score_technologies',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Listed, but not explained why.'), (1, '1 - The student does not understand about everything and does not try to understand, but knows something'), (2, '2 - Understands why choose one or the other technology')], null=True, verbose_name='The choice of technologies or method of integration with the existing development'),
        ),
        migrations.AlterField(
            model_name='report',
            name='score_usefulness',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Does not understand'), (1, '1 - Writing something about the usefulness'), (2, '2 - Understands and explains')], null=True, verbose_name='Possible uses and scenarios'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_technologies',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Listed, but not explained why.'), (1, '1 - The student does not understand about everything and does not try to understand, but knows something'), (2, '2 - Understands why choose one or the other technology')], null=True, verbose_name='The choice of technologies or method of integration with the existing development'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_usefulness',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Does not understand'), (1, '1 - Writing something about the usefulness'), (2, '2 - Understands and explains')], null=True, verbose_name='Possible uses and scenarios'),
        ),
    ]
