# Generated by Django 2.2.5 on 2019-09-18 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Select a project that is the continuation of the current one.', null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.Project', verbose_name='Continuation of Work'),
        ),
    ]
