# Generated by Django 2.2 on 2019-04-26 13:39

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20190426_1339'),
        ('learning', '0008_auto_20190426_1339'),
        ('projects', '0006_auto_20190412_0909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supervisor',
            options={'verbose_name': 'Supervisor', 'verbose_name_plural': 'Supervisors'},
        ),
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Helps to distinguish student reports for the project.', max_length=150, verbose_name='Label')),
                ('start_on', models.DateField(help_text='First day of the report period.', verbose_name='Start On')),
                ('end_on', models.DateField(help_text='The last day of the report period.', verbose_name='End On')),
                ('project_type', models.CharField(blank=True, choices=[('practice', 'StudentProject|Practice'), ('research', 'StudentProject|Research')], max_length=10, null=True, verbose_name='StudentProject|Type')),
                ('score_excellent', models.SmallIntegerField(blank=True, help_text='Projects with final score >= this value will be graded as Excellent', null=True, verbose_name='Projects|Border for excellent')),
                ('score_good', models.SmallIntegerField(blank=True, help_text='Projects with final score in [GOOD; EXCELLENT) will be graded as Good.', null=True, verbose_name='Projects|Border for good')),
                ('score_pass', models.SmallIntegerField(blank=True, help_text='Projects with final score in [PASS; GOOD) will be graded as Pass, with score < PASS as Unsatisfactory.', null=True, verbose_name='Projects|Border for pass')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='learning.Branch', verbose_name='Branch')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_periods', to='courses.Semester', verbose_name='Semester')),
            ],
            options={
                'verbose_name': 'Reporting Period',
                'verbose_name_plural': 'Reporting Periods',
            },
        ),
        migrations.AddConstraint(
            model_name='reportingperiod',
            constraint=models.CheckConstraint(check=models.Q(score_excellent__gt=django.db.models.expressions.F('score_good')), name='good_score_lt_excellent'),
        ),
        migrations.AddConstraint(
            model_name='reportingperiod',
            constraint=models.CheckConstraint(check=models.Q(score_good__gt=django.db.models.expressions.F('score_pass')), name='pass_score_lt_good'),
        ),
    ]
