# Generated by Django 3.0.9 on 2020-08-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200818_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterField(
            model_name='projectstudent',
            name='final_grade',
            field=models.CharField(choices=[('not_graded', 'ProjectGradeTypes|Not graded'), ('unsatisfactory', 'ProjectGradeTypes|Unsatisfactory'), ('pass', 'ProjectGradeTypes|Pass'), ('good', 'ProjectGradeTypes|Good'), ('excellent', 'ProjectGradeTypes|Excellent')], default='not_graded', max_length=15, verbose_name='Final grade'),
        ),
    ]
