# Generated by Django 2.2.1 on 2019-05-17 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20190515_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reporting_period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='projects.ReportingPeriod'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='project_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.ProjectStudent'),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('project_student', 'reporting_period')},
        ),
    ]
