# Generated by Django 2.2.3 on 2019-07-27 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0019_remove_enrollmentinvitation_expire_at'),
        ('projects', '0012_auto_20190528_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingperiod',
            name='branch_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='learning.Branch', to_field='code', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='project',
            name='reviewers',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('group__role', 9), ('is_staff', True), _connector='OR'), related_name='project_reviewers', to=settings.AUTH_USER_MODEL, verbose_name='Reviewers'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('o', 'Other/Prefer Not to Say')], max_length=1, verbose_name='Gender'),
        ),
    ]
