# Generated by Django 2.2.3 on 2019-07-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20190727_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportingperiod',
            name='branch',
        ),
        migrations.RenameField(
            model_name='reportingperiod',
            old_name='branch_new',
            new_name='branch',
        ),
    ]
