# Generated by Django 2.2.4 on 2019-08-14 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_branch'),
        ('projects', '0016_auto_20190813_1738'),
        ('learning', '0025_auto_20190813_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='branch_new2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='reportingperiod',
            name='branch_new2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Branch', verbose_name='Branch'),
        ),
    ]
