# Generated by Django 2.2.4 on 2019-08-14 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20190814_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Branch', verbose_name='Branch'),
        ),
    ]
