# Generated by Django 2.2.4 on 2019-08-15 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20190815_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='city',
        ),
    ]
