# Generated by Django 2.1.3 on 2018-12-28 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internshipcategory',
            options={'ordering': ['sort'], 'verbose_name': 'Internship Category', 'verbose_name_plural': 'Internship Categories'},
        ),
    ]
