# Generated by Django 2.2.1 on 2019-06-28 08:30

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
        migrations.AddField(
            model_name='announcement',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Recommended dimensions ', null=True, upload_to='announcements/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='event_date_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='announcements.TaggedAnnouncement', to='announcements.AnnouncementTag', verbose_name='Tags'),
        ),
    ]
