# Generated by Django 2.2.4 on 2019-08-30 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcements', '0001_initial'),
        ('publications', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementeventdetails',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='_announcementeventdetails_speakers_+', to='publications.Speaker', verbose_name='Speakers'),
        ),
        migrations.AddField(
            model_name='announcementeventdetails',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Location', verbose_name='Venue'),
        ),
    ]
