# Generated by Django 2.2.1 on 2019-06-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_auto_20190628_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='short_description',
            field=models.TextField(default='', verbose_name='Short Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Recommended dimensions 600x400', null=True, upload_to='announcements/', verbose_name='Photo'),
        ),
    ]
