# Generated by Django 3.0.9 on 2020-09-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_auto_20200902_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='thumbnail',
            field=models.ImageField(blank=True, default='', help_text='Recommended dimensions 600x400', max_length=200, upload_to='announcements/', verbose_name='Photo'),
            preserve_default=False,
        ),
    ]
