# Generated by Django 2.2.1 on 2019-06-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_auto_20190628_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementtag',
            name='modifier',
            field=models.CharField(blank=True, help_text='This class could affect the tag view', max_length=20, null=True, verbose_name='Modifier'),
        ),
    ]
