# Generated by Django 2.2.1 on 2019-07-01 12:43

import announcements.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20190701_1242'),
        ('publications', '0007_auto_20190627_1242'),
        ('announcements', '0004_announcementtag_modifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=models.TextField(blank=True, help_text="Don't forget to add &lt;h3&gt;Title&lt;/h3&gt; on the first line", verbose_name='Detail Description'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='publish_start_at',
            field=models.DateTimeField(default=announcements.models.timezone_now, verbose_name='Publish Start at'),
        ),
        migrations.CreateModel(
            name='AnnouncementEventDetails',
            fields=[
                ('announcement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='event_details', serialize=False, to='announcements.Announcement')),
                ('starts_on', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('starts_at', models.TimeField(blank=True, null=True, verbose_name='Start Time')),
                ('ends_on', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('ends_at', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('speakers', models.ManyToManyField(related_name='_announcementeventdetails_speakers_+', to='publications.Speaker', verbose_name='Speakers')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Venue', verbose_name='Venue')),
            ],
            options={
                'verbose_name': 'Announcement Detail',
                'verbose_name_plural': 'Announcement Details',
            },
        ),
    ]
