# Generated by Django 2.2.1 on 2019-07-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_auto_20190701_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='event_actions',
            new_name='actions',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='event_date_at',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='event_place',
        ),
        migrations.AlterField(
            model_name='announcementeventdetails',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='_announcementeventdetails_speakers_+', to='publications.Speaker', verbose_name='Speakers'),
        ),
    ]
