# Generated by Django 2.2.4 on 2019-08-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0007_auto_20190705_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='slug',
            field=models.SlugField(help_text='Write the URL part after `compscicenter.ru/` If this is an open lecture, add `open-lecture-` prefix', verbose_name='Slug'),
        ),
    ]
