# Generated by Django 2.2.4 on 2019-08-14 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0008_auto_20190813_1738'),
        ('core', '0011_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementeventdetails',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Venue', verbose_name='Venue'),
        ),
    ]
