# Generated by Django 3.2.6 on 2021-08-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_params',
            field=models.JSONField(blank=True, default=dict, verbose_name='Task Parameters'),
        ),
    ]
