---
- import_tasks: check_vars.yml

- import_tasks: install.yml

- import_tasks: server.yml
  when: not redis_sentinel
  tags:
    - config

- import_tasks: sentinel.yml
  when: redis_sentinel
  tags:
    - config

- import_tasks: local_facts.yml
  when: redis_local_facts|bool
