---
- name: Upgrade all packages to the latest version
  apt:
    upgrade: dist
    update_cache: yes

- name: Set default locale LANG to UTF-8
  lineinfile: dest=/etc/default/locale line='LANG="en_US.utf8"' regexp='^LANG=' state=present insertafter=BOF

- name: Set default locale LC_ALL to UTF-8
  lineinfile: dest=/etc/environment line='LC_ALL="en_US.utf8"' regexp='^LC_ALL=' state=present insertafter=BOF

- name: Check if a reboot is required
  stat: path=/var/run/reboot-required get_md5=no
  register: reboot_file

- name: Reboot the server and wait for it to come back up.
  reboot:
  when: reboot_file.stat.exists == true

- name: Add python PPAs
  apt_repository:
    repo: "{{ item }}"
    update_cache: yes
  with_items:
    - 'ppa:deadsnakes/ppa'

- name: Unlock python package for upgrade if it was hold before.
  dpkg_selections:
    name: "{{ python_pkg }}"
    selection: install

- name: Apt dependencies
  apt:
    name:
      - openssl
      - python-setuptools
  #    - python-dev
      - git
      - ntp
      - zsh
      - tmux
      - htop
      - build-essential
      # app dependencies
      - gettext
      # regular expressions support
      - libpcre3-dev
      - libpcre3
      - libxml2-dev
      - libxslt1-dev
      - libjpeg-dev
      - libpng-dev
      - libmagic-dev
      - libcurl4-gnutls-dev
      - libgnutls28-dev
      - "{{ python_pkg }}"
      - "{{ python_pkg }}-dev"
      - python-pycurl
      # LDAP support
      - ldap-utils
      - libldap2-dev
      - libsasl2-dev
      # - libssl-dev not sure we need this package to install python-ldap with pip
    state: present

- name: Register system python3 version
  command: /usr/bin/python3 -c "import sys; print('{}.{}'.format(sys.version_info.major, sys.version_info.minor));"
  register: system_python3_version
  tags:
    - ansible

- name: Check pip{{ system_python3_version.stdout }} exists
  command: pip{{ system_python3_version.stdout }} --version
  register: system_python3_pip_version_output
  ignore_errors: yes

- name: Download get-pip.py if neccessary
  get_url: url=https://bootstrap.pypa.io/get-pip.py
           dest=/tmp/get-pip.py
  when: system_python3_pip_version_output is failed

- name: Install pip for system python3
  command: "/usr/bin/python3 /tmp/get-pip.py"
  when: system_python3_pip_version_output is failed


- name: Install Ansible dependency for generating certificates
  pip:
    name: pyopenssl
    executable: pip{{ system_python3_version.stdout }}


- name: Get pip{{ python_version }} version
  command: pip{{ python_version }} --version
  register: pip_version_output
  ignore_errors: yes

- name: Download get-pip.py
  get_url: url=https://bootstrap.pypa.io/get-pip.py
           dest=/tmp/get-pip.py
  when: pip_version_output is failed

- name: install pip for {{ python_pkg }}
  command: "{{ python_pkg }} /tmp/get-pip.py"
  when: pip_version_output is failed

- name: Globally install {{ python_pkg }} dependencies
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    executable: pip{{ python_version }}
  with_items:
    - name: ipython
      version: "5.5.0"
    - name: virtualenv
      version: "16.7.0"
    - name: uwsgi
      version: "2.0.18"
    - name: uwsgitop
      version: "0.11"


- name: Create uwsgi config dir
  file:
    path: /etc/uwsgi
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy systemd uwsgi config
  template:
    src: emperor.uwsgi.service.jinja2
    dest: /etc/systemd/system/uwsgi.service
  tags:
    - uwsgi

- name: Copy uWSGI emperor.ini config
  template:
    src: emperor.ini.jinja2
    dest: /etc/uwsgi/emperor.ini
  tags:
    - uwsgi

- name: Create uwsgi config dir
  file: path=/etc/uwsgi/vassals state=directory
  tags:
    - uwsgi

- name: Ensure uWSGI is enabled after reboot
  systemd:
    name: uwsgi.service
    enabled: yes
    state: started

- name: Setup zsh for ec2 user
  include_tasks: zsh.yml
  with_items:
    - "{{ aws_ec2_user }}"

- name: Setup ntpd
  import_tasks: ntp.yml
  tags:
    - ntpd
    - ntp