# Generated by Django 2.1.5 on 2019-03-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('study_programs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AreaOfStudy',
            new_name='AcademicDiscipline',
        ),
    ]
