# Generated by Django 2.2.13 on 2020-08-03 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyprogramcoursegroup',
            name='study_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_groups', to='study_programs.StudyProgram', verbose_name='Study Program'),
        ),
    ]
