# Generated by Django 2.1.5 on 2019-03-14 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_auto_20190314_1519'),
        ('study_programs', '0002_auto_20190314_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyprogram',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='study_programs', to='learning.Branch', verbose_name='Branch'),
            preserve_default=False,
        ),
    ]
