# Generated by Django 3.1.7 on 2021-03-22 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('study_programs', '0002_auto_20200803_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicdiscipline',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sites.site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='academicdiscipline',
            name='code',
            field=models.CharField(max_length=10, verbose_name='PK|Code'),
        ),
    ]
