# Generated by Django 2.1.5 on 2019-03-14 15:19

from django.db import migrations, models
import django.db.models.deletion


def sync_data(apps, schema_editor):
    StudyProgram = apps.get_model('study_programs', 'StudyProgram')
    Branch = apps.get_model('learning', 'Branch')

    for sp in StudyProgram.objects.all():
        if sp.city_id == "online":
            city_code = "distance"
        else:
            city_code = sp.city_id
        branch = Branch.objects.get(code=city_code)
        sp.branch_id = branch.pk
        sp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_auto_20190314_1519'),
        ('study_programs', '0002_auto_20190314_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyprogram',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='study_programs', to='learning.Branch', verbose_name='Branch'),
            preserve_default=False,
        ),
        migrations.RunPython(sync_data),
    ]
