# Generated by Django 3.2.18 on 2024-09-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_programs', '0003_auto_20210322_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicdiscipline',
            name='hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='AcademicDiscipline|hours'),
        ),
    ]
