# Generated by Django 2.1.5 on 2019-03-15 13:10

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('study_programs', '0003_studyprogram_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicdiscipline',
            name='cover',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='academic_disciplines/', verbose_name='AcademicDiscipline|cover'),
        ),
    ]
