# Generated by Django 2.1.5 on 2019-03-17 15:18

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('study_programs', '0004_academicdiscipline_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicdiscipline',
            name='icon',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='academic_disciplines/', verbose_name='AcademicDiscipline|icon'),
        ),
    ]
