# Generated by Django 2.1.5 on 2019-03-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_programs', '0005_academicdiscipline_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyprogram',
            old_name='area',
            new_name='academic_discipline',
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show on syllabus page. Other activity flags for selected city and academic discipline will be deactivated.', verbose_name='Activity'),
        ),
        migrations.AlterField(
            model_name='academicdiscipline',
            name='icon',
            field=models.FileField(blank=True, upload_to='academic_disciplines/', verbose_name='AcademicDiscipline|icon'),
        ),
    ]
