# Generated by Django 2.2.3 on 2019-07-27 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0019_remove_enrollmentinvitation_expire_at'),
        ('study_programs', '0006_auto_20190318_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyprogram',
            name='branch_new',
            field=models.ForeignKey(default='spb', on_delete=django.db.models.deletion.CASCADE, related_name='study_programs_new', to='learning.Branch', to_field='code', verbose_name='Branch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='academic_discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='study_program', to='study_programs.AcademicDiscipline', verbose_name='Area of Study'),
        ),
    ]
