# Generated by Django 2.2.3 on 2019-07-27 17:16

from django.db import migrations


def copy_branch(apps, schema_editor):
    StudyProgram = apps.get_model('study_programs', 'StudyProgram')
    for sp in StudyProgram.objects.select_related('branch'):
        sp.branch_new_id = sp.branch.code
        sp.save(update_fields=['branch_new_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('study_programs', '0007_auto_20190727_1716'),
    ]

    operations = [
        migrations.RunPython(copy_branch)
    ]
