# Generated by Django 2.2.3 on 2019-07-27 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_programs', '0008_auto_20190727_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyprogram',
            name='branch',
        ),
        migrations.RenameField(
            model_name='studyprogram',
            old_name='branch_new',
            new_name='branch',
        ),
    ]
