# Generated by Django 2.2.3 on 2019-07-27 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_programs', '0009_auto_20190727_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyprogram',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_programs', to='learning.Branch', to_field='code', verbose_name='Branch'),
        ),
    ]
