# Generated by Django 2.2.4 on 2019-08-13 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_programs', '0010_auto_20190727_1739'),
        ('core', '0006_branch'),
        ('learning', '0023_auto_20190813_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyprogram',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_programs', to='core.Branch', to_field='code', verbose_name='Branch'),
        ),
    ]
