# Generated by Django 2.2.4 on 2019-08-14 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_programs', '0013_auto_20190814_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyprogram',
            name='branch',
        ),
        migrations.RenameField(
            model_name='studyprogram',
            old_name='branch_new2',
            new_name='branch',
        ),
    ]
