# Generated by Django 2.2.4 on 2019-08-14 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_programs', '0014_auto_20190814_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyprogram',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_programs', to='core.Branch', verbose_name='Branch'),
        ),
    ]
