# Generated by Django 2.2.4 on 2019-08-20 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_programs', '0015_auto_20190814_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyprogram',
            name='city',
        ),
    ]
