# Generated by Django 2.2.4 on 2019-08-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_programs', '0016_remove_studyprogram_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyprogram',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show on syllabus page. Other activity flags for selected branch and academic discipline will be deactivated.', verbose_name='Activity'),
        ),
    ]
