# Generated by Django 3.2.12 on 2022-03-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='order',
            field=models.PositiveIntegerField(default=512, verbose_name='Order'),
        ),
    ]
