# Generated by Django 2.1.5 on 2019-01-09 13:44

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='InternationalSchool|name')),
                ('link', models.URLField(verbose_name='InternationalSchool|Link')),
                ('place', models.CharField(max_length=255, verbose_name='InternationalSchool|place')),
                ('deadline', models.DateField(verbose_name='InternationalSchool|Deadline')),
                ('starts_at', models.DateField(verbose_name='InternationalSchool|Start')),
                ('ends_at', models.DateField(blank=True, null=True, verbose_name='InternationalSchool|End')),
                ('has_grants', models.BooleanField(default=False, verbose_name='InternationalSchool|Grants')),
            ],
            options={
                'verbose_name': 'International school',
                'verbose_name_plural': 'International schools',
                'db_table': 'international_schools',
                'ordering': ['name'],
            },
        ),
    ]
