# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentProject',
            new_name='Project',
        ),
    ]
