# Generated by Django 2.1.1 on 2018-11-06 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20181019_1339'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Semester', verbose_name='Semester'),
        ),
    ]
