# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-30 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcomment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.Report'),
        ),
        migrations.AlterField(
            model_name='review',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.Report'),
        ),
    ]
