# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 16:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models, connection, transaction
import django.db.models.deletion


def update_forward(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    old_table = Project.students.through._meta.db_table
    ProjectStudent = apps.get_model('projects', 'ProjectStudent')
    new_table = ProjectStudents._meta.db_table
    cursor = connection.cursor()
    with transaction.atomic():
        cursor.execute("INSERT INTO %s (project_id, student_id) "
                       "SELECT project_id, cscuser_id FROM %s" %
                       (new_table, old_table))


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_auto_20160714_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Project students',
                'verbose_name': 'Project student',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='students2',
            field=models.ManyToManyField(related_name='projects', through='projects.ProjectStudents', to=settings.AUTH_USER_MODEL, verbose_name='Students'),
        ),
        migrations.AlterUniqueTogether(
            name='projectstudents',
            unique_together=set([('student', 'project')]),
        ),
        migrations.RunPython(update_forward),
    ]
