# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20160714_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='students',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='students2',
            new_name='students',
        ),
    ]
