# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-30 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180730_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='project_student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='projects.ProjectStudent'),
        ),
    ]
