# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 10:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='students',
            field=models.ManyToManyField(through='projects.ProjectStudent', to=settings.AUTH_USER_MODEL, verbose_name='Students'),
        ),
    ]
