# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 11:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20160715_1342'),
    ]

    # state_operations = [
    #     migrations.RenameModel(
    #         old_name='ProjectStudents',
    #         new_name='ProjectStudent',
    #     ),
    # ]

    operations = [
        # migrations.SeparateDatabaseAndState(state_operations=state_operations),
        migrations.AlterField(
            model_name='project',
            name='students',
            field=models.ManyToManyField(through='projects.ProjectStudent', to=settings.AUTH_USER_MODEL, verbose_name='Students'),
        ),
    ]
