# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 15:17
from __future__ import unicode_literals

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20160715_1410'),
    ]

    operations = [
        migrations.RenameField('project', 'grade', 'final_grade'),
    ]
