# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20160718_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='final_grade',
        ),
    ]
