# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 13:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_project_final_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Student project', 'verbose_name_plural': 'Student projects'},
        ),
        migrations.AddField(
            model_name='projectstudent',
            name='presentation_grade',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Presentation grade'),
        ),
        migrations.AddField(
            model_name='projectstudent',
            name='supervisor_grade',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-15), django.core.validators.MaxValueValidator(15)], verbose_name='Supervisor grade'),
        ),
    ]
