# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 13:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0010_auto_20160719_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='reviewers',
            field=models.ManyToManyField(related_name='project_reviewers', to=settings.AUTH_USER_MODEL, verbose_name='Reviewers'),
        ),
    ]
