# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 13:57
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_reviewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='project_reviewers', to=settings.AUTH_USER_MODEL, verbose_name='Reviewers'),
        ),
        migrations.AlterField(
            model_name='projectstudent',
            name='presentation_grade',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Integer value from 0 to 10', null=True, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Presentation grade'),
        ),
        migrations.AlterField(
            model_name='projectstudent',
            name='supervisor_grade',
            field=models.SmallIntegerField(blank=True, help_text='Integer value from -15 to 15', null=True, validators=[django.core.validators.MinValueValidator(-15), django.core.validators.MaxValueValidator(15)], verbose_name='Supervisor grade'),
        ),
    ]
