# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 14:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import learning.projects.models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20160719_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('score_global_issue', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Does not understand the task at all'), (1, 'Understands, but very superficial'), (2, 'Understands everything')], help_text='Criterion #1', null=True, verbose_name='The global task for term')),
                ('score_global_issue_note', models.TextField(blank=True, help_text='LaTeX+<a href="http://en.wikipedia.org/wiki/Markdown">Markdown</a>+HTML is enabled', null=True, verbose_name='Note for criterion #1')),
                ('score_usefulness', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Does not understand'), (1, 'Writing something about the usefulness'), (2, 'Understands and explains')], help_text='Criterion #2', null=True, verbose_name='Who and why this can be useful.')),
                ('score_usefulness_note', models.TextField(blank=True, help_text='LaTeX+<a href="http://en.wikipedia.org/wiki/Markdown">Markdown</a>+HTML is enabled', null=True, verbose_name='Note for criterion #2')),
                ('score_progress', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Understand only theory, or even less'), (1, 'Some progress, but not enough'), (2, 'The normal rate of work')], help_text='Criterion #3', null=True, verbose_name='What has been done since the start of the project.')),
                ('score_progress_note', models.TextField(blank=True, help_text='LaTeX+<a href="http://en.wikipedia.org/wiki/Markdown">Markdown</a>+HTML is enabled', null=True, verbose_name='Note for criterion #3')),
                ('score_problems', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Problems not mentioned in the report'), (1, 'Problems are mentioned without any details'), (2, 'Problems are mentioned and explained how they been solved')], help_text='Criterion #4', null=True, verbose_name='What problems have arisen in the process.')),
                ('score_problems_note', models.TextField(blank=True, help_text='LaTeX+<a href="http://en.wikipedia.org/wiki/Markdown">Markdown</a>+HTML is enabled', null=True, verbose_name='Note for criterion #4')),
                ('score_technologies', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Listed, but not explained why.'), (1, 'The student does not understand about everything and does not try to understand, but knows something'), (2, 'Understands why choose one or the other technology')], help_text='Criterion #5', null=True, verbose_name='What technologies are used.')),
                ('score_technologies_note', models.TextField(blank=True, help_text='LaTeX+<a href="http://en.wikipedia.org/wiki/Markdown">Markdown</a>+HTML is enabled', null=True, verbose_name='Note for criterion #5')),
                ('score_plans', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Much less than what has already been done, or the student does not understand them'), (1, 'It seems to have plans of normal size, but does not understand what to do.'), (2, 'All right with them')], help_text='Criterion #6', null=True, verbose_name='Future plan')),
                ('score_plans_note', models.TextField(blank=True, help_text='LaTeX+<a href="http://en.wikipedia.org/wiki/Markdown">Markdown</a>+HTML is enabled', null=True, verbose_name='Note for criterion #6')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('review', 'Review'), ('rating', 'Waiting for final score'), ('completed', 'Completed')], default='sent', max_length=15, verbose_name='Status')),
                ('description', models.TextField(blank=True, help_text='LaTeX+<a href="http://en.wikipedia.org/wiki/Markdown">Markdown</a>+HTML is enabled', verbose_name='Description')),
                ('file', models.FileField(blank=True, null=True, upload_to=learning.projects.models.report_file_name, verbose_name='Report file')),
                ('score_activity', models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(1)], verbose_name='Student activity in cvs')),
                ('score_quality', models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(2)], verbose_name="Report's quality")),
                ('project_student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectStudent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('score_global_issue', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Does not understand the task at all'), (1, 'Understands, but very superficial'), (2, 'Understands everything')], help_text='Criterion #1', null=True, verbose_name='The global task for term')),
                ('score_global_issue_note', models.TextField(blank=True, help_text='LaTeX+<a href="http://en.wikipedia.org/wiki/Markdown">Markdown</a>+HTML is enabled', null=True, verbose_name='Note for criterion #1')),
                ('score_usefulness', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Does not understand'), (1, 'Writing something about the usefulness'), (2, 'Understands and explains')], help_text='Criterion #2', null=True, verbose_name='Who and why this can be useful.')),
                ('score_usefulness_note', models.TextField(blank=True, help_text='LaTeX+<a href="http://en.wikipedia.org/wiki/Markdown">Markdown</a>+HTML is enabled', null=True, verbose_name='Note for criterion #2')),
                ('score_progress', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Understand only theory, or even less'), (1, 'Some progress, but not enough'), (2, 'The normal rate of work')], help_text='Criterion #3', null=True, verbose_name='What has been done since the start of the project.')),
                ('score_progress_note', models.TextField(blank=True, help_text='LaTeX+<a href="http://en.wikipedia.org/wiki/Markdown">Markdown</a>+HTML is enabled', null=True, verbose_name='Note for criterion #3')),
                ('score_problems', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Problems not mentioned in the report'), (1, 'Problems are mentioned without any details'), (2, 'Problems are mentioned and explained how they been solved')], help_text='Criterion #4', null=True, verbose_name='What problems have arisen in the process.')),
                ('score_problems_note', models.TextField(blank=True, help_text='LaTeX+<a href="http://en.wikipedia.org/wiki/Markdown">Markdown</a>+HTML is enabled', null=True, verbose_name='Note for criterion #4')),
                ('score_technologies', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Listed, but not explained why.'), (1, 'The student does not understand about everything and does not try to understand, but knows something'), (2, 'Understands why choose one or the other technology')], help_text='Criterion #5', null=True, verbose_name='What technologies are used.')),
                ('score_technologies_note', models.TextField(blank=True, help_text='LaTeX+<a href="http://en.wikipedia.org/wiki/Markdown">Markdown</a>+HTML is enabled', null=True, verbose_name='Note for criterion #5')),
                ('score_plans', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Much less than what has already been done, or the student does not understand them'), (1, 'It seems to have plans of normal size, but does not understand what to do.'), (2, 'All right with them')], help_text='Criterion #6', null=True, verbose_name='Future plan')),
                ('score_plans_note', models.TextField(blank=True, help_text='LaTeX+<a href="http://en.wikipedia.org/wiki/Markdown">Markdown</a>+HTML is enabled', null=True, verbose_name='Note for criterion #6')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Report')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
