# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_report_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Reports', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AddField(
            model_name='report',
            name='final_score_note',
            field=models.TextField(blank=True, help_text='LaTeX+<a href="http://en.wikipedia.org/wiki/Markdown">Markdown</a>+HTML is enabled', null=True, verbose_name='Final score note'),
        ),
    ]
