# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import learning.projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20160720_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='supervisor_presentation',
            field=models.FileField(blank=True, upload_to=learning.projects.models.project_presentation_files, verbose_name='Supervisor presentation'),
        ),
    ]
