# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-18 15:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import learning.projects.models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0015_project_supervisor_presentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('text', models.TextField(blank=True, help_text='LaTeX+Markdown is enabled', verbose_name='ReportComment|text')),
                ('attached_file', models.FileField(blank=True, upload_to=learning.projects.models.report_comment_attachment_upload_to)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Report')),
            ],
            options={
                'ordering': ['created'],
                'verbose_name': 'Report comment',
                'verbose_name_plural': 'Report comments',
            },
        ),
    ]
