# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_review_reviewer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set([('report', 'reviewer')]),
        ),
    ]
