# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20160819_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='score_global_issue_note',
        ),
        migrations.RemoveField(
            model_name='report',
            name='score_plans_note',
        ),
        migrations.RemoveField(
            model_name='report',
            name='score_problems_note',
        ),
        migrations.RemoveField(
            model_name='report',
            name='score_progress_note',
        ),
        migrations.RemoveField(
            model_name='report',
            name='score_technologies_note',
        ),
        migrations.RemoveField(
            model_name='report',
            name='score_usefulness_note',
        ),
        migrations.AlterField(
            model_name='review',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Check if you already completed the assessment.', verbose_name='Completed'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_global_issue_note',
            field=models.TextField(blank=True, null=True, verbose_name='Note for criterion #1'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_plans_note',
            field=models.TextField(blank=True, null=True, verbose_name='Note for criterion #6'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_problems_note',
            field=models.TextField(blank=True, null=True, verbose_name='Note for criterion #4'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_progress_note',
            field=models.TextField(blank=True, null=True, verbose_name='Note for criterion #3'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_technologies_note',
            field=models.TextField(blank=True, null=True, verbose_name='Note for criterion #5'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_usefulness_note',
            field=models.TextField(blank=True, null=True, verbose_name='Note for criterion #2'),
        ),
    ]
