# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20160825_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='description',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='report',
            name='score_global_issue',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Does not understand the task at all'), (1, '1 - Understands, but very superficial'), (2, '2 - Understands everything')], help_text='Criterion #1', null=True, verbose_name='The global task for term'),
        ),
        migrations.AlterField(
            model_name='report',
            name='score_plans',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Much less than what has already been done, or the student does not understand them'), (1, '1 - It seems to have plans of normal size, but does not understand what to do.'), (2, '2 - All right with them')], help_text='Criterion #6', null=True, verbose_name='Future plan'),
        ),
        migrations.AlterField(
            model_name='report',
            name='score_problems',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Problems not mentioned in the report'), (1, '1 - Problems are mentioned without any details'), (2, '2 - Problems are mentioned and explained how they been solved')], help_text='Criterion #4', null=True, verbose_name='What problems have arisen in the process.'),
        ),
        migrations.AlterField(
            model_name='report',
            name='score_progress',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Understand only theory, or even less'), (1, '1 - Some progress, but not enough'), (2, '2 - The normal rate of work')], help_text='Criterion #3', null=True, verbose_name='What has been done since the start of the project.'),
        ),
        migrations.AlterField(
            model_name='report',
            name='score_technologies',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Listed, but not explained why.'), (1, '1 - The student does not understand about everything and does not try to understand, but knows something'), (2, '2 - Understands why choose one or the other technology')], help_text='Criterion #5', null=True, verbose_name='What technologies are used.'),
        ),
        migrations.AlterField(
            model_name='report',
            name='score_usefulness',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Does not understand'), (1, '1 - Writing something about the usefulness'), (2, '2 - Understands and explains')], help_text='Criterion #2', null=True, verbose_name='Who and why this can be useful.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_global_issue',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Does not understand the task at all'), (1, '1 - Understands, but very superficial'), (2, '2 - Understands everything')], help_text='Criterion #1', null=True, verbose_name='The global task for term'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_plans',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Much less than what has already been done, or the student does not understand them'), (1, '1 - It seems to have plans of normal size, but does not understand what to do.'), (2, '2 - All right with them')], help_text='Criterion #6', null=True, verbose_name='Future plan'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_problems',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Problems not mentioned in the report'), (1, '1 - Problems are mentioned without any details'), (2, '2 - Problems are mentioned and explained how they been solved')], help_text='Criterion #4', null=True, verbose_name='What problems have arisen in the process.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_progress',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Understand only theory, or even less'), (1, '1 - Some progress, but not enough'), (2, '2 - The normal rate of work')], help_text='Criterion #3', null=True, verbose_name='What has been done since the start of the project.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_technologies',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Listed, but not explained why.'), (1, '1 - The student does not understand about everything and does not try to understand, but knows something'), (2, '2 - Understands why choose one or the other technology')], help_text='Criterion #5', null=True, verbose_name='What technologies are used.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_usefulness',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Does not understand'), (1, '1 - Writing something about the usefulness'), (2, '2 - Understands and explains')], help_text='Criterion #2', null=True, verbose_name='Who and why this can be useful.'),
        ),
    ]
