# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-06 10:11
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import learning.projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20160825_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='presentation',
            field=models.FileField(blank=True, upload_to=learning.projects.models.project_presentation_files, verbose_name='Participants presentation'),
        ),
        migrations.AlterField(
            model_name='report',
            name='final_score_note',
            field=models.TextField(blank=True, null=True, verbose_name='Final score note'),
        ),
        migrations.AlterField(
            model_name='report',
            name='score_activity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1')], null=True, validators=[django.core.validators.MaxValueValidator(1)], verbose_name='Student activity in cvs'),
        ),
        migrations.AlterField(
            model_name='report',
            name='score_global_issue',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Does not understand the task at all'), (1, '1 - Understands, but very superficial'), (2, '2 - Understands everything')], null=True, verbose_name='The global task for term'),
        ),
        migrations.AlterField(
            model_name='report',
            name='score_plans',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Much less than what has already been done, or the student does not understand them'), (1, '1 - It seems to have plans of normal size, but does not understand what to do.'), (2, '2 - All right with them')], null=True, verbose_name='Future plan'),
        ),
        migrations.AlterField(
            model_name='report',
            name='score_problems',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Problems not mentioned in the report'), (1, '1 - Problems are mentioned without any details'), (2, '2 - Problems are mentioned and explained how they been solved')], null=True, verbose_name='What problems have arisen in the process.'),
        ),
        migrations.AlterField(
            model_name='report',
            name='score_progress',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Understand only theory, or even less'), (1, '1 - Some progress, but not enough'), (2, '2 - The normal rate of work')], null=True, verbose_name='What has been done since the start of the project.'),
        ),
        migrations.AlterField(
            model_name='report',
            name='score_quality',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2')], null=True, validators=[django.core.validators.MaxValueValidator(2)], verbose_name="Report's quality"),
        ),
        migrations.AlterField(
            model_name='report',
            name='score_technologies',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Listed, but not explained why.'), (1, '1 - The student does not understand about everything and does not try to understand, but knows something'), (2, '2 - Understands why choose one or the other technology')], null=True, verbose_name='What technologies are used.'),
        ),
        migrations.AlterField(
            model_name='report',
            name='score_usefulness',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Does not understand'), (1, '1 - Writing something about the usefulness'), (2, '2 - Understands and explains')], null=True, verbose_name='Who and why this can be useful.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Project reviewer'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_global_issue',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Does not understand the task at all'), (1, '1 - Understands, but very superficial'), (2, '2 - Understands everything')], null=True, verbose_name='The global task for term'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_plans',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Much less than what has already been done, or the student does not understand them'), (1, '1 - It seems to have plans of normal size, but does not understand what to do.'), (2, '2 - All right with them')], null=True, verbose_name='Future plan'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_problems',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Problems not mentioned in the report'), (1, '1 - Problems are mentioned without any details'), (2, '2 - Problems are mentioned and explained how they been solved')], null=True, verbose_name='What problems have arisen in the process.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_progress',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Understand only theory, or even less'), (1, '1 - Some progress, but not enough'), (2, '2 - The normal rate of work')], null=True, verbose_name='What has been done since the start of the project.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_technologies',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Listed, but not explained why.'), (1, '1 - The student does not understand about everything and does not try to understand, but knows something'), (2, '2 - Understands why choose one or the other technology')], null=True, verbose_name='What technologies are used.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_usefulness',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0 - Does not understand'), (1, '1 - Writing something about the usefulness'), (2, '2 - Understands and explains')], null=True, verbose_name='Who and why this can be useful.'),
        ),
    ]
