# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20160906_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='presentation_url',
            field=models.URLField(blank=True, help_text='Yandex.Disk support only', null=True, verbose_name='Link to participants presentation'),
        ),
        migrations.AddField(
            model_name='project',
            name='supervisor_presentation_url',
            field=models.URLField(blank=True, help_text='Supported only links from Yandex.Disk', null=True, verbose_name='Link to supervisor presentation'),
        ),
    ]
