# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-21 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20160920_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='presentation_url',
            field=models.URLField(blank=True, help_text='Supported public link to Yandex.Disk only', null=True, verbose_name='Link to participants presentation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='supervisor_presentation_url',
            field=models.URLField(blank=True, help_text='Supported public link to Yandex.Disk only', null=True, verbose_name='Link to supervisor presentation'),
        ),
    ]
