# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-26 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20160921_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='presentation_slideshare_url',
            field=models.URLField(blank=True, null=True, verbose_name='SlideShare URL for participants presentation'),
        ),
        migrations.AddField(
            model_name='project',
            name='supervisor_presentation_slideshare_url',
            field=models.URLField(blank=True, null=True, verbose_name='SlideShare URL for supervisor presentation'),
        ),
    ]
