# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-26 14:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20160926_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='canceled',
            field=models.BooleanField(default=False, help_text='Check if all participants leave project before reporting period'),
        ),
        migrations.AlterField(
            model_name='report',
            name='score_activity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Poor commit history'), (1, 'Normal activity')], null=True, validators=[django.core.validators.MaxValueValidator(1)], verbose_name='Student activity in cvs'),
        ),
        migrations.AlterField(
            model_name='report',
            name='score_quality',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Bad report quality and unrelated comments'), (1, 'Bad report quality, but sensible comments'), (2, 'Good report quality and sensible comments')], null=True, validators=[django.core.validators.MaxValueValidator(2)], verbose_name="Report's quality"),
        ),
    ]
