# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-09 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_auto_20161026_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='score_activity_note',
            field=models.TextField(blank=True, null=True, verbose_name='Note for criterion `score_activity`'),
        ),
        migrations.AddField(
            model_name='report',
            name='score_quality_note',
            field=models.TextField(blank=True, null=True, verbose_name='Note for criterion `score_quality`'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='How to style text read <a href="/comment-the-right-way/" target="_blank">here</a>. Partially HTML is enabled too.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='report',
            name='text',
            field=models.TextField(blank=True, help_text='How to style text read <a href="/comment-the-right-way/" target="_blank">here</a>. Partially HTML is enabled too.', verbose_name='Description'),
        ),
    ]
