apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "{{ k8s_namespace}}"
  name: "queue"
spec:
  replicas: 1
  revisionHistoryLimit: {{ revision_history_limit | default('3') }}
  selector:
    matchLabels:
      app: "queue"
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: "queue"
    spec:
      terminationGracePeriodSeconds: {{ termination_grace_period_seconds | default('30') }}
      securityContext:
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
      volumes:
        - name: ldap-certs
          secret:
            secretName: {{ backend_service_name }}-backend
            items:
              - key: LDAP_CA_CERT_FILE
                path: ca.crt
      containers:
        - name: worker
          image: "{{ docker_registry }}/{{ backend_django_image_name }}:{{ backend_django_image_tag }}"
          lifecycle:
            preStop:
              exec:
                command: [ '/bin/sh', '-c', 'sleep 5' ]
          volumeMounts:
            - mountPath: /etc/ldap/certs/
              name: ldap-certs
          command: ["/bin/sh"]
          args: ["-c", "python manage.py rqworker high default --with-scheduler"]
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 200m
              memory: 512Mi
          env:
            {% filter indent(width=12) %}{% include 'app-env.yaml' %}{% endfilter %}
