NOTIFICATION_TYPES = [
    "NEW_PROJECT_REPORT",
    "NEW_PROJECT_REPORT_COMMENT",
    # All project reports checked by curators
    "PROJECT_REPORTS_IN_REVIEW_STATE",
    "PROJECT_REPORTING_STARTED",
    "PROJECT_REPORTING_ENDED",
    "PROJECT_REVIEWER_ENROLLED",
    "PROJECT_REPORT_REVIEW_COMPLETED",
    "PROJECT_REPORT_COMPLETED",
    "NEW_ASSIGNMENT",
    "NEW_ASSIGNMENT_NEWS",
    "NEW_ASSIGNMENT_SUBMISSION",
    "ASSIGNMENT_DEADLINE_UPDATED",
    "NEW_ASSIGNMENT_SUBMISSION_COMMENT",
]
