# tasks file for supervisor
---

- name: install | supervisor (specific version)
  pip:
    name: supervisor
    version: "{{ supervisor_version }}"
  when: "supervisor_version != 'latest'"
  tags:
    - supervisor-install-specific

- name: install | supervisor (latest version)
  pip:
    name: supervisor
    state: "{{ supervisor_version }}"
  when: "supervisor_version == 'latest'"
  tags:
    - supervisor-install-latest
