# tasks file for supervisor
---
- import_tasks: install.yml
  tags:
    - configuration
    - supervisor
    - supervisor-install

- import_tasks: configure.yml
  tags:
    - configuration
    - supervisor
    - supervisor-configure

- import_tasks: service-initd.yml
  when: ansible_service_mgr != 'systemd'
  tags:
    - configuration
    - supervisor
    - supervisor-configure
    - supervisor-configure-initd

- import_tasks: service-systemd.yml
  when: ansible_service_mgr == 'systemd'
  tags:
    - configuration
    - supervisor
    - supervisor-configure
    - supervisor-configure-systemd

- import_tasks: programs.yml
  tags:
    - configuration
    - supervisor
    - supervisor-programs

- import_tasks: groups.yml
  tags:
    - configuration
    - supervisor
    - supervisor-groups

- name: start and enable service
  service:
    name: supervisor
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - configuration
    - supervisor
    - supervisor-start-enable-service
