# Generated by Django 2.2.4 on 2019-08-30 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study_programs', '0001_initial'),
        ('courses', '0002_auto_20190830_0814'),
        ('learning', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='StudentAssignment|student'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='courses',
            field=models.ManyToManyField(through='learning.CourseInvitation', to='courses.Course', verbose_name='Courses'),
        ),
        migrations.AddField(
            model_name='graduateprofile',
            name='academic_disciplines',
            field=models.ManyToManyField(blank=True, to='study_programs.AcademicDiscipline', verbose_name='Fields of study'),
        ),
        migrations.AddField(
            model_name='graduateprofile',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graduate_profile', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='event',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Location', verbose_name='CourseClass|Venue'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Course offering'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='learning.Invitation', verbose_name='Invitation'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='coursenewsnotification',
            name='course_offering_news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseNews', verbose_name='Course offering news'),
        ),
        migrations.AddField(
            model_name='coursenewsnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='courseinvitation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Course offering'),
        ),
        migrations.AddField(
            model_name='courseinvitation',
            name='invitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.Invitation', verbose_name='Course Invitation'),
        ),
        migrations.AddField(
            model_name='assignmentnotification',
            name='student_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.StudentAssignment', verbose_name='student_assignment'),
        ),
        migrations.AddField(
            model_name='assignmentnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='assignmentcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='assignmentcomment',
            name='student_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.StudentAssignment', verbose_name='AssignmentComment|student_assignment'),
        ),
        migrations.AlterUniqueTogether(
            name='studentassignment',
            unique_together={('assignment', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
        migrations.AddConstraint(
            model_name='courseinvitation',
            constraint=models.UniqueConstraint(fields=('invitation', 'course'), name='unique_invitation_course'),
        ),
    ]
