# Generated by Django 2.1.5 on 2019-01-21 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190109_1344'),
        ('learning', '0002_auto_20190109_1344'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NonCourseEvent',
            new_name='Event',
        ),
    ]
