# Generated by Django 2.2.6 on 2019-10-16 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190830_0814'),
        ('learning', '0002_auto_20190830_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='semester',
            field=models.ForeignKey(default=35, on_delete=django.db.models.deletion.CASCADE, to='courses.Semester', verbose_name='Semester'),
            preserve_default=False,
        ),
    ]
