# Generated by Django 2.1.5 on 2019-03-14 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180730_1437'),
        ('learning', '0003_auto_20190121_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Branch|Name')),
                ('is_remote', models.BooleanField(default=False, verbose_name='Distance Branch')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('timezone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.City', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
    ]
