# Generated by Django 2.2.6 on 2019-10-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_invitation_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentcomment',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
    ]
