# Generated by Django 2.1.5 on 2019-03-14 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='timezone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.City', verbose_name='Timezone'),
        ),
    ]
