# Generated by Django 2.2.9 on 2020-01-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_assignmentcomment_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='execution_time',
            field=models.TimeField(blank=True, help_text='The time spent by the student executing this task', null=True, verbose_name='Execution Time'),
        ),
    ]
