# Generated by Django 2.2.9 on 2020-01-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_studentassignment_execution_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='execution_time',
            field=models.DurationField(blank=True, help_text='The time spent by the student executing this task', null=True, verbose_name='Execution Time'),
        ),
    ]
