# Generated by Django 2.1.7 on 2019-03-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_auto_20190314_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(choices=[('spb', 'Saint Petersburg'), ('nsk', 'Novosibirsk'), ('distance', 'Branches|Distance')], max_length=8, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='description',
            field=models.TextField(blank=True, help_text='Branch|Description', verbose_name='Description'),
        ),
    ]
