# Generated by Django 2.1.7 on 2019-03-29 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_auto_20190328_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='timezone',
        ),
    ]
