# Generated by Django 2.2.10 on 2020-02-07 13:40
import core.db.fields
import core.db.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200207_1340'),
        ('courses', '0007_auto_20200207_1114'),
        ('learning', '0006_auto_20200131_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('type', models.CharField(choices=[('manual', 'Manual'), ('branch', 'Branch')], default='branch', max_length=100, verbose_name='Type')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('meta', core.db.fields.PrettyJSONField(blank=True, null=True, verbose_name='Meta')),
                ('enrollment_key', models.CharField(max_length=128, verbose_name='Enrollment key')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Branch', verbose_name='Branch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Course offering')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
