# Generated by Django 2.2.10 on 2020-02-11 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20200207_1114'),
        ('learning', '0007_studentgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentgroup',
            options={'verbose_name': 'Student Group', 'verbose_name_plural': 'Student Groups'},
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='courses.Course', verbose_name='Course offering'),
        ),
        migrations.CreateModel(
            name='AssignmentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Assignment', verbose_name='Assignment')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.StudentGroup', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Assignment Group',
                'verbose_name_plural': 'Assignment Groups',
            },
        ),
        migrations.AddConstraint(
            model_name='assignmentgroup',
            constraint=models.UniqueConstraint(fields=('assignment', 'group'), name='unique_assignment_group'),
        ),
    ]
