# Generated by Django 2.2 on 2019-04-26 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_remove_branch_timezone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ('student', 'course'), 'verbose_name': 'Enrollment', 'verbose_name_plural': 'Enrollments'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-date', '-starts_at', 'name'), 'verbose_name': 'Non-course event', 'verbose_name_plural': 'Non-course events'},
        ),
    ]
