# Generated by Django 2.2.1 on 2019-05-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_auto_20190426_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(choices=[('spb', 'Saint Petersburg'), ('nsk', 'Novosibirsk'), ('distance', 'Branches|Distance')], max_length=8, unique=True, verbose_name='Code'),
        ),
    ]
