# Generated by Django 2.2.10 on 2020-02-13 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_auto_20200211_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='student_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='learning.StudentGroup', verbose_name='Student Group'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='type',
            field=models.CharField(choices=[('no_groups', 'Without Groups'), ('manual', 'Manual'), ('branch', 'Branch')], default='branch', max_length=100, verbose_name='Type'),
        ),
    ]
