# Generated by Django 2.2.1 on 2019-06-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_graduateprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduateprofile',
            name='graduation_year',
            field=models.PositiveSmallIntegerField(default=2019, editable=False, help_text='Helps filtering by year', verbose_name='Graduation Year'),
            preserve_default=False,
        ),
    ]
