# Generated by Django 2.2.10 on 2020-02-19 13:25

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_studentassignment_deleted_at'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='assignmentcomment',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='assignmentcomment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
