# Generated by Django 2.2.1 on 2019-06-06 11:13

import core.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_graduateprofile_graduation_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduateprofile',
            name='details',
            field=core.db.models.PrettyJSONField(blank=True, default=dict, verbose_name='Details'),
            preserve_default=False,
        ),
    ]
