# Generated by Django 2.2.10 on 2020-03-16 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20200311_1305'),
        ('learning', '0011_auto_20200219_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentgroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='learning.StudentGroup', verbose_name='Group'),
        ),
        migrations.CreateModel(
            name='CourseClassGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseClass', verbose_name='Course Class')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.StudentGroup', verbose_name='Group')),
            ],
        ),
        migrations.AddConstraint(
            model_name='courseclassgroup',
            constraint=models.UniqueConstraint(fields=('course_class', 'group'), name='unique_class_student_group'),
        ),
    ]
