# Generated by Django 2.2.10 on 2020-05-26 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_auto_20200316_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useful',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='old_useful_set', to='sites.Site', verbose_name='Site'),
        ),
    ]
