# Generated by Django 2.2.1 on 2019-06-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_graduateprofile_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduateprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activity'),
        ),
    ]
