# Generated by Django 2.2.10 on 2020-05-22 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_enrollment_student_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.StudentProfile', verbose_name='Student Profile'),
        ),
    ]
