# Generated by Django 2.2.1 on 2019-06-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_programs', '0006_auto_20190318_0919'),
        ('learning', '0014_auto_20190610_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduateprofile',
            name='academic_disciplines',
            field=models.ManyToManyField(blank=True, to='study_programs.AcademicDiscipline', verbose_name='Fields of study'),
        ),
    ]
