# Generated by Django 2.2.10 on 2020-05-25 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200525_1652'),
        ('learning', '0014_auto_20200522_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduateprofile',
            name='student_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graduate_profile', to='users.StudentProfile', verbose_name='Student Profile'),
        ),
    ]
