# Generated by Django 2.2.1 on 2019-06-18 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0015_graduateprofile_academic_disciplines'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graduateprofile',
            old_name='graduation_at',
            new_name='graduated_on',
        ),
    ]
