# Generated by Django 2.2.10 on 2020-05-26 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0015_graduateprofile_student_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduateprofile',
            name='student',
        ),
        migrations.AlterField(
            model_name='graduateprofile',
            name='academic_disciplines',
            field=models.ManyToManyField(blank=True, help_text='Academic disciplines that the student graduated from', to='study_programs.AcademicDiscipline', verbose_name='Fields of study'),
        ),
        migrations.AlterField(
            model_name='graduateprofile',
            name='student_profile',
            field=models.OneToOneField(default=6230, on_delete=django.db.models.deletion.CASCADE, related_name='graduate_profile', to='users.StudentProfile', verbose_name='Student Profile'),
            preserve_default=False,
        ),
    ]
