# Generated by Django 2.2.3 on 2019-07-12 09:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20190701_1242'),
        ('learning', '0016_auto_20190618_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128, verbose_name='Token')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Course offering')),
            ],
            options={
                'verbose_name': 'Enrollment Invitation',
                'verbose_name_plural': 'Enrollment Invitations',
            },
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Enrollment', 'verbose_name_plural': 'Enrollments'},
        ),
        migrations.AlterField(
            model_name='graduateprofile',
            name='graduated_on',
            field=models.DateField(help_text='Graduation ceremony date', verbose_name='Graduated on'),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('expire_at', models.DateTimeField(blank=True, help_text='Leave blank to use course enrollment deadline from semester settings', null=True, verbose_name='Expire at')),
                ('token', models.CharField(max_length=128, verbose_name='Token')),
                ('courses', models.ManyToManyField(through='learning.EnrollmentInvitation', to='courses.Course', verbose_name='Courses')),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
            },
        ),
        migrations.AddField(
            model_name='enrollmentinvitation',
            name='invitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.Invitation', verbose_name='Course Invitation'),
        ),
        migrations.AddConstraint(
            model_name='enrollmentinvitation',
            constraint=models.UniqueConstraint(fields=('invitation', 'course'), name='unique_invitation_course'),
        ),
    ]
