# Generated by Django 2.2.10 on 2020-06-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0016_auto_20200526_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduateprofile',
            name='diploma_issued_on',
            field=models.DateField(blank=True, null=True, verbose_name='Diploma Issued on'),
        ),
        migrations.AddField(
            model_name='graduateprofile',
            name='diploma_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='Diploma Number'),
        ),
        migrations.AddField(
            model_name='graduateprofile',
            name='diploma_registration_number',
            field=models.CharField(blank=True, help_text='Registration number in the registry of education', max_length=255, verbose_name='Registration Number'),
        ),
    ]
