# Generated by Django 2.2.10 on 2020-06-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0017_auto_20200604_1639'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Useful',
        ),
    ]
