# Generated by Django 2.2.3 on 2019-07-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0017_auto_20190712_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='expire_at',
        ),
        migrations.AddField(
            model_name='enrollmentinvitation',
            name='expire_at',
            field=models.DateTimeField(blank=True, help_text='Leave blank to use course enrollment deadline from semester settings', null=True, verbose_name='Expire at'),
        ),
    ]
