# Generated by Django 2.2.3 on 2019-07-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0018_auto_20190712_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmentinvitation',
            name='expire_at',
        ),
    ]
