# Generated by Django 2.2.13 on 2020-06-25 05:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20200424_1618'),
        ('sites', '0002_alter_domain_unique'),
        ('learning', '0018_delete_useful'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('starts_on', models.DateField(blank=True, help_text='Leave blank to fill in with the date of the beginning of the term', null=True, verbose_name='Starts on')),
                ('ends_on', models.DateField(blank=True, help_text='Inclusive. Leave blank to calculate based on a default duration (45 days)', null=True, verbose_name='Deadline')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Semester', verbose_name='Semester')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Enrollment Period',
                'verbose_name_plural': 'Enrollment Periods',
            },
        ),
        migrations.AddConstraint(
            model_name='enrollmentperiod',
            constraint=models.UniqueConstraint(fields=('semester', 'site'), name='unique_enrollment_period_per_semester_per_site'),
        ),
    ]
