# Generated by Django 2.2.13 on 2020-06-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0019_auto_20200625_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentperiod',
            name='ends_on',
            field=models.DateField(blank=True, help_text='Включительно. Оставьте пустым, чтобы вычислить дедлайн записи на курсы на основе стандартной длительности периода (45 дн.)', null=True, verbose_name='Closing Day'),
        ),
    ]
