# Generated by Django 2.2.3 on 2019-07-30 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20190723_1208'),
        ('learning', '0020_enrollment_invitation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnrollmentInvitation',
            new_name='CourseInvitation',
        ),
    ]
