# Generated by Django 3.0.9 on 2020-08-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0021_auto_20200818_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentassignment',
            options={'ordering': ['assignment', 'student'], 'verbose_name': 'Personal Assignment', 'verbose_name_plural': 'Personal Assignments'},
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='grade',
            field=models.CharField(choices=[('not_graded', 'Not graded'), ('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5'), ('six', '6'), ('seven', '7'), ('eight', '8'), ('nine', '9'), ('ten', '10'), ('unsatisfactory', 'Enrollment|Unsatisfactory'), ('pass', 'Enrollment|Pass'), ('good', 'Good'), ('excellent', 'Excellent')], default='not_graded', max_length=100, verbose_name='Enrollment|grade'),
        ),
    ]
