# Generated by Django 3.0.9 on 2020-09-02 08:19

from django.db import migrations
import files.models
import learning.models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0022_auto_20200827_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentcomment',
            name='attached_file',
            field=files.models.ConfigurableStorageFileField(blank=True, max_length=200, upload_to=learning.models.assignment_comment_attachment_upload_to),
        ),
    ]
