# Generated by Django 2.2.4 on 2019-08-13 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0022_invitation_branch'),
        ('admission', '0027_auto_20190813_1132'),
        ('users', '0016_auto_20190727_1814'),
        ('study_programs', '0010_auto_20190727_1739'),
        ('library', '0005_auto_20190812_1556'),
        ('projects', '0015_auto_20190727_1750'),
    ]

    database_operations = [
        migrations.AlterModelTable('branch', 'core_branch'),
    ]

    state_operations = [
        # migrations.DeleteModel(
        #     name='Branch',
        # ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]