# Generated by Django 3.0.9 on 2020-09-02 09:15

from django.db import migrations
import learning.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0023_auto_20200902_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduateprofile',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(blank=True, max_length=200, upload_to=learning.models.graduate_photo_upload_to, verbose_name='Photo'),
        ),
    ]
