# Generated by Django 2.2.4 on 2019-08-13 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        #('study_programs', '0011_auto_20190813_1738'),
        #('admission', '0028_auto_20190813_1738'),
        ('learning', '0023_auto_20190813_1727'),
        ('core', '0006_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Branch', to_field='code', verbose_name='Branch'),
        ),
    ]
