# Generated by Django 3.0.9 on 2020-09-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0024_auto_20200902_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentcomment',
            name='type',
            field=models.CharField(choices=[('comment', 'Comment'), ('solution', 'Solution')], default='comment', max_length=42, verbose_name='AssignmentComment|Type'),
            preserve_default=False,
        ),
    ]
