# Generated by Django 2.2.4 on 2019-08-13 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0024_auto_20190813_1738'),
        ('projects', '0016_auto_20190813_1738'),
        ('library', '0006_auto_20190813_1738'),
        ('study_programs', '0011_auto_20190813_1738'),
        ('users', '0017_auto_20190813_1738'),
        ('admission', '0028_auto_20190813_1738'),
    ]

    state_operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
    ]

    operations = [
        # After this state operation, the Django DB state should match the
        # actual database structure.
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]