# Generated by Django 3.0.9 on 2020-09-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0025_assignmentcomment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentcomment',
            name='execution_time',
            field=models.DurationField(blank=True, help_text='The time spent by the student executing this submission', null=True, verbose_name='Solution Execution Time'),
        ),
    ]
