# Generated by Django 3.0.9 on 2020-09-15 18:33

from django.db import migrations, models
import django.db.models.deletion
import files.models
import learning.models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_submission'),
        ('learning', '0026_assignmentcomment_execution_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentcomment',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.Submission'),
        ),
        migrations.AlterField(
            model_name='assignmentcomment',
            name='attached_file',
            field=files.models.ConfigurableStorageFileField(blank=True, max_length=200, upload_to=learning.models.assignment_comment_attachment_upload_to, verbose_name='Attached File'),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='execution_time',
            field=models.DurationField(blank=True, editable=False, help_text='The time spent by the student executing this task', null=True, verbose_name='Execution Time'),
        ),
    ]
