# Generated by Django 3.0.9 on 2020-09-22 08:49

from django.db import migrations, models
import files.models
import learning.models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0026_assignmentcomment_execution_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentcomment',
            name='attached_file',
            field=files.models.ConfigurableStorageFileField(blank=True, max_length=200, upload_to=learning.models.assignment_comment_attachment_upload_to, verbose_name='Attached File'),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='execution_time',
            field=models.DurationField(blank=True, editable=False, help_text='The time spent by the student executing this task', null=True, verbose_name='Execution Time'),
        ),
    ]
