# Generated by Django 3.0.9 on 2020-09-16 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0027_auto_20200915_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentcomment',
            name='submission',
        ),
    ]
