# Generated by Django 3.0.9 on 2020-10-03 14:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import files.models
import learning.models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0028_auto_20200929_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('attachment', files.models.ConfigurableStorageFileField(max_length=200, upload_to=learning.models.assignment_submission_attachment_upload_to)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.AssignmentComment', verbose_name='Assignment Submission')),
            ],
            options={
                'verbose_name': 'Assignment Submission Attachment',
                'verbose_name_plural': 'Assignment Submission Attachments',
            },
        ),
    ]
