# Generated by Django 3.0.9 on 2020-10-07 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0032_auto_20201007_0737'),
        ('learning', '0029_submissionattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.CourseTeacher', verbose_name='Assignee'),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('check', 'Check'), ('accept', 'Accepted'), ('rework', 'Rework')], default='new', max_length=10, verbose_name='StudentAssignment|Status'),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='trigger_auto_assign',
            field=models.BooleanField(default=True, editable=False, help_text='Try to set assignee on first student activity', null=True),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='watchers',
            field=models.ManyToManyField(related_name='_studentassignment_watchers_+', to=settings.AUTH_USER_MODEL, verbose_name='Student Assignment Watchers'),
        ),
        migrations.AlterField(
            model_name='studentgroupassignee',
            name='assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseTeacher', verbose_name='Assignee'),
        ),
        migrations.AlterField(
            model_name='submissionattachment',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='learning.AssignmentComment', verbose_name='Assignment Submission'),
        ),
    ]
