# Generated by Django 3.2.6 on 2021-08-16 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0030_auto_20201007_0737'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentgroupassignee',
            name='unique_assignee_per_student_or_assignment_group',
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='status',
            field=models.CharField(choices=[('new', 'AssignmentStatus|New'), ('check', 'AssignmentStatus|Check'), ('accept', 'AssignmentStatus|Accepted'), ('rework', 'AssignmentStatus|Rework')], default='new', max_length=10, verbose_name='StudentAssignment|Status'),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='_learning_studentassignment_watchers_+', to=settings.AUTH_USER_MODEL, verbose_name='Student Assignment Watchers'),
        ),
        migrations.AddConstraint(
            model_name='studentgroupassignee',
            constraint=models.UniqueConstraint(condition=models.Q(('assignment__isnull', True)), fields=('student_group', 'assignee'), name='unique_assignee_per_student_group'),
        ),
        migrations.AddConstraint(
            model_name='studentgroupassignee',
            constraint=models.UniqueConstraint(condition=models.Q(('assignment__isnull', False)), fields=('student_group', 'assignee', 'assignment'), name='unique_assignee_per_student_group_per_assignment'),
        ),
    ]
