# Generated by Django 2.2.4 on 2019-08-21 15:01

from django.db import migrations


def copy_venues(apps, schema_editor):
    Location = apps.get_model('core', 'Location')
    LearningSpace = apps.get_model('learning', 'LearningSpace')
    CourseClass = apps.get_model('courses', 'CourseClass')
    for course_class in CourseClass.objects.select_related('course'):
        LearningSpace.objects.get_or_create(location_id=course_class.venue_id,
                                            branch_id=course_class.course.branch_id)


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0030_learningspace'),
    ]

    operations = [
        migrations.RunPython(copy_venues)
    ]
