# Generated by Django 3.2.7 on 2021-10-06 19:15

import core.db.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0031_auto_20210816_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='meta',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='graduateprofile',
            name='details',
            field=core.db.fields.PrettyJSONField(blank=True, default=dict, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='graduateprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Visibility'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='enrollment_key',
            field=models.CharField(blank=True, max_length=128, verbose_name='Enrollment key'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='type',
            field=models.CharField(choices=[('system', 'System'), ('manual', 'Manual'), ('branch', 'Branch')], default='branch', max_length=100, verbose_name='Group Type'),
        ),
        migrations.AlterField(
            model_name='studentgroupassignee',
            name='student_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_group_assignees', to='learning.studentgroup', verbose_name='Student Group'),
        ),
    ]
