# Generated by Django 2.2.4 on 2019-08-22 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0032_auto_20190821_1528'),
    ]

    database_operations = [
        migrations.AlterModelTable('learningspace', 'courses_learningspace'),
    ]

    state_operations = [
        # migrations.DeleteModel(
        #     name='Branch',
        # ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
