# Generated by Django 3.2.7 on 2021-10-08 18:55

from django.db import migrations, models
import rest_framework.utils.encoders


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0032_auto_20211006_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='meta',
            field=models.JSONField(blank=True, editable=False, encoder=rest_framework.utils.encoders.JSONEncoder, null=True),
        ),
    ]
