# Generated by Django 3.2.7 on 2021-10-26 10:09

import core.db.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0033_alter_studentassignment_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentScoreAuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('score_old', core.db.fields.ScoreField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Previous Score')),
                ('score_new', core.db.fields.ScoreField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='New Score')),
                ('source', models.CharField(choices=[('api', 'Api'), ('api-ya.contest', 'Api Yandex Contest'), ('csv-ya.login', 'Csv Yandex Login'), ('csv-stepik', 'Csv Stepik'), ('csv-enrollment', 'Csv Enrollment'), ('admin', 'Form Admin'), ('form', 'Form Assignment'), ('gradebook', 'Form Gradebook'), ('webhook-gerrit', 'Webhook Gerrit')], max_length=15)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Changed by')),
                ('student_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_history', to='learning.studentassignment', verbose_name='Student Assignment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
