# Generated by Django 2.2.4 on 2019-08-22 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0033_auto_20190822_1523'),
        ('courses', '0020_learningspace'),
    ]

    database_operations = [
    ]

    state_operations = [
        migrations.DeleteModel(
            name='LearningSpace',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
