# Generated by Django 2.2.4 on 2019-08-23 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20190821_1541'),
        ('learning', '0034_auto_20190822_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Branch', verbose_name='Branch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Location', verbose_name='CourseClass|Venue'),
        ),
    ]
