# Generated by Django 3.2.9 on 2022-01-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0034_assignmentscoreauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='status',
            field=models.CharField(choices=[('new', 'AssignmentStatus|New'), ('not_submitted', 'AssignmentStatus|Not submitted'), ('on_checking', 'AssignmentStatus|On checking'), ('need_fixes', 'AssignmentStatus|Need fixes'), ('completed', 'AssignmentStatus|Completed')], default='not_submitted', max_length=13, verbose_name='StudentAssignment|Status'),
        ),
    ]
