# Generated by Django 3.2.9 on 2021-12-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0034_assignmentscoreauditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentscoreauditlog',
            options={'verbose_name_plural': 'Assignment score audit log'},
        ),
        migrations.AlterField(
            model_name='assignmentscoreauditlog',
            name='source',
            field=models.CharField(choices=[('api', 'Api'), ('api-ya.contest', 'Api Yandex Contest'), ('csv-ya.login', 'Csv Yandex Login'), ('csv-stepik', 'Csv Stepik'), ('csv-enrollment', 'Csv Enrollment'), ('admin', 'Form Admin'), ('form', 'Form Assignment'), ('gradebook', 'Form Gradebook'), ('webhook-gerrit', 'Webhook Gerrit')], max_length=15, verbose_name='Source'),
        ),
    ]
