# Generated by Django 3.2.9 on 2022-01-27 11:33

import core.db.fields
from django.db import migrations, models
import rest_framework.utils.encoders


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0034_assignmentscoreauditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentscoreauditlog',
            options={'verbose_name_plural': 'Assignment score audit log'},
        ),
        migrations.AddField(
            model_name='assignmentcomment',
            name='meta',
            field=models.JSONField(blank=True, editable=False, encoder=rest_framework.utils.encoders.JSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='penalty',
            field=core.db.fields.ScoreField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Penalty'),
        ),
        migrations.AlterField(
            model_name='assignmentscoreauditlog',
            name='source',
            field=models.CharField(choices=[('api', 'REST API'), ('api-ya.contest', 'Yandex.Contest'), ('csv-ya.login', 'Imported from CSV by Yandex.Login'), ('csv-stepik', 'Imported from CSV by stepik.org ID'), ('csv-enrollment', 'Imported from CSV by LMS Student ID'), ('admin', 'Admin Panel'), ('form', 'Form on Assignment Detail Page'), ('gradebook', 'Gradebook'), ('webhook-gerrit', 'Gerrit Webhook')], max_length=15, verbose_name='Source'),
        ),
    ]
