# Generated by Django 3.2.9 on 2022-01-27 14:30

import core.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0035_auto_20220127_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='last_comment_from',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='The author type of the latest comment'),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='penalty',
            field=core.db.fields.ScoreField(blank=True, decimal_places=2, editable=False, max_digits=6, null=True, verbose_name='Penalty'),
        ),
    ]
