# Generated by Django 3.2.12 on 2022-02-15 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0037_alter_studentassignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='learning.invitation', verbose_name='Invitation'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='type',
            field=models.CharField(choices=[('system', 'System'), ('manual', 'Manual'), ('branch', 'Branch'), ('invite', 'Invitation')], default='branch', max_length=100, verbose_name='Group Type'),
        ),
    ]
