# Generated by Django 3.2.12 on 2022-02-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0038_auto_20220215_0715'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(fields=('semester', 'name'), name='unique_name_per_semester'),
        ),
    ]
