# Generated by Django 3.2.13 on 2022-08-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0039_invitation_unique_name_per_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='grade',
            field=models.CharField(choices=[('not_graded', 'Not graded'), ('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5'), ('six', '6'), ('seven', '7'), ('eight', '8'), ('nine', '9'), ('ten', '10'), ('unsatisfactory', 'Enrollment|Unsatisfactory'), ('pass', 'Enrollment|Pass'), ('good', 'Good'), ('excellent', 'Excellent'), ('re-credit', 'Enrollment|Re-credit')], default='not_graded', max_length=100, verbose_name='Enrollment|grade'),
        )
    ]
