# Generated by Django 3.2.13 on 2022-10-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_add_telegram_username'),
        ('learning', '0040_new_grade_re-credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, help_text='Students who took advantage of the invitation', related_name='invitations', to='users.StudentProfile', verbose_name='Enrolled students'),
        ),
    ]
