# Generated by Django 3.2.13 on 2022-11-15 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0041_invitation_student_profile_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentGradeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('grade_changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Entry Added')),
                ('grade', models.CharField(choices=[('not_graded', 'Not graded'), ('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5'), ('six', '6'), ('seven', '7'), ('eight', '8'), ('nine', '9'), ('ten', '10'), ('unsatisfactory', 'Enrollment|Unsatisfactory'), ('pass', 'Enrollment|Pass'), ('good', 'Good'), ('excellent', 'Excellent'), ('re-credit', 'Enrollment|Re-credit')], max_length=100, verbose_name='Enrollment|grade')),
                ('source', models.CharField(choices=[('gradebook', 'Gradebook'), ('csv-ya.login', 'Imported from CSV by Yandex.Login'), ('csv-stepik', 'Imported from CSV by stepik.org ID'), ('csv-enrollment', 'Imported from CSV by LMS Student ID'), ('admin', 'Admin Panel')], max_length=15, verbose_name='Source')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_history', to='learning.enrollment', verbose_name='Enrollment')),
                ('entry_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name_plural': 'Лог изменения оценки',
            },
        ),
    ]
