# Generated by Django 3.2.18 on 2024-02-27 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0043_studentgroupteacherbucket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentassignment',
            name='first_student_comment_at',
        ),
        migrations.RemoveField(
            model_name='studentassignment',
            name='last_comment_from',
        ),
        migrations.RemoveField(
            model_name='studentgroup',
            name='meta',
        ),
    ]
