# Generated by Django 3.2.18 on 2024-07-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_siteconfiguration_managers'),
        ('learning', '0045_auto_20240428_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='branches',
            field=models.ManyToManyField(related_name='_learning_invitation_branches_+', to='core.Branch', verbose_name='Branches'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='category',
            field=models.CharField(blank=True, choices=[('university', 'Invitation|University'), ('staff', 'Invitation|Staff'), ('teacher', 'Invitation|Teacher'), ('guest', 'Invitation|Guest'), ('academic', 'Invitation|Aacdemic'), ('graduate', 'Invitation|Graduate'), ('applicant', 'Invitation|Applicant')], max_length=15, null=True, verbose_name='Category'),
        ),
    ]
