# Generated by Django 3.2.18 on 2024-08-01 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0047_auto_20240729_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='branch',
        ),
    ]
