# Generated by Django 3.2.18 on 2024-08-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_user_gave_permission_at'),
        ('learning', '0048_remove_invitation_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinvitation',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 - unlimited', verbose_name='CourseOffering|capacity'),
        ),
        migrations.AddField(
            model_name='courseinvitation',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, help_text='Students who took advantage of the invitation', to='users.StudentProfile', verbose_name='Enrolled students'),
        ),
    ]
