# Generated by Django 3.2.18 on 2024-08-02 19:37

from django.db import migrations


def migrate_enrolled_students(apps, schema_editor):
    Invitation = apps.get_model('learning', 'Invitation')

    for invitation in Invitation.objects.all():
        course_invitation = invitation.courseinvitation_set.first()
        if course_invitation:
            for student in invitation.enrolled_students.all():
                course_invitation.enrolled_students.add(student)

class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0049_auto_20240802_1703'),
    ]

    operations = [
        migrations.RunPython(migrate_enrolled_students)
    ]
