# Generated by Django 3.2.18 on 2024-08-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_user_gave_permission_at'),
        ('learning', '0050_auto_20240802_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='enrolled_students',
        ),
        migrations.AlterField(
            model_name='courseinvitation',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, help_text='Students who took advantage of the invitation', related_name='course_invitations', to='users.StudentProfile', verbose_name='Enrolled students'),
        ),
    ]
