# Generated by Django 3.2.18 on 2024-09-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0052_auto_20240821_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinvitation',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 - unlimited', verbose_name='CourseInvitation|capacity'),
        ),
    ]
