# Generated by Django 3.2.18 on 2024-10-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0053_alter_courseinvitation_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_grade_recredited',
            field=models.BooleanField(default=False, verbose_name='Grade re-credited'),
        ),
    ]
