# Generated by Django 3.2.18 on 2025-01-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0055_alter_enrollment_is_grade_recredited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentgradelog',
            name='source',
            field=models.CharField(choices=[('gradebook', 'Gradebook'), ('csv-ya.login', 'Imported from CSV by Yandex.Login'), ('csv-stepik', 'Imported from CSV by stepik.org ID'), ('csv-enrollment', 'Imported from CSV by LMS Student ID'), ('admin', 'Admin Panel'), ('admin-on-type', 'Auto change on type change with admin panel')], max_length=15, verbose_name='Source'),
        ),
    ]
