# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-05 12:10
from __future__ import unicode_literals

from django.db import migrations
from notifications import types as notification_types


def update_forward(apps, schema_editor):
    cls = apps.get_model('notifications', 'Type')
    for t in notification_types:
        cls.objects.update_or_create(
            code=t.name
        )


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20161005_1454'),
    ]

    operations = [
        migrations.RunPython(update_forward),
    ]
