# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-26 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20161006_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Check if you want to save\n        related notifications in DB, but show,\n        that you are not using this notification type anymore.'),
        ),
    ]
