---
- name: add postgres repo key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: add PPAs for latest and greatest software
  apt_repository:
    repo: "{{ item }}"
    update_cache: yes
  with_items:
    - 'ppa:nginx/stable'
    - 'deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main'
    - 'ppa:fkrull/deadsnakes'

- name: Upgrade all packages to the latest version
  apt: upgrade=dist

- name: check if a reboot is required
  stat: path=/var/run/reboot-required get_md5=no
  register: reboot_file

- name: reboot the server
  command: /sbin/reboot removes=/var/run/reboot-required
  when: reboot_file.stat.exists == true

- name: wait for server to go offline (because reboot)
  sudo: no
  local_action: wait_for host="{{ inventory_hostname }}" port=22 state=stopped
  when: reboot_file.stat.exists == true

- name: wait for server to come back online
  sudo: no
  local_action: wait_for host="{{ inventory_hostname }}" port=22
  when: reboot_file.stat.exists == true

- name: set default locale LANG to UTF-8
  lineinfile: dest=/etc/default/locale line='LANG="en_US.utf8"' regexp='^LANG=' state=present insertafter=BOF

- name: set default locale LC_ALL to UTF-8
  lineinfile: dest=/etc/environment line='LC_ALL="en_US.utf8"' regexp='^LC_ALL=' state=present insertafter=BOF

- name: install stuff
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    # core items
    - nginx
    - postgresql-9.4
    - libpq-dev
    - gettext
    - libpcre3
    - libpcre3-dev
    - libxml2-dev
    - libxslt1-dev
    - python3.5
    - python-setuptools
    - python-dev
    - python3-dev
    - python3.5-dev
    - python3-pip
    - git
    - build-essential
    - libjpeg-dev
    - libpng-dev
    - libmagic-dev
    - libcurl4-gnutls-dev
    - python-pycurl
    # utilities
    - zsh
    - tmux
    - htop