---
- name: add postgres repo key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: add PPAs for latest and greatest software
  apt_repository:
    repo: "{{ item }}"
    update_cache: yes
  with_items:
    - 'ppa:nginx/stable'
    - 'deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main'

- name: Upgrade all packages to the latest version
  apt: upgrade=dist

- name: check if a reboot is required
  stat: path=/var/run/reboot-required get_md5=no
  register: reboot_file

- name: reboot the server
  command: /sbin/reboot removes=/var/run/reboot-required
  when: reboot_file.stat.exists == true

- name: wait for server to go offline (because reboot)
  local_action: wait_for host="{{ inventory_hostname }}" port=22 state=stopped
  when: reboot_file.stat.exists == true

- name: set default locale LANG to UTF-8
  lineinfile: dest=/etc/default/locale line='LANG="en_US.utf8"' regexp='^LANG=' state=present insertafter=BOF

- name: set default locale LC_ALL to UTF-8
  lineinfile: dest=/etc/environment line='LC_ALL="en_US.utf8"' regexp='^LC_ALL=' state=present insertafter=BOF

- name: install stuff
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    # stuff for system python
    - python-setuptools
    - python-dev
    # core items
    - nginx
    # db
    - libpq-dev
    - postgresql-9.4
    - git
    # utilities
    - zsh
    - tmux
    - htop
    # others
    - build-essential
