---
- name: Download and install certbot
  get_url: url=https://dl.eff.org/certbot-auto dest={{ certbot_script }} mode=0755

- name: LetsEncrypt Certbot directory exists
  file:
    path: "{{ repo_root }}/.well-known/acme-challenge"
    state: directory
    recurse: yes
    owner: "{{ site_user }}"
    group: "{{ site_user }}"
  tags:
    - certbot
    - tls

- debug: msg="{{ enable_https }}"

- meta: flush_handlers

- name: Generate certificate
  command: >
    {{ certbot_script }} certonly --webroot
    --noninteractive --agree-tos
    --email {{ admin_email }}
    -w {{ repo_root }}
    -d {{ certbot_domains|join(' -d ') }}
  tags:
    - certbot
    - tls
  args:
    creates: "{{ certbot_config_dir }}"

# Note: the `.` special character matches any character except newlines.
- name: Uncomment `ssl_certificate` and `ssl_certificate_key` directives
  replace:
    dest: "/etc/nginx/sites-available/{{ nginx_domain }}.conf"
    regexp: '^(\s*)# ssl_certificate(.*);$'
    replace: '\1ssl_certificate\2;'
    backup: no
  notify: reload_nginx
  loop: "{{ nginx_configs }}"
  loop_control:
    loop_var: nginx_domain
  tags:
    - certbot
    - tls
    - nginx

- meta: flush_handlers

- name: Ensure a cron job to auto-renew the certificate exists
  cron:
    name: "daily auto renew cert for {{ main_domain }}"
    special_time: daily
    job: >
      {{ certbot_script }} certonly --webroot
      --noninteractive --agree-tos --quiet
      --email {{ admin_email }}
      -w {{ repo_root }}
      -d {{ certbot_domains|join(' -d ') }}
      --deploy-hook 'service nginx reload'
      --no-self-upgrade
    state: present
  when: certbot_auto_renew
  tags:
    - certbot
    - tls