---
- name: daily late-night backup goes in cron
  become_user: "{{ item }}"
  cron:
    name: backup CSC website to S3
    user: "{{ item }}"
    hour: "4"
    minute: "0"
    job: >
      . /home/{{ item }}/site/env/bin/activate &&
      /home/{{ item }}/site/repo/manage.py dbbackup
      --settings={{item}}.settings.{{ app_environment }}
      --pythonpath='/home/{{item}}/site/repo/cscsite'
      >> /home/{{ item }}/site/logs/cscbackup.log
      2>&1
  with_items:
    - "{{ cscenter_user }}"

- name: notify people every 5 minutes (cronjob)
  become_user: "{{ item }}"
  cron:
    name: CSC mail notifier
    user: "{{ item }}"
    minute: "*/5"
    job: >
      . /home/{{ item }}/site/env/bin/activate &&
      /home/{{ item }}/site/repo/manage.py notify
      --settings={{ item }}.settings.{{ app_environment }}
      --pythonpath='/home/{{item}}/site/repo/cscsite'
      >> /home/{{ item }}/site/logs/cscnotifier.log
      2>&1
  with_items:
    - "{{ cscenter_user }}"

- name: remove useless notifications each week (cronjob)
  become_user: "{{ item }}"
  cron:
    name: CSC notification cleanup
    user: "{{ item }}"
    special_time: weekly
    job: >
      . /home/{{ item }}/site/env/bin/activate &&
      /home/{{ item }}/site/repo/manage.py notification_cleanup
      --settings={{ item }}.settings.{{ app_environment }}
      --pythonpath='/home/{{item}}/site/repo/cscsite'
      >> /home/{{ item }}/site/logs/cscnotifier.log
  with_items:
    - "{{ cscenter_user }}"

- name: Project deadlines notification
  become_user: "{{ item }}"
  cron:
    name: Send project notification about deadline if neccessary
    user: "{{ item }}"
    hour: "1,13"
    minute: "0"
    job: >
      . /home/{{ item }}/site/env/bin/activate &&
      /home/{{ item }}/site/repo/manage.py projects_notifications
      --settings={{ item }}.settings.{{ app_environment }}
      --pythonpath='/home/{{item}}/site/repo/cscsite'
      >> /home/{{ item }}/site/logs/cscnotifier.log
  with_items:
    - "{{ cscenter_user }}"

- name: Once a day remove expired sessions
  become_user: "{{ item }}"
  cron:
    name: Remove expired CSC sessions
    user: "{{ item }}"
    special_time: daily
    job: >
      . /home/{{ item }}/site/env/bin/activate &&
      /home/{{ item }}/site/repo/manage.py clearsessions
      --settings={{ item }}.settings.{{ app_environment }}
      --pythonpath='/home/{{item}}/site/repo/cscsite'
      >> /home/{{ item }}/site/logs/cscnotifier.log
  with_items:
    - "{{ cscenter_user }}"
