---
- name: daily late-night backup goes in cron
  sudo_user: "{{ item }}"
  cron:
    name: backup CSC website to S3
    user: "{{ item }}"
    hour: "4"
    minute: "0"
    job: >
      . /home/{{ item }}/site/env/bin/activate &&
      /home/{{ item }}/site/repo/manage.py cscbackup
      --settings={{item}}.settings.production
      --pythonpath='/home/{{item}}/site/repo/cscsite'
      >> /home/{{ item }}/site/logs/cscbackup.log
      2>&1
  with_items:
    - "{{ cscenter_user }}"
    - "{{ csclub_user }}"

- name: notify people every 5 minutes (cronjob)
  sudo_user: "{{ item }}"
  cron:
    name: CSC mail notifier
    user: "{{ item }}"
    minute: "*/5"
    job: >
      . /home/{{ item }}/site/env/bin/activate &&
      /home/{{ item }}/site/repo/manage.py notify
      --settings={{ item }}.settings.production
      --pythonpath='/home/{{item}}/site/repo/cscsite'
      >> /home/{{ item }}/site/logs/cscnotifier.log
      2>&1
  with_items:
    - "{{ cscenter_user }}"

- name: remove useless notifications each week (cronjob)
  sudo_user: "{{ item }}"
  cron:
    name: CSC notification cleanup
    user: "{{ item }}"
    special_time: weekly
    job: >
      . /home/{{ item }}/site/env/bin/activate &&
      /home/{{ item }}/site/repo/manage.py notification_cleanup
      --settings={{ item }}.settings.production
      --pythonpath='/home/{{item}}/site/repo/cscsite'
      >> /home/{{ item }}/site/logs/cscnotifier.log
  with_items:
    - "{{ cscenter_user }}"

- name: Project deadlines notification
  sudo_user: "{{ item }}"
  cron:
    name: Send project notification about deadline if neccessary
    user: "{{ item }}"
    hour: "1,13"
    minute: "0"
    job: >
      . /home/{{ item }}/site/env/bin/activate &&
      /home/{{ item }}/site/repo/manage.py projects_notifications
      --settings={{ item }}.settings.production
      --pythonpath='/home/{{item}}/site/repo/cscsite'
      >> /home/{{ item }}/site/logs/cscnotifier.log
  with_items:
    - "{{ cscenter_user }}"

- name: Each night try to mark completed courses (set `is_completed` to True)
  sudo_user: "{{ item }}"
  cron:
    name: Mark center courses as completed from prev terms if necessary
    user: "{{ item }}"
    hour: "3"
    minute: "0"
    job: >
      . /home/{{ item }}/site/env/bin/activate &&
      /home/{{ item }}/site/repo/manage.py mark_completed_courses
      --settings={{ item }}.settings.production
      --pythonpath='/home/{{item}}/site/repo/cscsite'
      >> /home/{{ item }}/site/logs/cscnotifier.log
  with_items:
    - "{{ cscenter_user }}"

- name: Once a day remove expired sessions
  sudo_user: "{{ item }}"
  cron:
    name: Remove expired CSC sessions
    user: "{{ item }}"
    special_time: daily
    job: >
      . /home/{{ item }}/site/env/bin/activate &&
      /home/{{ item }}/site/repo/manage.py clearsessions
      --settings={{ item }}.settings.production
      --pythonpath='/home/{{item}}/site/repo/cscsite'
      >> /home/{{ item }}/site/logs/cscnotifier.log
  with_items:
    - "{{ cscenter_user }}"
