---
- name: create dir for nginx crypto stuff
  file: path=/etc/nginx/crypto state=directory

- name: ensure all nginx crypto material is present
  copy:
    src: "{{ item.from }}"
    dest: "/etc/nginx/crypto/{{ item.to }}"
    mode: 0400
  with_items:
    - from: cscweb_tls_intermediate_bundle.crt
      to: intermediate_bundle.crt
    - from: cscweb_tls_server_bundle.crt
      to: server_bundle.crt
    - from: cscweb_tls_server_decrypted_key.crt
      to: server_key.crt
    - from: cscweb_tls_dhparam.pem
      to: dhparam.pem

- name: copy nginx config
  template:
    src: "{{ item }}.conf.tmpl"
    dest: "/etc/nginx/sites-available/{{ item }}.conf"
  with_items:
    - "{{ cscenter_user }}"
    - "{{ csclub_user }}"

- name: remove default nginx config
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: reload nginx

- name: symlink nginx config
  file:
    src: "/etc/nginx/sites-available/{{ item }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ item }}.conf"
    state: link
  notify: restart nginx
  with_items:
    - "{{ cscenter_user }}"
    - "{{ csclub_user }}"