---
- name: install pip
  easy_install: name=pip

- name: install global Python 2 stuff
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
  with_items:
    - name: ipython
      version: "5.5.0"
    - name: virtualenv
      version: "15.1.0"
# Psycopg used by db.yml to make sure user exists
    - name: psycopg2
      version: "2.7.3.1"