---
# TODO: limit max memory for rqworker
# TODO: create `target` for rqworker?
- name: Create rq worker services
  template:
    src: rqworker.service.jinja2
    dest: "/etc/systemd/system/rqworker_{{ worker_name }}.service"
#    owner: "{{ site_user }}"
  loop: "{{ rq_workers }}"
  loop_control:
    loop_var: worker_name

- name: rq worker target for easier management via systemctl
  template:
    src: rqworker.target.jinja2
    dest: "/etc/systemd/system/rqworker_{{ site_user }}.target"

- name: Force systemd to reread configs and (re)start services
  systemd: daemon_reload=yes

