---
- name: Create group for /media folder
  group: name={{ site_user_group }} state=present

- name: Make sure group with {{ site_user }} exists regardless to the /etc/login.defs settings
  group: name={{ site_user }} state=present

- name: Create website user
  user:
    home: "/home/{{ site_user }}"
    name: "{{ site_user }}"
    state: present
    # Set primary group
    group: "{{ site_user_group }}"
    groups:
      - "{{ site_user }}"
      - "{{ site_user_group }}"
    append: yes

- name: Create .ssh directory
  file:
    path: "/home/{{ site_user }}/.ssh"
    state: directory
    owner: "{{ site_user }}"

- name: Ensure github.com is a known host
  lineinfile:
    dest: /{{ site_user }}/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"

- name: Ensure ssh key is present
  copy:
    content: "{{ deploy_ssh_key }}"
    dest: "/home/{{ site_user }}/.ssh/id_rsa"
    mode: 0400
    owner: "{{ site_user }}"

- name: Configure shell
  include_role:
    name: system
    tasks_from: zsh.yml
  vars:
    zsh_theme: sunaku
  with_items:
    - "{{ site_user }}"
  tags:
    - zsh
