---
# TODO: restart uwsgi, restart rqworkers (!)

- name: Check if python is installed
  package:
    name: "{{ python_pkg }}"
    state: present
  check_mode: true
  register: python_installed

# FIXME: Do I need this step here? Duplicated in `system` role
- name: Unlock python package for upgrade if it was hold before.
  dpkg_selections:
    name: "{{ python_pkg }}"
    selection: install
  when: not python_installed.changed

- name: Get stat about virtualenv directory
  stat:
    path: "/home/{{ site_user }}/site/env/"
  register: venv_dir

- name: Get virtualenv python version if venv already exists
  shell: "/home/{{ site_user }}/site/env/bin/python --version 2>&1"
  register: python_venv_version_installed
  when: venv_dir.stat.exists

- name: Get current python 3.x version
  shell: "{{ python_pkg }} --version 2>&1"
  register: python_version_installed

- name: Remove venv if version has changed
  file:
    path: "/home/{{ site_user }}/site/env/"
    state: absent
  when: venv_dir.stat.exists and python_venv_version_installed.stdout != python_version_installed.stdout

- name: Install website dependencies
  become: yes
  become_user: "{{ site_user }}"
  pip:
    requirements: "/home/{{ site_user }}/site/repo/requirements.txt"
    virtualenv: "/home/{{ site_user }}/site/env/"
    virtualenv_python: "{{ python_pkg }}"

- name: Prevent python from being upgraded with `apt-get upgrade` (it can broke venv)
  dpkg_selections:
    name: "{{ python_pkg }}"
    selection: hold