# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_extension', '0002_menuitemextension_open_in_new_window'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemextension',
            name='budge',
            field=models.CharField(blank=True, default='', help_text='Variable name for unred_notifications_cache', max_length=255),
        ),
        migrations.AlterField(
            model_name='menuitemextension',
            name='classes',
            field=models.CharField(blank=True, default='', help_text='Additional classes', max_length=255),
        ),
        migrations.AlterField(
            model_name='menuitemextension',
            name='exclude_patterns',
            field=models.TextField(blank=True, default=' ', help_text='Specify patterns when item is not selected. One pattern for each line.'),
        ),
        migrations.AlterField(
            model_name='menuitemextension',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Restrict visibility to selected groups.', related_name='menuitems_set', related_query_name='menuitem', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='menuitemextension',
            name='select_patterns',
            field=models.TextField(blank=True, default=' ', help_text='Specify patterns when item is selected. One pattern for each line.'),
        ),
    ]
