# Generated by Django 2.2.10 on 2020-03-04 13:00

import admission.models
import collections
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_auto_20200211_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='course',
            new_name='level_of_education',
        ),
        migrations.AlterField(
            model_name='contest',
            name='details',
            field=jsonfield.fields.JSONField(blank=True, load_kwargs={'object_pairs_hook': collections.OrderedDict}, validators=[admission.models.validate_json_container], verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='details',
            field=jsonfield.fields.JSONField(blank=True, load_kwargs={'object_pairs_hook': collections.OrderedDict}, null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='test',
            name='details',
            field=jsonfield.fields.JSONField(blank=True, load_kwargs={'object_pairs_hook': collections.OrderedDict}, verbose_name='Details'),
        ),
    ]
