# Generated by Django 2.2.10 on 2020-05-27 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0008_attachment_headers'),
        ('admission', '0007_auto_20200421_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online')], max_length=255, verbose_name='Format Name')),
                ('remind_before_start', models.DurationField(default='23:59:59', help_text='Helps to calculate schedule time of the reminder. Specify timedelta that will be subtracted from the interview start time.', verbose_name='Remind Before Start')),
                ('appointment_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='post_office.EmailTemplate', verbose_name='Invitation Template')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_formats', to='admission.Campaign', verbose_name='Campaign')),
                ('confirmation_template', models.ForeignKey(blank=True, help_text='Template for confirmation email that the interview was scheduled. Leave blank if there is no need to send confirmation email', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='post_office.EmailTemplate', verbose_name='Confirmation Template')),
                ('reminder_template', models.ForeignKey(help_text='Template for interview reminder email. Notification will be generated only on interview creation through slots mechanism.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='post_office.EmailTemplate', verbose_name='Reminder Template')),
            ],
            options={
                'verbose_name': 'Interview Format',
                'verbose_name_plural': 'Interview Formats',
            },
        ),
        migrations.AddConstraint(
            model_name='interviewformat',
            constraint=models.UniqueConstraint(fields=('campaign', 'format'), name='unique_format_per_campaign'),
        ),
    ]
