# Generated by Django 2.2.10 on 2020-05-27 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0008_auto_20200527_1708'),
    ]

    operations = [
    ]
