# Generated by Django 2.2.10 on 2020-05-27 17:09

from django.db import migrations


def create_interview_formats(apps, schema_editor):
    EmailTemplate = apps.get_model('post_office', 'EmailTemplate')
    Campaign = apps.get_model('admission', 'Campaign')
    InterviewFormat = apps.get_model('admission', 'InterviewFormat')
    for c in Campaign.objects.all():
        ta = EmailTemplate.objects.get(name=c.template_appointment or 'admission-interview-invitation')
        tir = EmailTemplate.objects.get(name=c.template_interview_reminder or 'admission-interview-reminder')
        InterviewFormat.objects.update_or_create(
            campaign=c, format='offline',
            defaults={
                "appointment_template": ta,
                "reminder_template": tir,
                "remind_before_start": '23:59:59'})


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0008_auto_20200527_1708'),
    ]

    operations = [
        migrations.RunPython(create_interview_formats),
    ]
