# Generated by Django 2.2.10 on 2020-05-28 12:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0011_remove_interviewformat_appointment_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='secret_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Secret code'),
        ),
    ]
