# Generated by Django 2.2.10 on 2020-05-28 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0012_interview_secret_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='template_interview_reminder',
        ),
    ]
