# Generated by Django 3.0.9 on 2020-08-18 22:11

import admission.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import files.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admission', '0013_remove_campaign_template_interview_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contest',
            name='file',
            field=files.models.ConfigurableStorageFileField(blank=True, upload_to=admission.models.contest_assignments_upload_to, verbose_name='Assignments in pdf format'),
        ),
    ]
