# Generated by Django 3.0.9 on 2021-02-17 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admission', '0016_auto_20210217_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth Date'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='is_studying',
            field=models.NullBooleanField(verbose_name='Are you studying?'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='year_of_graduation',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Graduation Year'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Applicant|additional_info', null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Account'),
        ),
    ]
