# Generated by Django 3.0.9 on 2021-02-17 15:23

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("admission", "0017_auto_20210217_1503"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="faculty",
            field=models.TextField(
                blank=True,
                help_text="Applicant|faculty",
                null=True,
                verbose_name="Faculty",
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="level_of_education",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "1 course bachelor, speciality"),
                    ("2", "2 course bachelor, speciality"),
                    ("3", "3 course bachelor, speciality"),
                    ("4", "4 course bachelor, speciality"),
                    ("5", "last course speciality"),
                    ("6", "1 course magistracy"),
                    ("7", "2 course magistracy"),
                    ("8", "postgraduate"),
                    ("9", "graduate"),
                ],
                help_text="Applicant|course",
                max_length=355,
                null=True,
                verbose_name="Course",
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="university",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applicants",
                to="admission.University",
                verbose_name="Applicant|University",
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="where_did_you_learn",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("uni", "плакат/листовка в университете"),
                    ("social_net", "пост в соц. сетях"),
                    ("friends", "от друзей"),
                    ("other", "другое"),
                    ("habr", "Прочитал в статье на habr.ru"),
                    ("club", "Из CS клуба"),
                    ("tandp", "Теории и практики"),
                ],
                max_length=44,
                verbose_name="Where did you learn about admission?",
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="where_did_you_learn_other",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Where did you learn about admission? (other)",
            ),
        ),
    ]
