# Generated by Django 3.1.7 on 2021-02-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0020_auto_20210220_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='details',
            field=models.JSONField(blank=True, default=dict, verbose_name='Details'),
        ),
    ]
