# Generated by Django 3.1.7 on 2021-02-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admission", "0024_applicant_university"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date of Birth"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="level_of_education",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "1 course bachelor, speciality"),
                    ("2", "2 course bachelor, speciality"),
                    ("3", "3 course bachelor, speciality"),
                    ("4", "4 course bachelor, speciality"),
                    ("5", "5 course speciality"),
                    ("6_spec", "6 course speciality"),
                    ("6", "1 course magistracy"),
                    ("7", "2 course magistracy"),
                    ("8", "postgraduate"),
                    ("9", "graduate"),
                    ("other", "Other"),
                ],
                help_text="Applicant|course",
                max_length=12,
                null=True,
                verbose_name="Course",
            ),
        ),
    ]
