# Generated by Django 3.1.7 on 2021-02-25 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0025_auto_20210225_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='university2',
        ),
    ]
