# Generated by Django 3.1.7 on 2021-03-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0026_remove_applicant_university2'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='preferred_study_program_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Study Program Notes'),
        ),
    ]
