# Generated by Django 3.1.7 on 2021-04-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admission", "0028_auto_20210421_1109"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewstream",
            name="section",
            field=models.CharField(
                choices=[
                    ("all_in_1", "Common"),
                    ("math", "Math"),
                    ("code", "Coding"),
                    ("mv", "Motivation"),
                ],
                default="all_in_1",
                max_length=15,
                verbose_name="Interview|Section",
            ),
            preserve_default=False,
        ),
    ]
