# Generated by Django 3.1.7 on 2021-05-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0031_auto_20210517_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewinvitation',
            name='status',
            field=models.CharField(choices=[('created', 'No Response'), ('declined', 'Declined'), ('expired', 'Expired'), ('accepted', 'Accepted')], default='created', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='interviewinvitation',
            name='expired_at',
            field=models.DateTimeField(verbose_name='Expired at'),
        ),
    ]
