# Generated by Django 3.1.12 on 2021-06-28 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0011_models_help_text'),
        ('admission', '0035_auto_20210624_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='template_interview_feedback',
            field=models.ForeignKey(blank=True, help_text='Leave blank if there is no need to send a feedback email. Email will be sent at 21:00 of the interview day (or at the time of interview status change) after interview is marked as completed.', null=True, on_delete=django.db.models.deletion.PROTECT, to='post_office.emailtemplate', verbose_name='Interview Feedback Template'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.SmallIntegerField(verbose_name='Score'),
        ),
    ]
