# Generated by Django 3.1.7 on 2021-06-29 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0011_models_help_text'),
        ('core', '0015_auto_20210413_1607'),
        ('admission', '0036_auto_20210628_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='venue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='interview', to='core.location', verbose_name='Interview venue'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='template_interview_feedback',
            field=models.ForeignKey(blank=True, help_text='Leave blank if there is no need to send a feedback email. Email will be sent at the time of interview status change, but not earlier than 21:00 of the day of the interview', null=True, on_delete=django.db.models.deletion.PROTECT, to='post_office.emailtemplate', verbose_name='Interview Feedback Template'),
        ),
    ]
