# Generated by Django 3.1.7 on 2021-06-29 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210413_1607'),
        ('admission', '0037_auto_20210629_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='venue',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='interview', to='core.location', verbose_name='Interview venue'),
        ),
    ]
