# Generated by Django 3.2.12 on 2022-03-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0040_auto_20210910_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='data',
            field=models.JSONField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='meta',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
