# Generated by Django 3.2.12 on 2022-04-03 11:11

from django.db import connection, migrations
from admission.models import Applicant

schema_editor = connection.schema_editor()


def get_index_name(field):
    return schema_editor._create_index_name(field.model._meta.db_table, [field.attname])


new_field_index_name = get_index_name(Applicant.university.field)
old_field_index_name = get_index_name(Applicant.university_legacy.field)


class Migration(migrations.Migration):
    dependencies = [
        ("admission", "0041_auto_20220305_1143"),
    ]

    operations = [
        migrations.RenameField(
            model_name="applicant",
            old_name="university",
            new_name="university_legacy",
        ),
        migrations.RunSQL(
            f"ALTER INDEX {new_field_index_name} rename TO {old_field_index_name}"
        ),
    ]
