# Generated by Django 3.2.12 on 2022-04-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0041_auto_20220305_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='university',
            new_name='university_legacy',
        ),
    ]
