# Generated by Django 3.2.13 on 2023-03-20 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0002_city_order"),
        ("admission", "0043_applicant_university"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResidenceCity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.PositiveIntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="External ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Name")),
                ("display_name", models.TextField(verbose_name="Display Name")),
                (
                    "order",
                    models.PositiveIntegerField(default=512, verbose_name="Order"),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admission_cities",
                        to="universities.country",
                        verbose_name="Country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Residence City",
                "verbose_name_plural": "Residence Cities",
            },
        ),
        migrations.CreateModel(
            name="CampaignCity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="admission.campaign",
                        verbose_name="Campaign",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="admission.residencecity",
                        verbose_name="City",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign Available in City",
                "verbose_name_plural": "Campaigns Available in City",
            },
        ),
        migrations.AddConstraint(
            model_name="campaigncity",
            constraint=models.UniqueConstraint(
                fields=("campaign", "city"), name="unique_campaign_per_city"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaigncity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("city__isnull", True)),
                fields=("campaign",),
                name="admission_campaigncity_default_campaign_unique",
            ),
        ),
    ]
