# Generated by Django 3.2.13 on 2023-03-21 08:22

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0044_auto_20230320_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='where_did_you_learn',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('uni', 'плакат/листовка в университете'), ('social_net', 'пост в соц. сетях'), ('ambassador', 'от амбассадора Yandex U-Team'), ('friends', 'от друзей'), ('other', 'другое'), ('habr', 'Прочитал в статье на habr.ru'), ('club', 'Из CS клуба'), ('tandp', 'Теории и практики')], max_length=55, verbose_name='Where did you learn about admission?'),
        ),
    ]
