# Generated by Django 3.2.18 on 2023-03-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0045_auto_20230321_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='order',
            field=models.PositiveIntegerField(default=1000, verbose_name='Order'),
        ),
    ]
