# Generated by Django 3.2.18 on 2023-03-24 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0047_auto_20230322_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='residence_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admission.residencecity', verbose_name='Residence city'),
        ),
    ]
