# Generated by Django 3.2.18 on 2024-03-26 10:57

import admission.models
import datetime
import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0049_alter_applicant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='diploma_degree',
            field=models.CharField(blank=True, choices=[('1', 'bachelor'), ('2', 'speciality'), ('3', 'magistracy'), ('4', 'postgraduate'), ('5', 'secondary professional')], help_text='Applicant|diploma_degree', max_length=30, null=True, verbose_name='Degree of diploma'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('o', 'Other/Prefer Not to Say')], default='o', max_length=1, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='has_diploma',
            field=models.CharField(choices=[('yes', 'yes'), ('in_process', 'in process of getting degree'), ('no', 'no')], help_text='Applicant|has_diploma', max_length=30, null=True, verbose_name='Has diploma'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='internship_beginning',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2050, 1, 1)), django.core.validators.MinValueValidator(datetime.date(1900, 1, 1))], verbose_name='Date of the internship beginning'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='internship_end',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2050, 1, 1)), django.core.validators.MinValueValidator(datetime.date(1900, 1, 1))], verbose_name='Date of the internship end'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='internship_not_ended',
            field=models.BooleanField(default=False, help_text='Applicant|internship_not_ended', verbose_name='Does your internship still going?'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='new_track',
            field=models.BooleanField(null=True, verbose_name='Are applying for alternative track?'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='new_track_info',
            field=models.CharField(blank=True, help_text='Applicant|alternative_track_info', max_length=1000, null=True, verbose_name='Alternative track info'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Applicant|photo', upload_to=admission.models.applicant_photo_upload_to, verbose_name='Applicant photo'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='working_hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Working hours'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 1, 1)), django.core.validators.MinValueValidator(datetime.date(1900, 1, 1))], verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='level_of_education',
            field=models.CharField(blank=True, choices=[('1', '1 course bachelor, speciality'), ('2', '2 course bachelor, speciality'), ('3', '3 course bachelor, speciality'), ('4', '4 course bachelor, speciality'), ('5', '5 course speciality'), ('6', '6 course speciality'), ('7', '1 course magistracy'), ('8', '2 course magistracy'), ('9', 'postgraduate'), ('10', 'academic_leave'), ('other', 'Other')], help_text='Applicant|course', max_length=12, null=True, verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phone',
            field=models.CharField(help_text='Applicant|phone', max_length=42, validators=[django.core.validators.RegexValidator(regex='^\\+?[1-9][0-9]{7,14}$')], verbose_name='Contact phone'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='where_did_you_learn',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('uni', 'плакат в университете'), ('group', 'тг-канал/группа в университете'), ('post', 'пост в вк/тг-канале'), ('mailing', 'рассылка по почте'), ('community', 'от студента/выпускника/преподавателя ШАД'), ('ambassador', 'от амбассадора Yandex U-Team'), ('friends', 'от друзей'), ('bloger', 'от блогера'), ('other', 'другое'), ('habr', 'Прочитал в статье на habr.ru'), ('club', 'Из CS клуба'), ('tandp', 'Теории и практики'), ('social_net', 'пост в соц. сетях')], max_length=91, verbose_name='Where did you learn about admission?'),
        ),
    ]
