# Generated by Django 3.2.18 on 2024-03-15 08:53

import admission.models
import datetime
import django.core.validators
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0049_alter_applicant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=admission.models.applicant_photo_upload_to, verbose_name='Applicant|photo'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 3, 15)), django.core.validators.MinValueValidator(datetime.date(1900, 1, 1))], verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phone',
            field=models.CharField(help_text='Applicant|phone', max_length=42, validators=[django.core.validators.RegexValidator(regex='^\\+?[1-9][0-9]{7,14}$')], verbose_name='Contact phone'),
        ),
    ]
