# Generated by Django 3.2.18 on 2024-03-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0050_auto_20240326_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='level_of_education_other',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course (other)'),
        ),
    ]
