# Generated by Django 3.2.18 on 2024-03-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0052_auto_20240317_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='diploma_degree',
            field=models.CharField(blank=True, choices=[('1', 'bachelor'), ('2', 'speciality'), ('3', 'magistracy'), ('4', 'postgraduate'), ('5', 'secondary professional')], help_text='Applicant|diploma_degree', max_length=30, null=True, verbose_name='Degree oj diploma'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='has_diploma',
            field=models.CharField(choices=[('1', 'yes'), ('2', 'in process of getting degree'), ('3', 'no')], help_text='Applicant|has_diploma', max_length=30, null=True, verbose_name='Has diploma'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='level_of_education',
            field=models.CharField(blank=True, choices=[('1', '1 course bachelor, speciality'), ('2', '2 course bachelor, speciality'), ('3', '3 course bachelor, speciality'), ('4', '4 course bachelor, speciality'), ('5', '5 course speciality'), ('6', '6 course speciality'), ('7', '1 course magistracy'), ('8', '2 course magistracy'), ('9', 'postgraduate'), ('10', 'academic_leave'), ('other', 'Other')], help_text='Applicant|course', max_length=12, null=True, verbose_name='Course'),
        ),
    ]
