# Generated by Django 3.2.18 on 2024-03-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0053_auto_20240319_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='working_hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Working hours'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='diploma_degree',
            field=models.CharField(blank=True, choices=[('1', 'bachelor'), ('2', 'speciality'), ('3', 'magistracy'), ('4', 'postgraduate'), ('5', 'secondary professional')], help_text='Applicant|diploma_degree', max_length=30, null=True, verbose_name='Degree of diploma'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='has_diploma',
            field=models.CharField(choices=[('yes', 'yes'), ('in_process', 'in process of getting degree'), ('no', 'no')], help_text='Applicant|has_diploma', max_length=30, null=True, verbose_name='Has diploma'),
        ),
    ]
