# Generated by Django 3.2.18 on 2024-03-22 12:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0054_auto_20240320_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='where_did_you_learn',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('uni', 'плакат в университете'), ('group', 'тг-канал/группа в университете'), ('post', 'пост в вк/тг-канале'), ('mailing', 'рассылка по почте'), ('community', 'от студента/выпускника/преподавателя ШАД'), ('ambassador', 'от амбассадора Yandex U-Team'), ('friends', 'от друзей'), ('bloger', 'от блогера'), ('other', 'другое'), ('habr', 'Прочитал в статье на habr.ru'), ('club', 'Из CS клуба'), ('tandp', 'Теории и практики'), ('social_net', 'пост в соц. сетях')], max_length=91, verbose_name='Where did you learn about admission?'),
        ),
    ]
