# Generated by Django 3.2.18 on 2024-07-04 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0054_auto_20240612_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='duration',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(10)], verbose_name='Slot duration'),
        ),
        migrations.AddField(
            model_name='interview',
            name='format',
            field=models.CharField(choices=[('offline', 'Offline'), ('online', 'Online')], default='Undefined', max_length=42, verbose_name='Interview Format'),
            preserve_default=False,
        ),
    ]
