# Generated by Django 3.2.18 on 2024-07-18 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0055_auto_20240704_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='new_track',
            field=models.BooleanField(blank=True, null=True, verbose_name='Are applying for alternative track?'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='new_track_info',
            field=models.TextField(blank=True, help_text='Applicant|alternative_track_info', null=True, verbose_name='Alternative track info'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='duration',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(10)], verbose_name='Interview|Slot duration'),
        ),
    ]
