# Generated by Django 3.2.18 on 2024-03-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0055_alter_applicant_where_did_you_learn'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('o', 'Other/Prefer Not to Say')], default='o', max_length=1, verbose_name='Gender'),
        ),
    ]
