# Generated by Django 3.2.18 on 2025-03-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0056_auto_20240718_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='mipt_track',
            field=models.CharField(blank=True, choices=[('basic', 'Basiс track'), ('advanced', 'Advanced track')], max_length=30, null=True, verbose_name='MIPT track'),
        ),
    ]
