# Generated by Django 3.2.18 on 2024-03-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0056_applicant_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='alternative_track_info',
            field=models.CharField(help_text='Applicant|alternative_track_info', max_length=1000, null=True, verbose_name='Alternative track info'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='is_alternative_track',
            field=models.BooleanField(null=True, verbose_name='Are applying for alternative track?'),
        ),
    ]
