# Generated by Django 3.2.18 on 2024-03-24 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0057_auto_20240324_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='is_alternative_track',
            new_name='new_track',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='alternative_track_info',
            new_name='new_track_info',
        ),
    ]
