# Generated by Django 3.2.18 on 2025-03-11 14:30

import admission.models
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0057_applicant_mipt_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='mipt_expectations',
            field=models.TextField(blank=True, null=True, verbose_name='MIPT expectations'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='mipt_gpa',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='MIPT GPA'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='mipt_grades_file',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=admission.models.applicant_grades_upload_to, verbose_name='MIPT grades file'),
        ),
    ]
