# Generated by Django 3.2.18 on 2025-03-18 09:37

import admission.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0059_auto_20250313_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='template_registration_mipt_advanced',
            field=models.CharField(blank=True, help_text='Template name for contest registration email for MIPT Advanced track applicants', max_length=255, validators=[admission.models.validate_email_template_name], verbose_name='MIPT Advanced Registration Template'),
        ),
    ]
