# Generated by Django 3.2.18 on 2025-04-02 20:21

import admission.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0060_campaign_template_registration_mipt_advanced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='mipt_grades_file',
            field=models.FileField(blank=True, null=True, upload_to=admission.models.applicant_grades_upload_to, verbose_name='MIPT grades file'),
        ),
    ]
