# Generated by Django 3.2.18 on 2025-04-03 16:31

import admission.models
import core.db.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_siteconfiguration_managers'),
        ('admission', '0060_campaign_template_registration_mipt_advanced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='mipt_grades_file',
            field=models.FileField(blank=True, null=True, upload_to=admission.models.applicant_grades_upload_to, verbose_name='MIPT grades file'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='type',
            field=models.IntegerField(choices=[(1, 'Testing'), (2, 'Exam'), (3, 'Olympiad')], verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='Olympiad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('yandex_contest_id', models.CharField(blank=True, help_text='Applicant|yandex_contest_id', max_length=42, null=True, verbose_name='Contest #ID')),
                ('contest_participant_id', models.IntegerField(blank=True, help_text='participant_id in Yandex.Contest', null=True, verbose_name='Participant ID')),
                ('contest_status_code', models.IntegerField(blank=True, null=True, verbose_name='Yandex API Response')),
                ('status', models.CharField(choices=[('new', 'Not registered in the contest'), ('registered', 'Syncing with a contest'), ('manual', 'Manual score input')], default='new', help_text='Choose `manual score input` to avoid synchronization with contest results', max_length=15, verbose_name='Status')),
                ('score', core.db.fields.ScoreField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Score')),
                ('math_score', core.db.fields.ScoreField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Math Score')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Details')),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='olympiad', to='admission.applicant', verbose_name='Applicant')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Olympiad Result',
                'verbose_name_plural': 'Olympiad Results',
            },
            bases=(models.Model, admission.models.ApplicantRandomizeContestMixin),
        ),
    ]
