# Generated by Django 3.2.18 on 2025-04-15 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0061_alter_applicant_mipt_grades_file'),
        ('admission', '0061_auto_20250403_1631'),
    ]

    operations = [
    ]
