# Generated by Django 3.2.18 on 2025-04-16 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0062_alter_applicant_unique_together'),
        ('admission', '0062_merge_20250415_1020'),
    ]

    operations = [
    ]
