# Generated by Django 3.2.18 on 2025-04-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0063_merge_20250416_1424'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='applicant',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', {'rejected_exam_preselect', 'rejected_interview_preselect'}), _negated=True), fields=('email', 'campaign'), name='unique_emails'),
        ),
    ]
