# Generated by Django 2.2.4 on 2019-08-30 08:14

import bitfield.models
import core.models
from core.timezone import models as tz_models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='City name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='City name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='City name')),
                ('abbr', models.CharField(max_length=20, verbose_name='Abbreviation')),
                ('abbr_ru', models.CharField(max_length=20, null=True, verbose_name='Abbreviation')),
                ('abbr_en', models.CharField(max_length=20, null=True, verbose_name='Abbreviation')),
                ('time_zone', models.CharField(choices=[('Europe/Moscow', 'Europe/Moscow'), ('Asia/Novosibirsk', 'Asia/Novosibirsk')], max_length=63, verbose_name='Timezone')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
            bases=(tz_models.TimezoneAwareMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Location|Name')),
                ('address', models.CharField(blank=True, help_text='Should be resolvable by Google Maps', max_length=500, verbose_name='Address')),
                ('description', models.TextField(help_text='How to style text read <a href="/commenting-the-right-way/" target="_blank">here</a>. Partially HTML is enabled too.', verbose_name='Description')),
                ('directions', models.TextField(blank=True, null=True, verbose_name='Directions')),
                ('flags', bitfield.models.BitField((('lecture', 'Class'), ('interview', 'Interview')), default=1, help_text='Set purpose of this place', verbose_name='Flags')),
                ('city', models.ForeignKey(default='spb', on_delete=django.db.models.deletion.PROTECT, to='core.City', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Location|Name',
                'verbose_name_plural': 'Locations',
                'ordering': ('name',),
            },
            bases=(tz_models.TimezoneAwareMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=8, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Branch|Name')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('time_zone', models.CharField(choices=[('Europe/Moscow', 'Europe/Moscow'), ('Asia/Novosibirsk', 'Asia/Novosibirsk')], max_length=63, verbose_name='Timezone')),
                ('description', models.TextField(blank=True, help_text='Branch|Description', verbose_name='Description')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.City', verbose_name='Branch Location')),
                ('site', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
            bases=(tz_models.TimezoneAwareMixin, models.Model),
            managers=[
                ('objects', core.models.BranchManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('code', 'site'), name='unique_code_per_site'),
        ),
    ]
