# Generated by Django 2.2.5 on 2019-09-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='established',
            field=models.PositiveIntegerField(default=2011, verbose_name='Established'),
            preserve_default=False,
        ),
    ]
