# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-30 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sites.Site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sites.Site', verbose_name='Site'),
        ),
    ]
