# Generated by Django 2.2.4 on 2019-08-09 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180730_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='city',
            field=models.ForeignKey(default='spb', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.City', verbose_name='City'),
        ),
    ]
