# Generated by Django 2.2.10 on 2020-02-07 13:40

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_branch_established'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='branch',
            managers=[
                ('objects', core.models.BranchManager()),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Branch|Name'),
        ),
        migrations.AddField(
            model_name='branch',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Branch|Name'),
        ),
    ]
