# Generated by Django 2.2.4 on 2019-08-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0022_auto_20190809_1402'),
        ('core', '0003_auto_20190809_1402'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterModelTable('university', 'admission_university'),
                # Repeat for the other models you want to move.
            ],
            state_operations=[
                migrations.DeleteModel(
                    name='University',
                ),
            ],
        ),
    ]
