# Generated by Django 2.2.10 on 2020-05-14 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200207_1340'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='branch',
            managers=[
            ],
        ),
    ]
