# Generated by Django 2.2.4 on 2019-08-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqcategory',
            name='site',
        ),
        migrations.DeleteModel(
            name='Faq',
        ),
        migrations.DeleteModel(
            name='FaqCategory',
        ),
    ]
