# Generated by Django 3.0.9 on 2020-09-04 12:47

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200902_0811'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='branch',
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
