# Generated by Django 2.2.4 on 2019-08-14 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('core', '0006_branch'),
        ('learning', '0028_auto_20190814_0920'),
        ('users', '0020_auto_20190814_0943'),
        ('projects', '0019_auto_20190814_0927'),
        ('library', '0009_auto_20190814_0923'),
        ('study_programs', '0015_auto_20190814_0940'),
        ('admission', '0032_auto_20190814_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='branch',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='branch',
            name='time_zone',
            field=models.CharField(choices=[('Europe/Moscow', 'Europe/Moscow'), ('Asia/Novosibirsk', 'Asia/Novosibirsk')], default='Europe/Moscow', max_length=63, verbose_name='Timezone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(db_index=True, max_length=8, verbose_name='Code'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('code', 'site'), name='unique_code_per_site'),
        ),
    ]
