# Generated by Django 2.2.4 on 2019-08-14 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190814_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.City', verbose_name='Branch Location'),
        ),
    ]
