# Generated by Django 3.0.9 on 2020-09-08 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
        ('core', '0007_auto_20200904_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('default_from_email', models.CharField(max_length=255, verbose_name='Default Email Address')),
                ('email_host', models.CharField(help_text='The host to use for sending email', max_length=255, verbose_name='Email Host')),
                ('email_host_password', models.CharField(help_text='Password to use for the SMTP server defined in EMAIL_HOST. Should be encrypted with a symmetric key stored in a settings.SECRET_KEY', max_length=255, verbose_name='Email Host Password')),
                ('email_host_user', models.CharField(help_text='Username to use for the SMTP server defined in EMAIL_HOST', max_length=255, verbose_name='Email Host User')),
                ('email_port', models.PositiveSmallIntegerField(help_text='Port to use for the SMTP server defined in EMAIL_HOST.', verbose_name='Email Port')),
                ('email_use_tls', models.BooleanField(help_text='Whether to use an explicit TLS (secure) connection when talking to the SMTP server', verbose_name='Use TLS')),
                ('email_use_ssl', models.BooleanField(help_text='Whether to use an implicit TLS (secure) connection when talking to the SMTP server.', verbose_name='Use SSL')),
                ('changed_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Changed by')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='site_configuration', to='sites.Site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'db_table': 'site_configurations',
            },
        ),
    ]
