# Generated by Django 2.2.4 on 2019-08-14 13:48

from django.db import migrations


def set_location(apps, schema_editor):
    Branch = apps.get_model('core', 'Branch')
    City = apps.get_model('core', 'City')
    for b in Branch.objects.all():
        if not b.is_remote:
            b.city = City.objects.get(code=b.code)
            b.save(update_fields=['city'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_branch_city'),
    ]

    operations = [
        migrations.RunPython(set_location)
    ]
