# Generated by Django 2.2.4 on 2019-08-14 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190814_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='is_remote',
        ),
    ]
