# Generated by Django 3.0.9 on 2020-09-11 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('core', '0010_siteconfiguration_default_branch_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_configuration', to='sites.Site', verbose_name='Site'),
        ),
    ]
