# Generated by Django 2.2.4 on 2019-08-14 15:14

import bitfield.models
import core.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_branch_is_remote'),
        ('courses', '0013_auto_20190814_1513'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Venue|Name')),
                ('address', models.CharField(blank=True, help_text='Should be resolvable by Google Maps', max_length=500, verbose_name='Venue|Address')),
                ('description', models.TextField(help_text='How to style text read <a href="/commenting-the-right-way/" target="_blank">here</a>. Partially HTML is enabled too.', verbose_name='Description')),
                ('directions', models.TextField(blank=True, null=True, verbose_name='Directions')),
                ('flags', bitfield.models.BitField((('lecture', 'Class'), ('interview', 'Interview')), default=1, help_text='Set purpose of this place', verbose_name='Flags')),
                ('is_preferred', models.BooleanField(default=False, help_text='Will be displayed on top of the venue list', verbose_name='Preferred')),
                ('city', models.ForeignKey(blank=True, default='spb', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.City', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Venue',
                'verbose_name_plural': 'Venues',
                'ordering': ['-is_preferred', 'name'],
            },
            bases=(core.mixins.TimezoneAwareModel, models.Model),
        ),
    ]

    database_operations = []

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]