# Generated by Django 2.2.4 on 2019-08-14 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_venue'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table=None,
        ),
    ]
