# Generated by Django 3.1.7 on 2021-02-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200911_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Code'),
        ),
    ]
