# Generated by Django 3.1.7 on 2021-03-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='instagram_access_token',
            field=models.CharField(blank=True, max_length=420, null=True),
        ),
    ]
