# Generated by Django 2.2.4 on 2019-08-16 13:30

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190816_1326'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='branch',
            managers=[
                ('objects', core.models.BranchManager()),
            ],
        ),
    ]
