# Generated by Django 2.2.4 on 2019-08-21 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0009_auto_20190814_1514'),
        ('admission', '0033_auto_20190814_1514'),
        ('learning', '0029_auto_20190814_1514'),
        ('courses', '0019_auto_20190821_0951'),
        ('core', '0014_auto_20190816_1330'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Venue',
            new_name='Location',
        ),
    ]
