# Generated by Django 2.2.4 on 2019-08-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190821_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-is_preferred', 'name'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, help_text='Should be resolvable by Google Maps', max_length=500, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_preferred',
            field=models.BooleanField(default=False, help_text='Will be displayed on top of the location list', verbose_name='Preferred'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=140, verbose_name='Location|Name'),
        ),
    ]
