# Generated by Django 3.2.7 on 2021-09-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210413_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='email_host',
            field=models.CharField(blank=True, help_text='The host of the SMTP server to use for sending email', max_length=255, verbose_name='Email Host'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='email_host_password',
            field=models.CharField(blank=True, help_text='Password to use for the SMTP server defined in EMAIL_HOST. Should be encrypted with a symmetric key stored in a settings.SECRET_KEY', max_length=255, verbose_name='Email Host Password'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='email_host_user',
            field=models.CharField(blank=True, help_text='Username to use for the SMTP server defined in EMAIL_HOST', max_length=255, verbose_name='Email Host User'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='email_port',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Port to use for the SMTP server defined in EMAIL_HOST.', null=True, verbose_name='Email Port'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='email_use_ssl',
            field=models.BooleanField(help_text='Whether to use an implicit TLS (secure) connection when talking to the SMTP server.', null=True, verbose_name='Use SSL'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='email_use_tls',
            field=models.BooleanField(help_text='Whether to use an explicit TLS (secure) connection when talking to the SMTP server', null=True, verbose_name='Use TLS'),
        ),
    ]
