# Generated by Django 3.2.12 on 2022-02-09 16:14

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210910_1019'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='siteconfiguration',
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='lms_domain',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Domain Name for Learning Management System'),
        ),
    ]
