# Generated by Django 2.2.4 on 2019-08-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190821_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('name',), 'verbose_name': 'Location|Name', 'verbose_name_plural': 'Locations'},
        ),
        migrations.RemoveField(
            model_name='location',
            name='is_preferred',
        ),
        migrations.AddField(
            model_name='location',
            name='time_zone',
            field=models.CharField(choices=[('Europe/Moscow', 'Europe/Moscow'), ('Asia/Novosibirsk', 'Asia/Novosibirsk')], default='Europe/Moscow', max_length=63, verbose_name='Timezone'),
            preserve_default=False,
        ),
    ]
