# Generated by Django 2.2.4 on 2019-08-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190821_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='time_zone',
            field=models.CharField(choices=[('Europe/Moscow', 'Europe/Moscow'), ('Asia/Novosibirsk', 'Asia/Novosibirsk')], default='Europe/Moscow', max_length=63, verbose_name='Timezone'),
            preserve_default=False,
        ),
    ]
