# Generated by Django 3.2.18 on 2024-02-27 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_siteconfiguration_lms_subdomain'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='siteconfiguration',
            managers=[
            ],
        ),
    ]
