# Generated by Django 2.2.4 on 2019-08-21 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20190821_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='time_zone',
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.ForeignKey(default='spb', on_delete=django.db.models.deletion.PROTECT, to='core.City', verbose_name='City'),
        ),
    ]
