# Generated by Django 3.2.18 on 2025-02-03 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('core', '0019_alter_siteconfiguration_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='site',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.ForeignKey(default='msk', on_delete=django.db.models.deletion.PROTECT, to='core.city', verbose_name='City'),
        ),
    ]
