# Generated by Django 2.2.4 on 2019-08-30 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.Course'),
        ),
        migrations.AddField(
            model_name='coursenews',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='coursenews',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.Course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='courseclassattachment',
            name='course_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseClass', verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.Course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.LearningSpace', verbose_name='CourseClass|Venue'),
        ),
        migrations.AddField(
            model_name='course',
            name='additional_branches',
            field=models.ManyToManyField(blank=True, help_text='Branches where the course is also available for enrollment', related_name='additional_branches', to='core.Branch', verbose_name='Additional Branches'),
        ),
        migrations.AddField(
            model_name='course',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='core.Branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='course',
            name='meta_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.MetaCourse', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.Semester', verbose_name='Semester'),
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(related_name='teaching_set', through='courses.CourseTeacher', to=settings.AUTH_USER_MODEL, verbose_name='Course|teachers'),
        ),
        migrations.AddField(
            model_name='assignmentattachment',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Assignment', verbose_name='Assignment'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.Course', verbose_name='Course offering'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='notify_teachers',
            field=models.ManyToManyField(blank=True, help_text='Leave blank if you want to populate list from the course settings', to='courses.CourseTeacher', verbose_name='Assignment|notify_settings'),
        ),
        migrations.AlterUniqueTogether(
            name='courseteacher',
            unique_together={('teacher', 'course')},
        ),
        migrations.AddConstraint(
            model_name='coursereview',
            constraint=models.UniqueConstraint(fields=('course', 'author'), name='one_author_review_per_course'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('meta_course', 'semester', 'branch'), name='unique_course_for_branch_in_a_term'),
        ),
    ]
