# Generated by Django 2.2.9 on 2020-01-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190830_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='ttc',
            field=models.TimeField(blank=True, help_text='Calculated amount of time required for the task to be completed', null=True, verbose_name='Time to Completion (min)'),
        ),
    ]
