# Generated by Django 2.2.9 on 2020-01-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200130_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='is_online',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='submission_type',
            field=models.CharField(choices=[('online', 'Online Submission'), ('external', 'External Service'), ('other', 'No Submission')], max_length=42, verbose_name='Submission Type'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='ttc',
            field=models.TimeField(blank=True, help_text='Estimated amount of time required for the task to be completed', null=True, verbose_name='Time to Completion'),
        ),
    ]
