# Generated by Django 2.2 on 2019-04-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190318_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='survey_url',
            field=models.URLField(blank=True, help_text='Leave empty if you want to fetch survey url from DB', verbose_name='Survey URL'),
        ),
    ]
