# Generated by Django 2.2.9 on 2020-01-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20200130_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='ttc',
            field=models.DurationField(blank=True, help_text='Estimated amount of time required for the task to be completed', null=True, verbose_name='Time to Completion'),
        ),
    ]
