# Generated by Django 2.2.10 on 2020-02-07 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200131_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='group_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('branch', 'Branch')], default='branch', editable=False, help_text='Choose `Branch` to auto generate student groups from course branches.', max_length=100, verbose_name='Student Group Mode'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Assignment Weight'),
        ),
    ]
