# Generated by Django 2.2.1 on 2019-06-26 12:46

import bitfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20190528_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_preview_url',
            field=models.URLField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='courseteacher',
            name='roles',
            field=bitfield.models.BitField((('lecturer', 'Lecturer'), ('reviewer', 'Reviewer'), ('seminar', 'Seminarian')), default=1),
        ),
    ]
