# Generated by Django 2.2.1 on 2019-06-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20190626_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='video_preview_url',
        ),
        migrations.AddField(
            model_name='course',
            name='youtube_video_id',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
