# Generated by Django 2.2.10 on 2020-02-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_auto_20200211_1252'),
        ('courses', '0007_auto_20200207_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='restrict_to',
            field=models.ManyToManyField(related_name='restricted_assignments', through='learning.AssignmentGroup', to='learning.StudentGroup', verbose_name='Groups'),
        ),
    ]
