# Generated by Django 2.2.1 on 2019-07-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20190626_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='youtube_video_id',
            field=models.CharField(blank=True, editable=False, help_text='Helpful for getting thumbnail on /videos/ page', max_length=255),
        ),
    ]
