# Generated by Django 2.2.10 on 2020-03-06 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_assignment_restrict_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='materials_visibility',
            field=models.CharField(choices=[('all', 'All'), ('students', 'Only Students')], default='all', help_text='Default visibility for class materials.', max_length=8, verbose_name='Materials Visibility'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='notify_teachers',
            field=models.ManyToManyField(blank=True, help_text='Specify who will receive notifications about new comments', to='courses.CourseTeacher', verbose_name='Assignment|notify_settings'),
        ),
        migrations.AlterField(
            model_name='course',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='core.Branch', verbose_name='Main Branch'),
        ),
        migrations.AlterField(
            model_name='course',
            name='group_mode',
            field=models.CharField(choices=[('no_groups', 'Without Groups'), ('manual', 'Manual'), ('branch', 'Branch')], default='branch', editable=False, help_text='Choose `Branch` to auto generate student groups from course branches.', max_length=100, verbose_name='Student Group Mode'),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], db_index=True, default='ru', help_text='The language in which lectures are given.', max_length=5, verbose_name='Language'),
        ),
    ]
