# Generated by Django 2.2.10 on 2020-03-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20200306_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseclass',
            name='materials_visibility',
            field=models.CharField(choices=[('all', 'All Users'), ('students', 'Only Students')], default='all', help_text='Slides, attachments and other materials', max_length=8, verbose_name='Materials Visibility'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='materials_visibility',
            field=models.CharField(choices=[('all', 'All Users'), ('students', 'Only Students')], default='all', help_text='Default visibility for class materials.', max_length=8, verbose_name='Materials Visibility'),
        ),
    ]
