# Generated by Django 2.2.10 on 2020-03-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20200310_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='materials_files',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Public Attachments'),
        ),
        migrations.AlterField(
            model_name='course',
            name='materials_slides',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Public Slides'),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='video_url',
            field=models.URLField(blank=True, help_text='Both YouTube and Yandex Video are supported', verbose_name='Video Recording'),
        ),
    ]
