# Generated by Django 2.2.3 on 2019-07-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_learners_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='materials_video',
        ),
        migrations.AddField(
            model_name='course',
            name='videos_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
