# Generated by Django 2.2.4 on 2019-08-14 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20190723_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='sites',
        ),
    ]
