# Generated by Django 2.2.10 on 2020-03-11 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20200311_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='materials_files',
            new_name='public_attachments_count',
        ),
    ]
