# Generated by Django 2.2.4 on 2019-08-14 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_remove_venue_sites'),
        ('learning', '0028_auto_20190814_0920'),
        ('announcements', '0008_auto_20190813_1738'),
        ('admission', '0032_auto_20190814_0917'),
    ]

    database_operations = [
        migrations.AlterModelTable('venue', 'core_venue'),
    ]

    state_operations = []

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
