# Generated by Django 2.2.10 on 2020-03-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20200311_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='videos_count',
            new_name='public_videos_count',
        ),
    ]
