# Generated by Django 2.2.10 on 2020-03-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_auto_20200316_1238'),
        ('courses', '0014_auto_20200311_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseclass',
            name='restricted_to',
            field=models.ManyToManyField(related_name='course_classes', through='learning.CourseClassGroup', to='learning.StudentGroup', verbose_name='Groups'),
        ),
    ]
