# Generated by Django 2.2.4 on 2019-08-14 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20190814_1514'),
        ('admission', '0033_auto_20190814_1514'),
        ('announcements', '0009_auto_20190814_1514'),
        ('learning', '0029_auto_20190814_1514'),
    ]

    state_operations = [
        migrations.DeleteModel(
            name='Venue',
        ),
    ]

    operations = [
        # After this state operation, the Django DB state should match the
        # actual database structure.
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]