# Generated by Django 2.2.10 on 2020-03-16 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_courseclass_restricted_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='restrict_to',
            new_name='restricted_to',
        ),
    ]
