# Generated by Django 2.2.4 on 2019-08-16 13:30
from django.conf import settings
from django.db import migrations


def fix_branches(apps, schema_editor):
    Branch = apps.get_model('core', 'Branch')
    Course = apps.get_model('courses', 'Course')

    for c in Course.objects.all():
        if c.is_open:
            site_id = settings.CLUB_SITE_ID
        else:
            site_id = settings.CENTER_SITE_ID
        if c.city_id == 'online':
            code = 'distance'
        else:
            code = c.city_id
        branch = Branch.objects.get(code=code, site_id=site_id)
        c.branch = branch
        c.save(update_fields=['branch'])


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_course_branch'),
        ('core', '0014_auto_20190816_1330'),
    ]

    operations = [
        migrations.RunPython(fix_branches)
    ]
