# Generated by Django 2.2.10 on 2020-03-30 18:37
import core.timezone.fields
import core.timezone.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20200316_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='deadline_at',
            field=core.timezone.fields.TimezoneAwareDateTimeField(verbose_name='Assignment|deadline'),
        ),
    ]
