# Generated by Django 2.2.4 on 2019-08-21 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190816_1330'),
        ('courses', '0017_auto_20190816_1330'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('meta_course', 'semester', 'branch')},
        ),
    ]
