# Generated by Django 2.2.10 on 2020-04-24 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20200330_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='branch',
            new_name='main_branch',
        ),
    ]
