# Generated by Django 2.2.10 on 2020-04-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20200424_1246'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course',
            name='unique_course_for_branch_in_a_term',
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('meta_course', 'semester', 'main_branch'), name='unique_course_for_main_branch_in_a_term'),
        ),
    ]
