# Generated by Django 2.2.10 on 2020-04-24 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200207_1340'),
        ('courses', '0019_auto_20200424_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False, verbose_name='Main Branch')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Branch', verbose_name='Branch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Course Branch',
                'verbose_name_plural': 'Course Branches',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='branches',
            field=models.ManyToManyField(help_text='All branches where the course is available for enrollment', related_name='branches', through='courses.CourseBranch', to='core.Branch', verbose_name='Course Branches'),
        ),
        migrations.AddConstraint(
            model_name='coursebranch',
            constraint=models.UniqueConstraint(fields=('course', 'branch'), name='unique_course_branch'),
        ),
    ]
