# Generated by Django 3.0.9 on 2020-08-12 18:40

import courses.models
from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20200424_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='enrollment_end_at',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='enrollment_start_at',
        ),
        migrations.AddField(
            model_name='course',
            name='ask_enrollment_reason',
            field=models.BooleanField(default=False, help_text="Ask a student why they wants to enroll in the course when they clicks the 'Enroll' button.", verbose_name='Ask Enrollment Reason'),
        ),
        migrations.AlterField(
            model_name='assignmentattachment',
            name='attachment',
            field=files.models.ConfigurableStorageFileField(max_length=150, upload_to=courses.models.assignment_attachment_upload_to),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='slides',
            field=files.models.ConfigurableStorageFileField(blank=True, max_length=200, upload_to=courses.models.course_class_slides_upload_to, verbose_name='Slides'),
        ),
        migrations.AlterField(
            model_name='courseclassattachment',
            name='material',
            field=files.models.ConfigurableStorageFileField(max_length=200, upload_to=courses.models.course_class_attachment_upload_to),
        ),
    ]
