# Generated by Django 3.0.9 on 2020-08-13 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_auto_20200812_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_open',
        ),
    ]
