# Generated by Django 2.2.4 on 2019-08-22 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20190822_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseclass',
            name='venue',
        ),
    ]
