# Generated by Django 3.0.9 on 2020-08-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_remove_course_is_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='grading_type',
            field=models.SmallIntegerField(choices=[(0, 'Default'), (1, 'Pass/Fail'), (2, '10-point scale')], default=0, verbose_name='CourseOffering|grading_type'),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='video_url',
            field=models.URLField(blank=True, help_text='Both YouTube and Yandex Video are supported', max_length=512, verbose_name='Video Recording'),
        ),
    ]
