# Generated by Django 2.2.4 on 2019-08-22 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_remove_courseclass_venue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseclass',
            old_name='venue_new',
            new_name='venue',
        ),
    ]
