# Generated by Django 3.0.9 on 2020-08-28 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_auto_20200825_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='additional_branches',
        ),
    ]
