# Generated by Django 3.0.9 on 2020-09-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_remove_course_additional_branches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='submission_type',
            field=models.CharField(choices=[('online', 'Online Submission'), ('external', 'External Service'), ('code_review', 'Code Review Submission'), ('other', 'No Submission')], max_length=42, verbose_name='Submission Type'),
        ),
        migrations.AlterField(
            model_name='course',
            name='materials_visibility',
            field=models.CharField(choices=[('all', 'All Users'), ('students', 'All Students'), ('participants', 'Course Participants')], default='all', help_text='Default visibility for class materials.', max_length=12, verbose_name='Materials Visibility'),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='materials_visibility',
            field=models.CharField(choices=[('all', 'All Users'), ('students', 'All Students'), ('participants', 'Course Participants')], help_text='Slides, attachments and other materials', max_length=12, verbose_name='Materials Visibility'),
        ),
    ]
