# Generated by Django 3.0.9 on 2020-09-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_auto_20200901_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='materials_visibility',
            field=models.CharField(choices=[('public', 'All Users'), ('participants', 'All Students'), ('private', 'Course Participants')], default='participants', help_text='Default visibility for class materials.', max_length=12, verbose_name='Materials Visibility'),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='materials_visibility',
            field=models.CharField(choices=[('public', 'All Users'), ('participants', 'All Students'), ('private', 'Course Participants')], help_text='Slides, attachments and other materials', max_length=12, verbose_name='Materials Visibility'),
        ),
    ]
