# Generated by Django 2.2.4 on 2019-08-26 08:11

from django.db import migrations


def copy_reviews(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')
    CourseReview = apps.get_model('courses', 'CourseReview')
    for course in Course.objects.all():
        if course.reviews_old and course.reviews_old.strip():
            cr = CourseReview.objects.get_or_create(course=course,
                                                    text=course.reviews_old)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_auto_20190826_0804'),
    ]

    operations = [
        migrations.RunPython(copy_reviews)
    ]
