# Generated by Django 2.2.4 on 2019-08-26 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_auto_20190826_0811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='reviews_old',
            new_name='reviews',
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_new', to='courses.Course'),
        ),
    ]
