# Generated by Django 3.0.9 on 2020-09-02 08:19

import courses.models
from django.db import migrations
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_auto_20200902_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentattachment',
            name='attachment',
            field=files.models.ConfigurableStorageFileField(max_length=200, upload_to=courses.models.assignment_attachment_upload_to),
        ),
    ]
