# Generated by Django 3.0.9 on 2020-09-02 09:15

import courses.models
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_auto_20200902_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metacourse',
            name='cover',
            field=sorl.thumbnail.fields.ImageField(blank=True, max_length=200, upload_to=courses.models.meta_course_cover_upload_to, verbose_name='MetaCourse|cover'),
        ),
    ]
