# Generated by Django 2.2.4 on 2019-08-26 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_auto_20190826_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='reviews',
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.Course'),
        ),
    ]
