# Generated by Django 2.2.4 on 2019-08-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20190821_1541'),
        ('courses', '0028_auto_20190826_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='additional_branches',
            field=models.ManyToManyField(help_text='Branches where the course is also available for enrollment', related_name='additional_branches', to='core.Branch', verbose_name='Additional Branches'),
        ),
    ]
