# Generated by Django 2.2.4 on 2019-08-26 13:35

from django.db import migrations


def set_additional_branches(apps, schema_editor):
    Branch = apps.get_model('core', 'Branch')
    Course = apps.get_model('courses', 'Course')
    center_branch_spb = Branch.objects.get(code='spb', site_id=1)
    center_branch_nsk = Branch.objects.get(code='nsk', site_id=1)
    for course in Course.objects.select_related('branch'):
        if course.is_open:
            if course.branch.code == 'spb':
                course.additional_branches.add(center_branch_spb)
            elif course.branch.code == 'nsk':
                course.additional_branches.add(center_branch_nsk)
            elif course.branch.code != 'kzn':
                print("WTF is open", course, course.pk)
        elif course.is_correspondence:
            if course.branch == center_branch_spb:
                course.additional_branches.add(center_branch_nsk)
            elif course.branch == center_branch_nsk:
                course.additional_branches.add(center_branch_spb)
            else:
                print("WTF", course, course.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_course_additional_branches'),
        ('core', '0020_auto_20190821_1541'),
        ('learning', '0036_auto_20190823_0920'),
    ]

    operations = [
        migrations.RunPython(set_additional_branches)
    ]
