# Generated by Django 3.0.9 on 2020-09-15 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_submission'),
        ('courses', '0029_auto_20200915_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='checking_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contests.CheckingSystem', verbose_name='Checking System'),
        ),
    ]
