# Generated by Django 2.2.4 on 2019-08-27 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_auto_20190826_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='ends_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Ends at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semester',
            name='starts_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Starts at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='additional_branches',
            field=models.ManyToManyField(blank=True, help_text='Branches where the course is also available for enrollment', related_name='additional_branches', to='core.Branch', verbose_name='Additional Branches'),
        ),
    ]
