# Generated by Django 3.0.9 on 2020-09-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_assignment_checker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='group_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('branch', 'Branch')], default='branch', help_text='Choose `Branch` to auto generate student groups from course branches.', max_length=100, verbose_name='Student Group Mode'),
        ),
    ]
