# Generated by Django 3.0.9 on 2020-09-18 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_auto_20200918_1004'),
        ('courses', '0030_assignment_checking_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='checking_system',
        ),
        migrations.AddField(
            model_name='assignment',
            name='checker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contests.Checker', verbose_name='Checking System'),
        ),
    ]
