# Generated by Django 2.2.4 on 2019-08-27 09:06
import datetime

from django.db import migrations


def set_semester(apps, schema_editor):
    Semester = apps.get_model('courses', 'Semester')
    import pytz
    from courses.utils import get_term_start
    from courses.utils import next_term_starts_at
    for s in Semester.objects.all():
        s.starts_at = get_term_start(s.year, s.type, pytz.UTC)
        s.ends_at = next_term_starts_at(s.index) - datetime.timedelta(
            days=1)
        s.save(update_fields=['starts_at', 'ends_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_auto_20190827_0903'),
    ]

    operations = [
        migrations.RunPython(set_semester)
    ]
