# Generated by Django 3.0.9 on 2020-10-07 07:37

import bitfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_auto_20200929_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseteacher',
            name='notify_by_default',
            field=models.BooleanField(default=True, help_text='Add teacher to assignment notify settings by default', verbose_name='Notify by default'),
        ),
        migrations.AlterField(
            model_name='courseteacher',
            name='roles',
            field=bitfield.models.BitField((('lecturer', 'Lecturer'), ('reviewer', 'Reviewer'), ('seminar', 'Seminarian'), ('spectator', 'Spectator')), default=1),
        ),
    ]
