# Generated by Django 3.0.9 on 2020-10-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_auto_20201007_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignees',
            field=models.ManyToManyField(blank=True, help_text='Has lower priority than student group assignees', related_name='_assignment_assignees_+', to='courses.CourseTeacher', verbose_name='Assignment Assignees'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='notify_teachers',
            field=models.ManyToManyField(blank=True, help_text='TODO: remove', to='courses.CourseTeacher', verbose_name='Legacy Field'),
        ),
    ]
