# Generated by Django 2.2.4 on 2019-08-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_auto_20190827_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_correspondence',
        ),
        migrations.AlterField(
            model_name='semester',
            name='ends_at',
            field=models.DateTimeField(editable=False, help_text='Datetime in UTC and is predefined.', verbose_name='Semester|EndsAt'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='starts_at',
            field=models.DateTimeField(editable=False, help_text='Datetime in UTC and is predefined.', verbose_name='Semester|StartsAt'),
        ),
    ]
