# Generated by Django 3.1.7 on 2021-02-27 11:58

import core.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_auto_20210211_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='notify_teachers',
        ),
        migrations.AddField(
            model_name='courseclass',
            name='time_zone',
            field=core.db.fields.TimeZoneField(verbose_name='Time Zone', null=True),
        ),
    ]
