# Generated by Django 2.2.4 on 2019-08-28 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_auto_20190828_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='city',
        ),
    ]
