# Generated by Django 3.2.7 on 2021-11-02 08:03

import bitfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_auto_20210421_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignee_mode',
            field=models.CharField(choices=[('off', 'Disabled'), ('sg', 'Student Group'), ('manual', 'Manual')], default='sg', help_text='Automatic assignment mode of a responsible teacher', max_length=12, verbose_name='Assignee mode'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='submission_type',
            field=models.CharField(choices=[('online', 'Online Submission'), ('ya.contest', 'Yandex.Contest'), ('external', 'External Service'), ('code_review', 'Code Review Submission'), ('other', 'No Submission')], max_length=42, verbose_name='Submission Type'),
        ),
        migrations.AlterField(
            model_name='course',
            name='group_mode',
            field=models.CharField(choices=[('no_groups', 'No Groups'), ('manual', 'Manual'), ('branch', 'Branch')], default='branch', help_text='Choose `Branch` to auto generate student groups from course branches.', max_length=100, verbose_name='Student Group Mode'),
        ),
        migrations.AlterField(
            model_name='courseteacher',
            name='roles',
            field=bitfield.models.BitField((('lecturer', 'Lecturer'), ('reviewer', 'Reviewer'), ('seminar', 'Seminarian'), ('spectator', 'Spectator'), ('organizer', 'Organizer')), default=1),
        ),
    ]
