# Generated by Django 3.2.9 on 2021-12-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_auto_20211102_0803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentattachment',
            options={'verbose_name': 'Assignment attachment', 'verbose_name_plural': 'Assignment attachments'},
        ),
        migrations.AddField(
            model_name='course',
            name='internal_description',
            field=models.TextField(blank=True, help_text='Visible to course listeners only. LaTeX+Markdown+HTML is enabled.', verbose_name='Internal Information'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignee_mode',
            field=models.CharField(choices=[('off', 'Without a responsible person'), ('manual', 'Choose from the list'), ('sg_default', 'Student Group - Default'), ('sg_custom', 'Student Group - Custom')], help_text='Automatic assignment mode of a responsible teacher', max_length=12, verbose_name='Assignee mode'),
        ),
        migrations.AlterField(
            model_name='course',
            name='grading_type',
            field=models.SmallIntegerField(choices=[(0, 'Default'), (1, 'Pass/Fail'), (3, 'Pass/Fail + Excellent'), (2, '10-point scale')], default=0, verbose_name='CourseOffering|grading_type'),
        ),
    ]
