# Generated by Django 3.2.9 on 2021-12-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_auto_20211215_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='contacts',
            field=models.TextField(blank=True, help_text='Visible to course listeners only. LaTeX+Markdown+HTML is enabled.', verbose_name='Contacts'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='LaTeX+Markdown+HTML is enabled', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description_en',
            field=models.TextField(blank=True, help_text='LaTeX+Markdown+HTML is enabled', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description_ru',
            field=models.TextField(blank=True, help_text='LaTeX+Markdown+HTML is enabled', null=True, verbose_name='Description'),
        ),
    ]
