# Generated by Django 3.2.13 on 2022-09-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_auto_20211229_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_visible_in_certificates',
            field=models.BooleanField(default=True, verbose_name='Do we see this course in certificates and diplomas?'),
        )
    ]
