# Generated by Django 3.2.13 on 2022-12-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0041_auto_20220927_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignee_mode',
            field=models.CharField(choices=[('off', 'Without a responsible person'), ('manual', 'Choose from the list'), ('sg_default', 'Student Group - Default'), ('sg_custom', 'Student Group - Custom'), ('sg_balance', 'Student Group - Balanced')], help_text='Automatic assignment mode of a responsible teacher', max_length=12, verbose_name='Assignee mode'),
        )
    ]
