# Generated by Django 3.2.18 on 2024-02-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0042_new_assigneemode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='submission_type',
            field=models.CharField(choices=[('online', 'Online Submission'), ('ya.contest', 'Yandex.Contest'), ('external', 'External Service'), ('code_review', 'Code Review Submission'), ('penalty', 'Penalty'), ('other', 'No Submission')], max_length=42, verbose_name='Assignment Format'),
        ),
        migrations.AlterField(
            model_name='course',
            name='group_mode',
            field=models.CharField(choices=[('no_groups', 'No Groups'), ('manual', 'Manual'), ('branch', 'Branches'), ('invite_and_branch', 'Invitations and Branches')], default='branch', help_text='Choose `Branch` to auto generate student groups from course branches.', max_length=100, verbose_name='Student Group Mode'),
        ),
        migrations.AlterField(
            model_name='course',
            name='materials_visibility',
            field=models.CharField(choices=[('public', 'All Users'), ('participants', 'All Students'), ('private', 'Course Participants')], default='private', help_text='Default visibility for class materials.', max_length=12, verbose_name='Materials Visibility'),
        ),
    ]
