# Generated by Django 3.2.18 on 2024-04-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_auto_20240227_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(choices=[('first', 'In the first half of semester'), ('second', 'In the second half of semester'), ('full', 'Full semester')], db_index=True, default='full', help_text='Duration of course', max_length=10, verbose_name='Duration'),
        ),
    ]
