# Generated by Django 3.2.18 on 2024-05-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0044_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='default_grade',
            field=models.CharField(choices=[('not_graded', 'Not graded'), ('without_grade', 'Without Grade'), ('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5'), ('six', '6'), ('seven', '7'), ('eight', '8'), ('nine', '9'), ('ten', '10'), ('unsatisfactory', 'Enrollment|Unsatisfactory'), ('pass', 'Enrollment|Pass'), ('good', 'Good'), ('excellent', 'Excellent'), ('re-credit', 'Enrollment|Re-credit')], default='not_graded', max_length=100, verbose_name='Enrollment|default_grade'),
        ),
    ]
