# Generated by Django 3.2.18 on 2024-05-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0045_course_default_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='default_grade',
            field=models.CharField(choices=[('without_grade', 'Without Grade'), ('not_graded', 'Not graded')], default='not_graded', max_length=100, verbose_name='Enrollment|default_grade'),
        ),
    ]
