# Generated by Django 3.2.18 on 2024-08-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0047_auto_20240526_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='CourseOffering|hours'),
        ),
    ]
