# Generated by Django 3.2.18 on 2024-08-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0049_auto_20240827_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseclass',
            name='is_conducted_by_invited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='course_classes', to='courses.CourseTeacher', verbose_name='Course class teachers'),
        ),
        migrations.AlterField(
            model_name='course',
            name='default_grade',
            field=models.CharField(choices=[('not_graded', 'Not graded'), ('without_grade', 'Without Grade')], default='not_graded', max_length=100, verbose_name='Enrollment|default_grade'),
        ),
    ]
