# Generated by Django 3.2.18 on 2024-09-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0050_auto_20240830_0818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='capacity',
            new_name='learners_capacity',
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='is_conducted_by_invited',
            field=models.BooleanField(default=False, verbose_name='Is conducted by invited'),
        ),
    ]
