# Generated by Django 3.2.18 on 2024-09-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0051_auto_20240903_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollment_type',
            field=models.CharField(choices=[('Regular', 'InvitationEnrollmentTypes|Regular'), ('lections', 'InvitationEnrollmentTypes|Lections'), ('Any', 'InvitationEnrollmentTypes|Any')], default='Any', max_length=100, verbose_name='Enrollment|type'),
        ),
        migrations.AddField(
            model_name='course',
            name='listeners_capacity',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 - unlimited', verbose_name='CourseOffering|listeners_capacity'),
        ),
        migrations.AddField(
            model_name='course',
            name='listeners_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='learners_capacity',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 - unlimited', verbose_name='CourseOffering|learners_capacity'),
        ),
    ]
