# Generated by Django 3.2.18 on 2025-01-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0054_auto_20241213_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereview',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='CourseReview|is_visible'),
        ),
    ]
