# Generated by Django 3.2.18 on 2025-01-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0055_coursereview_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseclass',
            name='invited_teacher_first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Invited teacher first name'),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='invited_teacher_last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Invited teacher last name'),
        ),
    ]
