# Generated by Django 3.2.18 on 2025-02-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0056_auto_20250128_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseclass',
            name='invited_teacher_first_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Invited teacher first name'),
            preserve_default=False,
        )
    ]
