# Generated by Django 3.2.18 on 2025-02-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0057_auto_20250204_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseclass',
            name='invited_teacher_last_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Invited teacher last name'),
            preserve_default=False,
        ),
    ]
