# Generated by Django 3.2.18 on 2025-03-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0058_alter_courseclass_invited_teacher_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='metacourse',
            name='index',
            field=models.SlugField(blank=True, help_text='Short unique index of course', max_length=70, null=True, unique=True, verbose_name='Course|index'),
        ),
    ]
