# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 11:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionTestApplicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('surname', models.CharField(max_length=255, verbose_name='Surname')),
                ('patronymic', models.CharField(max_length=255, verbose_name='Patronymic')),
                ('email', models.EmailField(help_text='Applicant|email', max_length=254, verbose_name='Email')),
                ('stepic_id', models.PositiveIntegerField(blank=True, help_text='Applicant|stepic_id', null=True, verbose_name='Stepik ID')),
                ('yandex_id', models.CharField(blank=True, help_text='Applicant|yandex_id', max_length=80, null=True, validators=[django.core.validators.RegexValidator(message='Only the part before "@yandex.ru" is expected', regex='^[^@]*$')], verbose_name='Yandex ID')),
                ('yandex_id_normalize', models.CharField(blank=True, help_text='Applicant|yandex_id_normalization', max_length=80, null=True, verbose_name='Yandex ID normalisation')),
                ('github_id', models.CharField(blank=True, help_text='Applicant|github_id', max_length=255, null=True, verbose_name='Github ID')),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Admission Test Applicant',
                'verbose_name_plural': 'Admission Test Applicants',
            },
        ),
    ]
