# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissiontestapplicant',
            name='yandex_id_normalize',
        ),
        migrations.AddField(
            model_name='admissiontestapplicant',
            name='participant_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Participant ID in Yandex Contest'),
        ),
    ]
