# Generated by Django 2.2.1 on 2019-06-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='csc_review',
        ),
        migrations.AlterField(
            model_name='shadcourserecord',
            name='grade',
            field=models.CharField(choices=[('not_graded', 'Not graded'), ('unsatisfactory', 'SHADCourseGrade|Unsatisfactory'), ('pass', 'SHADCourseGrade|Pass'), ('good', 'Good'), ('excellent', 'Excellent')], default='not_graded', max_length=100, verbose_name='Enrollment|grade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('o', 'Other/Prefer Not to Say')], max_length=1, verbose_name='Gender'),
        ),
    ]
