# Generated by Django 2.2.5 on 2019-09-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_academic_disciplines'),
    ]

    operations = [
        migrations.AddField(
            model_name='shadcourserecord',
            name='anytask_url',
            field=models.URLField(blank=True, null=True, verbose_name='Anytask URL'),
        ),
    ]
