# Generated by Django 2.2.5 on 2019-09-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_shadcourserecord_anytask_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shadcourserecord',
            name='anytask_url',
        ),
        migrations.AddField(
            model_name='user',
            name='anytask_url',
            field=models.URLField(blank=True, null=True, verbose_name='Anytask URL'),
        ),
    ]
