# Generated by Django 2.2.6 on 2019-10-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190923_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='diploma_number',
            field=models.CharField(blank=True, help_text='Number of higher education diploma', max_length=64, verbose_name='Diploma Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='official_student',
            field=models.BooleanField(default=False, help_text='Passport, consent for processing personal data, diploma (optional)', verbose_name='Official Student'),
        ),
    ]
