# Generated by Django 2.2.10 on 2020-02-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191010_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('expelled', 'StudentInfo|Expelled'), ('academic', 'StudentStatus|Academic leave'), ('reinstated', 'StudentInfo|Reinstalled'), ('will_graduate', 'StudentInfo|Will graduate')], help_text='Status|HelpText', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='userstatuslog',
            name='status',
            field=models.CharField(choices=[('expelled', 'StudentInfo|Expelled'), ('academic', 'StudentStatus|Academic leave'), ('reinstated', 'StudentInfo|Reinstalled'), ('will_graduate', 'StudentInfo|Will graduate')], max_length=15, verbose_name='Status'),
        ),
    ]
