# Generated by Django 2.2.10 on 2020-04-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200211_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatuslog',
            name='semester',
        ),
    ]
