# Generated by Django 2.2.3 on 2019-07-03 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('users', '0006_auto_20190703_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.PositiveSmallIntegerField(choices=[(1, 'Student [CENTER]'), (2, 'Teacher [CENTER]'), (3, 'Graduate'), (4, 'Volunteer'), (5, 'Student [CLUB]'), (6, 'Teacher [CLUB]'), (7, 'Interviewer [Admission]'), (8, 'Studying for a master degree'), (9, 'Project reviewer'), (10, 'Curator of projects')], verbose_name='Role')),
                ('site', models.ForeignKey(db_index=False, default=users.models.get_current_site, on_delete=django.db.models.deletion.PROTECT, to='sites.Site', verbose_name='Site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_new', related_query_name='group_new', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Access Group',
                'verbose_name_plural': 'Access Groups',
                'db_table': 'users_user_groups2',
            },
        ),
        migrations.AddConstraint(
            model_name='usergroup',
            constraint=models.UniqueConstraint(fields=('user', 'group', 'site'), name='unique_user_group_site'),
        ),
    ]
