# Generated by Django 2.2.3 on 2019-07-03 13:34

from django.db import migrations

from users.constants import AcademicRoles


def migrate_groups(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Group = apps.get_model('users', 'Group')
    UserGroup = apps.get_model('users', 'UserGroup')
    for user in User.objects.all():
        for group in user.groups.all():
            site = 1
            # 5, 6 == AcademicRoles.STUDENT_CLUB, AcademicRoles.TEACHER_CLUB
            if group.pk in (5, 6):
                site = 2
            user.groups_new.add(UserGroup(user=user, site_id=site, group=group.pk), bulk=False)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190703_1333'),
    ]

    operations = [
        migrations.RunPython(migrate_groups)
    ]
