# Generated by Django 2.2.10 on 2020-04-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_userstatuslog_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinecourserecord',
            name='url',
            field=models.URLField(blank=True, verbose_name='Online Course URL'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('expelled', 'StudentInfo|Expelled'), ('academic', 'StudentStatus|Academic leave'), ('reinstated', 'StudentInfo|Reinstalled'), ('will_graduate', 'StudentInfo|Will graduate')], max_length=15, verbose_name='Status'),
        ),
    ]
