# Generated by Django 2.2.10 on 2020-05-14 17:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200514_1750'),
        ('sites', '0002_alter_domain_unique'),
        ('study_programs', '0001_initial'),
        ('users', '0008_auto_20200424_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('regular', 'Regular Student'), ('volunteer', 'Volunteer'), ('invited', 'Invited Student')], max_length=10, verbose_name='Type')),
                ('priority', models.PositiveIntegerField(editable=False, verbose_name='Priority')),
                ('status', models.CharField(blank=True, choices=[('expelled', 'StudentInfo|Expelled'), ('academic', 'StudentStatus|Academic leave'), ('reinstated', 'StudentInfo|Reinstalled'), ('will_graduate', 'StudentInfo|Will graduate')], max_length=15, verbose_name='Status')),
                ('year_of_admission', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1990)], verbose_name='Student|admission year')),
                ('year_of_curriculum', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2000)], verbose_name='CSCUser|Curriculum year')),
                ('university', models.CharField(blank=True, max_length=255, verbose_name='University')),
                ('level_of_education_on_admission', models.CharField(blank=True, choices=[('1', '1 course bachelor, speciality'), ('2', '2 course bachelor, speciality'), ('3', '3 course bachelor, speciality'), ('4', '4 course bachelor, speciality'), ('5', 'last course speciality'), ('6', '1 course magistracy'), ('7', '2 course magistracy'), ('8', 'postgraduate'), ('9', 'graduate')], help_text='at enrollment', max_length=2, null=True, verbose_name='StudentInfo|University year')),
                ('is_official_student', models.BooleanField(default=False, help_text='Passport, consent for processing personal data, diploma (optional)', verbose_name='Official Student')),
                ('diploma_number', models.CharField(blank=True, help_text='Number of higher education diploma', max_length=64, verbose_name='Diploma Number')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('comment_changed_at', model_utils.fields.MonitorField(blank=True, default=None, monitor='comment', null=True, verbose_name='Comment changed')),
                ('academic_disciplines', models.ManyToManyField(blank=True, help_text='Academic disciplines from which student plans to graduate', to='study_programs.AcademicDiscipline', verbose_name='Fields of study')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Branch', verbose_name='Branch')),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'db_table': 'student_profiles',
            },
        ),
        migrations.AddField(
            model_name='usergroup',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Student'), (2, 'Teacher'), (3, 'Graduate'), (4, 'Co-worker'), (5, 'Curator'), (7, 'Interviewer [Admission]'), (8, 'Studying for a master degree'), (9, 'Project reviewer'), (10, 'Curator of projects'), (11, 'Invited User')], verbose_name='Role'),
        ),
        migrations.CreateModel(
            name='StudentStatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Created')),
                ('status_changed_at', models.DateField(default=django.utils.timezone.now, verbose_name='Entry Added')),
                ('status', models.CharField(choices=[('expelled', 'StudentInfo|Expelled'), ('academic', 'StudentStatus|Academic leave'), ('reinstated', 'StudentInfo|Reinstalled'), ('will_graduate', 'StudentInfo|Will graduate')], max_length=15, verbose_name='Status')),
                ('entry_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.StudentProfile', verbose_name='Student')),
            ],
            options={
                'verbose_name_plural': 'Student Status Log',
                'ordering': ['-pk'],
            },
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='comment_last_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Author of last edit'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='site',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='sites.Site', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.UniqueConstraint(fields=('user', 'branch', 'year_of_admission'), name='unique_student_per_branch_per_admission_campaign'),
        ),
    ]
