# Generated by Django 2.2.10 on 2020-05-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200514_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status_last_change',
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Student'), (2, 'Teacher'), (3, 'Graduate'), (4, 'Co-worker'), (5, 'Curator'), (7, 'Interviewer [Admission]'), (9, 'Project reviewer'), (10, 'Curator of projects'), (11, 'Invited User')], verbose_name='Role'),
        ),
        migrations.DeleteModel(
            name='UserStatusLog',
        ),
    ]
