# Generated by Django 2.2.3 on 2019-07-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_groups'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usergroup',
            table='users_user_groups',
        ),
    ]
