# Generated by Django 2.2.10 on 2020-05-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200520_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='diploma_issued_by',
            field=models.CharField(blank=True, max_length=255, verbose_name='Issued by'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='diploma_issued_on',
            field=models.DateField(blank=True, null=True, verbose_name='Issued on'),
        ),
    ]
