# Generated by Django 2.2.10 on 2020-05-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200522_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='diploma_issued_by',
            field=models.CharField(blank=True, max_length=255, verbose_name='Diploma Issued by'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='diploma_issued_on',
            field=models.DateField(blank=True, null=True, verbose_name='Diploma Issued on'),
        ),
    ]
