# Generated by Django 2.2.3 on 2019-07-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190703_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'CSCUser|user', 'verbose_name_plural': 'CSCUser|users'},
        ),
        migrations.RemoveConstraint(
            model_name='usergroup',
            name='unique_user_group_site',
        ),
        migrations.AddConstraint(
            model_name='usergroup',
            constraint=models.UniqueConstraint(fields=('user', 'role', 'site'), name='unique_user_role_site'),
        ),
    ]
