# Generated by Django 2.2.3 on 2019-07-27 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0019_remove_enrollmentinvitation_expire_at'),
        ('users', '0013_auto_20190704_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='learning.Branch', to_field='code', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Student'), (2, 'Teacher'), (3, 'Graduate'), (4, 'Volunteer'), (5, 'Curator'), (7, 'Interviewer [Admission]'), (8, 'Studying for a master degree'), (9, 'Project reviewer'), (10, 'Curator of projects'), (11, 'Invited User')], verbose_name='Role'),
        ),
    ]
