# Generated by Django 2.2.10 on 2020-05-25 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200525_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmentcertificate',
            name='student',
        ),
    ]
