# Generated by Django 2.2.3 on 2019-07-27 18:13

from django.db import migrations


def copy_branch(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for sp in User.objects.select_related('branch'):
        if sp.branch_id:
            sp.branch_new_id = sp.branch.code
            sp.save(update_fields=['branch_new_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190727_1812'),
    ]

    operations = [
        migrations.RunPython(copy_branch)
    ]
