# Generated by Django 2.2.10 on 2020-05-25 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_enrollmentcertificate_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnrollmentCertificate',
            new_name='CertificateOfParticipation',
        ),
    ]
