# Generated by Django 2.2.3 on 2019-07-27 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190727_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='branch',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='branch_new',
            new_name='branch',
        ),
    ]
