# Generated by Django 2.2.10 on 2020-05-26 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200525_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='academic_disciplines',
        ),
        migrations.RemoveField(
            model_name='user',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='comment_changed_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='comment_last_author',
        ),
        migrations.RemoveField(
            model_name='user',
            name='diploma_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='enrollment_year',
        ),
        migrations.RemoveField(
            model_name='user',
            name='official_student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uni_year_at_enrollment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='university',
        ),
    ]
