# Generated by Django 2.2.13 on 2020-07-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200526_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_zone',
            field=models.CharField(choices=[('Europe/Kiev', 'Europe/Kiev'), ('Europe/Moscow', 'Europe/Moscow'), ('Europe/Minsk', 'Europe/Minsk'), ('Asia/Yekaterinburg', 'Asia/Yekaterinburg'), ('Asia/Novosibirsk', 'Asia/Novosibirsk')], default='Europe/Moscow', max_length=63, verbose_name='Timezone'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='academic_disciplines',
            field=models.ManyToManyField(blank=True, to='study_programs.AcademicDiscipline', verbose_name='Fields of study'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='level_of_education_on_admission',
            field=models.CharField(blank=True, choices=[('1', '1 course bachelor, speciality'), ('2', '2 course bachelor, speciality'), ('3', '3 course bachelor, speciality'), ('4', '4 course bachelor, speciality'), ('5', 'last course speciality'), ('6', '1 course magistracy'), ('7', '2 course magistracy'), ('8', 'postgraduate'), ('9', 'graduate')], max_length=2, null=True, verbose_name='StudentInfo|University year'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('expelled', 'StudentInfo|Expelled'), ('academic', 'StudentStatus|Academic leave'), ('reinstated', 'StudentInfo|Reinstalled'), ('will_graduate', 'StudentInfo|Will graduate'), ('graduate', 'StudentInfo|Graduate')], max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='type',
            field=models.CharField(choices=[('regular', 'Regular Student'), ('volunteer', 'Co-worker'), ('invited', 'Invited Student')], max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='studentstatuslog',
            name='status',
            field=models.CharField(choices=[('expelled', 'StudentInfo|Expelled'), ('academic', 'StudentStatus|Academic leave'), ('reinstated', 'StudentInfo|Reinstalled'), ('will_graduate', 'StudentInfo|Will graduate'), ('graduate', 'StudentInfo|Graduate')], max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('expelled', 'StudentInfo|Expelled'), ('academic', 'StudentStatus|Academic leave'), ('reinstated', 'StudentInfo|Reinstalled'), ('will_graduate', 'StudentInfo|Will graduate'), ('graduate', 'StudentInfo|Graduate')], max_length=15, verbose_name='Status'),
        ),
    ]
