# Generated by Django 2.2.13 on 2020-08-04 11:27

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200728_1046'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentprofile',
            name='unique_student_per_branch_per_admission_campaign',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.UniqueConstraint(condition=models.Q(type='regular'), fields=('user', 'branch', 'year_of_admission'), name='unique_student_per_branch_per_admission_campaign'),
        ),
    ]
