# Generated by Django 2.2.4 on 2019-08-14 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20190814_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='branch',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='branch_new2',
            new_name='branch',
        ),
    ]
