# Generated by Django 2.2.13 on 2020-08-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200804_1127'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentprofile',
            name='unique_student_per_branch_per_admission_campaign',
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.UniqueConstraint(condition=models.Q(type='regular'), fields=('user', 'branch', 'year_of_admission'), name='unique_regular_student_per_admission_campaign'),
        ),
    ]
