# Generated by Django 2.2.13 on 2020-08-04 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0020_auto_20200625_2102'),
        ('users', '0020_auto_20200804_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='invitation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to='learning.Invitation', verbose_name='Invitation'),
        ),
    ]
