# Generated by Django 2.2.4 on 2019-08-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20190822_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_networks',
            field=models.TextField(blank=True, help_text='доступны LaTeX и Markdown; will be shown only to curators only', null=True, verbose_name='Social Networks'),
        ),
    ]
