# Generated by Django 2.2.4 on 2019-08-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_social_networks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='areas_of_study',
        ),
        migrations.AlterField(
            model_name='user',
            name='social_networks',
            field=models.TextField(blank=True, help_text='доступны LaTeX и Markdown; будут показаны только кураторам', null=True, verbose_name='Social Networks'),
        ),
    ]
