# Generated by Django 2.2.4 on 2019-08-28 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20190828_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='yandex_id',
            new_name='yandex_login',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='github_id',
            new_name='github_login',
        ),
    ]
