# Generated by Django 3.0.9 on 2020-09-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20200902_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='calendar_key',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
