# Generated by Django 2.2.4 on 2019-08-28 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20190828_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github_login',
            field=models.CharField(blank=True, max_length=80, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9](-?[a-zA-Z0-9])*$')], verbose_name='Github Login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='yandex_login',
            field=models.CharField(blank=True, max_length=80, verbose_name='Yandex Login'),
        ),
    ]
