# Generated by Django 3.1.7 on 2021-02-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20210220_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cropbox_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
