# Generated by Django 2.2.4 on 2019-08-28 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20190828_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='graduation_year',
        ),
    ]
