# Generated by Django 2.2.4 on 2019-08-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_remove_user_graduation_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
    ]
