# Generated by Django 3.1.7 on 2021-04-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20210302_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='curriculum_year',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year_of_admission',
            field=models.PositiveSmallIntegerField(verbose_name='Student|admission year'),
        ),
    ]
