# Generated by Django 3.2.6 on 2021-08-30 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20210413_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Partner Tag',
                'verbose_name_plural': 'Partner Tags',
            },
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('expelled', 'StudentInfo|Expelled'), ('academic', 'StudentStatus|Academic leave'), ('academic_2', 'Second academic leave'), ('reinstated', 'StudentInfo|Reinstalled'), ('will_graduate', 'StudentInfo|Will graduate'), ('graduate', 'StudentInfo|Graduate')], max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='type',
            field=models.CharField(choices=[('regular', 'Regular Student'), ('volunteer', 'Co-worker'), ('invited', 'Invited Student'), ('partner', "Master's Degree Student")], max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='studentstatuslog',
            name='status',
            field=models.CharField(choices=[('expelled', 'StudentInfo|Expelled'), ('academic', 'StudentStatus|Academic leave'), ('academic_2', 'Second academic leave'), ('reinstated', 'StudentInfo|Reinstalled'), ('will_graduate', 'StudentInfo|Will graduate'), ('graduate', 'StudentInfo|Graduate')], max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='studentstatuslog',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='users.studentprofile', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('expelled', 'StudentInfo|Expelled'), ('academic', 'StudentStatus|Academic leave'), ('academic_2', 'Second academic leave'), ('reinstated', 'StudentInfo|Reinstalled'), ('will_graduate', 'StudentInfo|Will graduate'), ('graduate', 'StudentInfo|Graduate')], max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Student'), (2, 'Teacher'), (3, 'Graduate'), (4, 'Co-worker'), (5, 'Curator'), (7, 'Interviewer [Admission]'), (9, 'Project reviewer'), (10, 'Curator of projects'), (11, 'Invited User'), (12, 'Service User'), (13, "Master's Degree Student")], verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to='users.partnertag', verbose_name='Magistracy'),
        ),
    ]
