# Generated by Django 3.2.7 on 2021-09-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20210830_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_suspension_details',
            field=models.JSONField(blank=True, editable=False, null=True, verbose_name='Email Address Suspension Details'),
        ),
    ]
