# Generated by Django 3.2.7 on 2021-09-28 11:05

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_user_email_suspension_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentstatuslog',
            name='modified_at',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='studentstatuslog',
            name='created_at',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
    ]
