# Generated by Django 3.2.9 on 2021-11-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20210928_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_paid_basis',
            field=models.BooleanField(default=False, verbose_name='Paid Basis'),
        ),
    ]
