# Generated by Django 3.2.9 on 2021-11-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_studentprofile_is_paid_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='yandex_login_normalized',
            field=models.CharField(blank=True, editable=False, max_length=80),
        ),
    ]
