# Generated by Django 3.2.12 on 2022-08-08 13:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_remove_studentprofile_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(regex='^(?!.*__.*)[a-z A-Z]\\w{3,30}[a-zA-Z0-9]$')], verbose_name='Telegram'),
        )
    ]
