# Generated by Django 3.2.13 on 2022-10-11 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0041_invitation_student_profile_relation'),
        ('users', '0037_add_telegram_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='invitation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='learning.invitation', verbose_name='Invitation'),
        ),
    ]
