# Generated by Django 3.2.13 on 2022-11-23 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_studentprofile_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='YandexUserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('login', models.CharField(blank=True, max_length=64, verbose_name='Yandex Login')),
                ('uid', models.CharField(max_length=64, unique=True, verbose_name='Yandex UID')),
                ('first_name', models.CharField(blank=True, max_length=64, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=64, verbose_name='last name')),
                ('display_name', models.CharField(blank=True, max_length=130, verbose_name='Display Name')),
                ('real_name', models.CharField(blank=True, max_length=130, verbose_name='Real name')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Changed by')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yandex_data', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Data from Yandex.ID',
            },
        ),
    ]
