# Generated by Django 3.2.18 on 2024-02-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_yandexuserdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_notification_allowed',
            field=models.BooleanField(default=True, help_text='Designates that this user enabled email notifications ', verbose_name='notification permission status'),
        ),
    ]
