# Generated by Django 3.2.18 on 2024-03-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_user_is_notification_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='level_of_education_on_admission',
            field=models.CharField(blank=True, choices=[('1', '1 course bachelor, speciality'), ('2', '2 course bachelor, speciality'), ('3', '3 course bachelor, speciality'), ('4', '4 course bachelor, speciality'), ('5', '5 course speciality'), ('6', '6 course speciality'), ('7', '1 course magistracy'), ('8', '2 course magistracy'), ('9', 'postgraduate'), ('10', 'academic_leave'), ('other', 'Other')], max_length=12, null=True, verbose_name='StudentInfo|University year'),
        ),
    ]
