# Generated by Django 3.2.18 on 2024-06-12 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_alter_studentprofile_level_of_education_on_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='graduation_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Passport, consent for processing personal data, diploma (optional)', null=True, validators=[django.core.validators.MinValueValidator(2000)], verbose_name='StudentProfile|graduation_year'),
        ),
    ]
