# Generated by Django 3.2.18 on 2024-07-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20240720_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gave_permission_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Permission time'),
        ),
    ]
