# Generated by Django 3.2.18 on 2024-08-10 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('study_programs', '0003_auto_20210322_1705'),
        ('users', '0044_user_gave_permission_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentstatuslog',
            old_name='status_changed_at',
            new_name='changed_at',
        ),
        migrations.AddField(
            model_name='studentstatuslog',
            name='former_status',
            field=models.CharField(blank=True, choices=[('expelled', 'StudentInfo|Expelled'), ('academic', 'StudentStatus|Academic leave'), ('academic_2', 'Second academic leave'), ('reinstated', 'StudentInfo|Reinstalled'), ('will_graduate', 'StudentInfo|Will graduate'), ('graduate', 'StudentInfo|Graduate')], max_length=15, verbose_name='Former status'),
        ),
        migrations.AddField(
            model_name='studentstatuslog',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='Designates whether this Log was processed in document list', verbose_name='Is processed'),
        ),
        migrations.AddField(
            model_name='studentstatuslog',
            name='processed_at',
            field=models.DateField(blank=True, null=True, verbose_name='Processed time'),
        ),
        migrations.AlterField(
            model_name='studentstatuslog',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentstatuslog_related', to='users.studentprofile', verbose_name='Student'),
        ),
        migrations.CreateModel(
            name='StudentAcademicDisciplineLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('changed_at', models.DateField(default=django.utils.timezone.now, verbose_name='Entry Added')),
                ('is_processed', models.BooleanField(default=False, help_text='Designates whether this Log was processed in document list', verbose_name='Is processed')),
                ('processed_at', models.DateField(blank=True, null=True, verbose_name='Processed time')),
                ('academic_discipline', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='study_programs.academicdiscipline', verbose_name='Field of study')),
                ('entry_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('former_academic_discipline', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='study_programs.academicdiscipline', verbose_name='Former field of study')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentacademicdisciplinelog_related', to='users.studentprofile', verbose_name='Student')),
            ],
            options={
                'verbose_name_plural': 'Student Academic Discipline Log',
            },
        ),
    ]
