# Generated by Django 3.2.18 on 2024-08-12 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_programs', '0003_auto_20210322_1705'),
        ('users', '0045_auto_20240810_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentacademicdisciplinelog',
            name='academic_discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='study_programs.academicdiscipline', verbose_name='Field of study'),
        ),
        migrations.AlterField(
            model_name='studentacademicdisciplinelog',
            name='former_academic_discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='study_programs.academicdiscipline', verbose_name='Former field of study'),
        ),
    ]
