# Generated by Django 3.2.18 on 2024-08-30 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_auto_20240812_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentacademicdisciplinelog',
            options={'ordering': ['-changed_at', '-pk'], 'verbose_name_plural': 'Student Academic Discipline Log'},
        ),
        migrations.AlterModelOptions(
            name='studentstatuslog',
            options={'ordering': ['-changed_at', '-pk'], 'verbose_name_plural': 'Student Status Log'},
        ),
    ]
