# Generated by Django 3.2.18 on 2024-11-28 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0055_alter_enrollment_is_grade_recredited'),
        ('users', '0048_studentprofile_snils'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='badge_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Badge number'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='learning.invitation', verbose_name='Invitation'),
        ),
    ]
