# Generated by Django 3.2.18 on 2025-02-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_auto_20241128_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tshirt_size',
            field=models.CharField(choices=[('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=4, null=True, verbose_name='T-Shirt size'),
        ),
    ]
