# Generated by Django 3.2.18 on 2025-01-22 11:07

from django.db import migrations

from users.constants import ConsentTypes

def create_user_consents(apps, schema_editor):
    User = apps.get_model('users', 'User')
    UserConsent = apps.get_model('users', 'UserConsent')

    for user in User.objects.filter(gave_permission_at__isnull=False):
        for consent_type in ConsentTypes.regular_student_consents:
            UserConsent.objects.create(
                user=user,
                type=consent_type,
                created=user.gave_permission_at
            )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_userconsent'),
    ]

    operations = [
        migrations.RunPython(create_user_consents)
    ]
