# Generated by Django 3.2.18 on 2025-01-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_auto_20250122_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gave_permission_at',
        ),
    ]
