# Generated by Django 3.2.18 on 2025-02-04 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_user_tshirt_size'),
        ('users', '0052_remove_user_gave_permission_at'),
    ]

    operations = [
    ]
