# Generated by Django 3.2.18 on 2025-03-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_user_tshirt_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='yandex_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='yandex_login_normalized',
        ),
        migrations.AlterField(
            model_name='yandexuserdata',
            name='uid',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Yandex UID'),
        ),
    ]
