# Generated by Django 3.2.18 on 2025-04-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_auto_20250330_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yandexuserdata',
            name='display_name',
            field=models.CharField(max_length=130, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='yandexuserdata',
            name='first_name',
            field=models.CharField(max_length=64, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='yandexuserdata',
            name='last_name',
            field=models.CharField(max_length=64, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='yandexuserdata',
            name='login',
            field=models.CharField(max_length=64, verbose_name='Yandex Login'),
        ),
        migrations.AlterField(
            model_name='yandexuserdata',
            name='real_name',
            field=models.CharField(max_length=130, verbose_name='Real name'),
        ),
        migrations.AlterField(
            model_name='yandexuserdata',
            name='uid',
            field=models.CharField(default='', max_length=64, unique=True, verbose_name='Yandex UID'),
            preserve_default=False,
        ),
    ]
