# Generated by Django 3.2.18 on 2025-04-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_auto_20250402_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='citizenship',
            field=models.CharField(blank=True, help_text='Citizenship code in OKSM system', max_length=3, verbose_name='User citizenship'),
        ),
    ]
