# Generated by Django 2.1.1 on 2018-10-29 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cscuser',
            table='users_user',
        ),
    ]
