# Generated by Django 2.1.3 on 2018-12-26 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='note',
            new_name='bio',
        ),
    ]
