# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-30 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_squashed_0005_auto_20180730_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cscuser',
            name='city',
            field=models.ForeignKey(blank=True, help_text='CSCUser|city', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.City', verbose_name='Default city'),
        ),
    ]
