# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-14 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170414_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cscuserstatuslog',
            options={'ordering': ['-pk']},
        ),
        migrations.RenameField(
            model_name='cscuser',
            old_name='status_changed_at',
            new_name='status_last_change',
        ),
    ]
