# Generated by Django 2.1.5 on 2019-01-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181226_0804'),
        ('learning', '0005_delete_internationalschool'),
    ]

    state_operations = [
        migrations.RemoveField('User', 'areas_of_study'),
    ]

    operations = [
      migrations.SeparateDatabaseAndState(
        state_operations=state_operations)
    ]