# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 13:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_cscuser_photo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cscuser',
            name='status_changed_at',
            field=users.models.MonitorFKField(blank=True, help_text='Укажите, если хотите, чтобы при изменении поля status в логе появилась запись со значением, отличным от значения по-умолчанию.', log_class=users.models.CSCUserStatusLog, monitor='status', null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.Semester', verbose_name='Status changed'),
        ),
        migrations.AlterField(
            model_name='cscuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username'),
        ),
    ]
