# Generated by Django 2.1.1 on 2018-10-29 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181029_1220'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CSCUserReference',
            new_name='UserReference',
        ),
    ]
