# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-18 12:39
from __future__ import unicode_literals

import django.core.validators
from django.contrib.auth import get_user_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160714_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='cscuser',
            name='curriculum_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2000)], verbose_name='CSCUser|Curriculum year'),
        ),
        migrations.AlterField(
            model_name='cscuser',
            name='comment',
            field=models.TextField(blank=True, help_text='How to style text read <a href="/commenting-the-right-way/" target="_blank">here</a>.', verbose_name='Comment'),
        ),
    ]
