# Generated by Django 2.1.1 on 2018-10-29 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_auto_20181019_1339'),
        ('users', '0003_auto_20181029_1227'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CSCUserStatusLog',
            new_name='UserStatusLog',
        ),
    ]
