# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170414_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='cscuser',
            name='index_redirect',
            field=models.CharField(blank=True, max_length=200, verbose_name='Index Redirect Option'),
        ),
        migrations.AlterField(
            model_name='cscuser',
            name='stepic_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='stepik.org ID'),
        ),
    ]
