# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-30 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180313_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cscuser',
            name='index_redirect',
            field=models.CharField(blank=True, choices=[('projects', 'Проекты'), ('admission', 'Набор'), ('learning', 'Обучение'), ('teaching', 'Преподавание'), ('staff', 'Курирование')], max_length=200, verbose_name='Index Redirect Option'),
        ),
    ]
