# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-20 15:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0031_auto_20170220_1859'),
        ('users', '0004_add_curriculum_year'),
    ]

    operations = [
        migrations.RenameField('CSCUser', 'study_programs', 'areas_of_study'),
        migrations.AlterField(
            model_name='cscuser',
            name='github_id',
            field=models.CharField(blank=True, max_length=80, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9](-?[a-zA-Z0-9])*[a-zA-Z0-9]$')], verbose_name='Github ID'),
        ),
    ]
