# Generated by Django 2.1.1 on 2018-10-31 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_auto_20181029_1255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserReference',
            new_name='EnrollmentCertificate',
        ),
        migrations.AlterField(
            model_name='enrollmentcertificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='enrollment_certificates',
                                    to=settings.AUTH_USER_MODEL,
                                    verbose_name='Student'),
        ),
    ]
