# Generated by Django 2.1.1 on 2018-11-06 19:41

import django.db
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181031_0910'),
        ('learning', '0021_auto_20181106_1828'),
    ]

    state_operations = [
        migrations.AlterField(
            model_name='shadcourserecord',
            name='grade',
            field=models.CharField(choices=[('not_graded', 'Not graded'), (
            'unsatisfactory', 'Enrollment|Unsatisfactory'),
                                            ('pass', 'Enrollment|Pass'),
                                            ('good', 'Good'),
                                            ('excellent', 'Excellent')],
                                   default='not_graded', max_length=100,
                                   verbose_name='Enrollment|grade'),
        ),
        migrations.AlterField(
            model_name='SHADCourseRecord',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.Semester', verbose_name='Semester')
        ),
        migrations.AlterField(
            model_name='userstatuslog',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Semester', verbose_name='Semester'),
        ),
    ]

    operations = [
      migrations.SeparateDatabaseAndState(
        state_operations=state_operations)
    ]