# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-28 08:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170220_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cscuser',
            old_name='photo_data',
            new_name='cropbox_data',
        ),
        migrations.AlterField(
            model_name='cscuser',
            name='areas_of_study',
            field=models.ManyToManyField(blank=True, to='learning.AreaOfStudy', verbose_name='StudentInfo|Areas of study'),
        ),
        migrations.AlterField(
            model_name='cscuser',
            name='github_id',
            field=models.CharField(blank=True, max_length=80, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9](-?[a-zA-Z0-9])*$')], verbose_name='Github ID'),
        ),
    ]
