# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-28 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170322_1513'),
        ('users', '0006_auto_20170328_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='cscuser',
            name='city',
            field=models.ForeignKey(default='spb', on_delete=django.db.models.deletion.CASCADE, to='core.City', verbose_name='Default city'),
            preserve_default=False,
        ),
    ]
