# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-29 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_cscuser_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cscuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.City', verbose_name='Default city'),
        ),
    ]
