# Generated by Django 3.2.9 on 2021-11-29 13:33

from django.db import migrations, models
import social_django.storage


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailValidationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(db_index=True, max_length=32)),
                ('verified', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'auth_social_email_validation',
            },
            bases=(social_django.storage.DjangoCodeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OpenIDAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_url', models.CharField(max_length=255)),
                ('handle', models.CharField(max_length=255)),
                ('secret', models.CharField(max_length=255)),
                ('issued', models.IntegerField()),
                ('lifetime', models.IntegerField()),
                ('assoc_type', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'auth_social_openid_associations',
            },
            bases=(social_django.storage.DjangoAssociationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OpenIDNonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_url', models.CharField(max_length=255)),
                ('timestamp', models.IntegerField()),
                ('salt', models.CharField(max_length=65)),
            ],
            options={
                'db_table': 'auth_social_openid_nonces',
            },
            bases=(social_django.storage.DjangoNonceMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Partial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=32)),
                ('next_step', models.PositiveSmallIntegerField(default=0)),
                ('backend', models.CharField(max_length=32)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'auth_social_partial',
            },
            bases=(social_django.storage.DjangoPartialMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='openidnonce',
            constraint=models.UniqueConstraint(fields=('server_url', 'timestamp', 'salt'), name='unique_salt_per_timestamp_per_server_url'),
        ),
        migrations.AddConstraint(
            model_name='openidassociation',
            constraint=models.UniqueConstraint(fields=('server_url', 'handle'), name='unique_handle_per_server_url'),
        ),
        migrations.AddConstraint(
            model_name='emailvalidationcode',
            constraint=models.UniqueConstraint(fields=('email', 'code'), name='unique_code_per_email'),
        ),
    ]
