---
certbot_auto_renew: yes
certbot_script: /opt/certbot-auto
certbot_required_vars:
  - certbot_acme_challenge_user
  - certbot_admin_email
  - certbot_domains
  - certbot_config_dir
  - certbot_webroot_path

