lvm_packages: [ 'lvm2' ]
lvm_global_use_lvmetad: '1'
lvm_devices_filter: [ 'a|sd.*|', 'a|vd.*|', 'a|drbd.*|', 'r|.*|' ]
lvm_devices_global_filter: '{{ lvm_devices_filter }}'
lvm_default_fs_type: 'ext4'
lvm_default_mount_options: 'defaults'
lvm_volume_groups: []
lvm_logical_volumes: []