# Generated by Django 3.0.9 on 2020-09-15 16:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('type', models.CharField(choices=[('ya', 'Yandex.Contest')], max_length=42, verbose_name='Type')),
                ('settings', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Contest id, problem id, etc', verbose_name='Details')),
            ],
            options={
                'verbose_name': 'Checking System',
                'verbose_name_plural': 'Checking Systems',
            },
        ),
    ]
