# Generated by Django 3.0.9 on 2020-09-15 18:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0026_assignmentcomment_execution_time'),
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(1, 'New'), (20, 'Not Submitted'), (30, 'Checking'), (40, 'Wrong Answer'), (50, 'Correct Answer')], verbose_name='Status')),
                ('settings', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Selected compiler, etc', verbose_name='Settings')),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Returned submission id or error details', verbose_name='Meta')),
                ('assignment_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='learning.AssignmentComment', verbose_name='Assignment Comment')),
                ('checking_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.CheckingSystem', verbose_name='Checking System')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
            },
        ),
    ]
