# Generated by Django 3.0.9 on 2020-09-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='type',
            field=models.CharField(choices=[('code', 'code')], default='code', max_length=16, verbose_name='Submission Type'),
            preserve_default=False,
        ),
    ]
