# Generated by Django 3.0.9 on 2020-09-16 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0028_remove_assignmentcomment_submission'),
        ('contests', '0003_submission_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='checking_system',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='type',
        ),
        migrations.AlterField(
            model_name='submission',
            name='assignment_comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='learning.AssignmentComment'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (20, 'Not Submitted'), (30, 'Checking'), (40, 'Wrong Answer'), (50, 'Correct Answer')], default=1, verbose_name='Status'),
        ),
    ]
