# Generated by Django 3.0.9 on 2020-09-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_auto_20200916_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkingsystem',
            name='url',
            field=models.URLField(blank=True, verbose_name='Checking System URL'),
        ),
        migrations.AlterField(
            model_name='checkingsystem',
            name='type',
            field=models.CharField(choices=[('ya', 'Yandex.Contest')], max_length=42, verbose_name='Checking System Type'),
        ),
    ]
