# Generated by Django 3.0.9 on 2020-09-18 10:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0028_remove_assignmentcomment_submission'),
        ('contests', '0005_auto_20200916_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkingsystem',
            name='url',
        ),
        migrations.AddField(
            model_name='checkingsystem',
            name='description',
            field=models.TextField(blank=True, verbose_name='What can it be used for?'),
        ),
        migrations.AddField(
            model_name='checkingsystem',
            name='name',
            field=models.CharField(max_length=80, verbose_name='CheckingSystem|Name'),
        ),
        migrations.AlterField(
            model_name='checkingsystem',
            name='settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Access token, etc', verbose_name='CheckingSystem|Details'),
        ),
        migrations.AlterField(
            model_name='checkingsystem',
            name='type',
            field=models.CharField(choices=[('ya', 'Yandex.Contest')], max_length=42, verbose_name='CheckingSystem|Type'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='assignment_comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='learning.AssignmentComment', verbose_name='Assignment Submission'),
        ),
        migrations.CreateModel(
            name='Checker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Contest id, problem id, etc', verbose_name='Checker|Settings')),
                ('checking_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.CheckingSystem', verbose_name='Checking System')),
            ],
            options={
                'verbose_name': 'Checker',
                'verbose_name_plural': 'Checkers',
            },
        ),
    ]
