# Generated by Django 3.0.9 on 2020-09-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_auto_20200918_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='checker',
            name='url',
            field=models.URLField(blank=True, verbose_name='Checker|URL'),
        ),
    ]
