# Generated by Django 3.0.9 on 2020-09-22 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_checker_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='assignment_comment',
            new_name='assignment_submission',
        ),
    ]
