from learning.settings import PARTICIPANT_GROUPS

GROUPS_IMPORT_TO_GERRIT = [
    PARTICIPANT_GROUPS.STUDENT_CENTER,
    PARTICIPANT_GROUPS.VOLUNTEER,
    PARTICIPANT_GROUPS.TEACHER_CENTER,
    PARTICIPANT_GROUPS.GRADUATE_CENTER
]