# Generated by Django 2.2.4 on 2019-08-30 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
        ('courses', '0002_auto_20190830_0814'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='album',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_of', to='gallery.Image', verbose_name='Head'),
        ),
        migrations.AddField(
            model_name='album',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Parent album', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='gallery.Album', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='album',
            name='semester',
            field=models.ForeignKey(blank=True, help_text='Set semester for album and all uploaded images will inherit it.', null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Semester', verbose_name='Semester'),
        ),
    ]
