# Generated by Django 2.2.4 on 2019-08-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20190109_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
