# Generated by Django 2.2.10 on 2020-05-29 16:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('sort', models.SmallIntegerField(blank=True, null=True, verbose_name='Sort order')),
                ('site', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sites.Site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Infoblock',
                'verbose_name_plural': 'Infoblocks',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='InfoBlockTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Infoblock Tag',
                'verbose_name_plural': 'Infoblock Tags',
                'db_table': 'info_blocks_tags',
            },
        ),
        migrations.CreateModel(
            name='TaggedInfoBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_blocks.InfoBlock')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_blocks.InfoBlockTag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='infoblock',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='info_blocks.TaggedInfoBlock', to='info_blocks.InfoBlockTag', verbose_name='Tags'),
        ),
    ]
