# Generated by Django 3.0.9 on 2020-09-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_blocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoblocktag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='infoblocktag',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='slug'),
        ),
    ]
