# Generated by Django 2.2.9 on 2019-12-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='css_class',
            new_name='field_css_classes',
        ),
        migrations.AlterField(
            model_name='field',
            name='field_css_classes',
            field=models.CharField(blank=True, max_length=128,
                                   verbose_name='Field CSS classes'),
        ),
        migrations.AddField(
            model_name='field',
            name='widget_css_classes',
            field=models.CharField(blank=True, max_length=128, verbose_name='Widget CSS classes'),
        ),
        migrations.AlterField(
            model_name='coursesurvey',
            name='expire_at',
            field=models.DateTimeField(help_text="With published selected, won't be shown after this time. Datetime should be specified in the timezone of the root course branch. Students will see deadline in MSK timezone", verbose_name='Expires on'),
        ),
    ]
