# Generated by Django 2.1.8 on 2019-04-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='expire_at',
        ),
        migrations.RemoveField(
            model_name='form',
            name='publish_at',
        ),
        migrations.AddField(
            model_name='coursesurvey',
            name='expire_at',
            field=models.DateTimeField(blank=True, help_text="With published selected, won't be shown after this time.", null=True, verbose_name='Expires on'),
        ),
        migrations.AddField(
            model_name='coursesurvey',
            name='publish_at',
            field=models.DateTimeField(blank=True, help_text="With published selected, won't be shown until this time.", null=True, verbose_name='Published from'),
        ),
    ]
