# Generated by Django 2.2.1 on 2019-05-24 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20190405_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesurvey',
            name='publish_at',
        ),
    ]
