# Generated by Django 2.2.9 on 2019-12-26 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20191226_1448'),
    ]

    operations = [
    ]
