# Generated by Django 2.2.4 on 2019-08-30 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission', '0002_auto_20190830_0814'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewstream',
            name='interviewers',
            field=models.ManyToManyField(limit_choices_to={'group__role': 7}, to=settings.AUTH_USER_MODEL, verbose_name='Interview|Interviewers'),
        ),
        migrations.AddField(
            model_name='interviewstream',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='streams', to='core.Location', verbose_name='Interview venue'),
        ),
        migrations.AddField(
            model_name='interviewslot',
            name='interview',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot', to='admission.Interview', verbose_name='Interview'),
        ),
        migrations.AddField(
            model_name='interviewslot',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='admission.InterviewStream', verbose_name='Interview stream'),
        ),
        migrations.AddField(
            model_name='interviewinvitation',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interview_invitations', to='admission.Applicant', verbose_name='Applicant'),
        ),
        migrations.AddField(
            model_name='interviewinvitation',
            name='interview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='admission.Interview', verbose_name='Interview'),
        ),
        migrations.AddField(
            model_name='interviewinvitation',
            name='streams',
            field=models.ManyToManyField(related_name='interview_invitations', to='admission.InterviewStream', verbose_name='Interview streams'),
        ),
        migrations.AddField(
            model_name='interviewassignment',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interview_assignments', to='admission.Campaign', verbose_name='InterviewAssignments|Campaign'),
        ),
        migrations.AddField(
            model_name='interview',
            name='applicant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='interview', to='admission.Applicant', verbose_name='Applicant'),
        ),
        migrations.AddField(
            model_name='interview',
            name='assignments',
            field=models.ManyToManyField(blank=True, to='admission.InterviewAssignment', verbose_name='Interview|Assignments'),
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewers',
            field=models.ManyToManyField(limit_choices_to={'group__role': 7}, to=settings.AUTH_USER_MODEL, verbose_name='Interview|Interviewers'),
        ),
        migrations.AddField(
            model_name='exam',
            name='applicant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='exam', to='admission.Applicant', verbose_name='Applicant'),
        ),
        migrations.AddField(
            model_name='contest',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contests', to='admission.Campaign', verbose_name='Contest|Campaign'),
        ),
        migrations.AddField(
            model_name='comment',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='admission.Interview', verbose_name='Interview'),
        ),
        migrations.AddField(
            model_name='comment',
            name='interviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interview_comments', to=settings.AUTH_USER_MODEL, verbose_name='Interviewer'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='core.Branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to='admission.Campaign', verbose_name='Applicant|Campaign'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to='admission.University', verbose_name='Applicant|University'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(django.db.models.deletion.SET_NULL), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('interview', 'interviewer')},
        ),
        migrations.AlterUniqueTogether(
            name='applicant',
            unique_together={('email', 'campaign')},
        ),
    ]
