# Generated by Django 2.1.5 on 2019-03-09 10:58

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_auto_20190308_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='patronymic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Patronymic'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='preferred_study_programs',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('cs', 'Computer Science (Современная информатика)'), ('ds', 'Data Science (Анализ данных)'), ('se', 'Software Engineering (Разработка ПО)')], help_text='Applicant|study_program', max_length=255, verbose_name='Study program'),
        ),
    ]
