# Generated by Django 2.1.5 on 2019-03-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_auto_20190309_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='stepic_id',
            field=models.CharField(blank=True, help_text='Applicant|stepic_id', max_length=255, null=True, verbose_name='Stepik ID'),
        ),
    ]
