# Generated by Django 2.1.7 on 2019-03-28 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_auto_20190328_1327'),
        ('admission', '0006_auto_20190325_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='learning.Branch', verbose_name='Branch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='application_ends_at',
            field=models.DateTimeField(help_text='Last day for submitting application', verbose_name='Application Ends on'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='application_starts_at',
            field=models.DateTimeField(verbose_name='Application Starts on'),
        ),
    ]
