# Generated by Django 2.2 on 2019-04-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0007_auto_20190328_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='contest_participant_id',
            field=models.IntegerField(blank=True, editable=False, help_text='Participant ID if user registered in Yandex Contest', null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='contest_status_code',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Yandex API Response'),
        ),
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('new', 'Not registered in contest'), ('registered', 'Registered in contest'), ('manual', 'Manual score input')], default='manual', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('new', 'Not registered in contest'), ('registered', 'Registered in contest'), ('manual', 'Manual score input')], default='new', max_length=15, verbose_name='Status'),
        ),
    ]
