# Generated by Django 2.2 on 2019-04-18 11:28

import core.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0008_auto_20190417_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='contest_participant_id',
            field=models.IntegerField(blank=True, help_text='participant_id in Yandex.Contest', null=True, verbose_name='Participant ID'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='contest_status_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Yandex API Response'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='score',
            field=core.db.models.ScoreField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('new', 'Not registered in the contest'), ('registered', 'Registered in the contest'), ('manual', 'Manual score input')], default='manual', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='test',
            name='contest_participant_id',
            field=models.IntegerField(blank=True, help_text='participant_id in Yandex.Contest', null=True, verbose_name='Participant ID'),
        ),
        migrations.AlterField(
            model_name='test',
            name='contest_status_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Yandex API Response'),
        ),
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('new', 'Not registered in the contest'), ('registered', 'Registered in the contest'), ('manual', 'Manual score input')], default='new', max_length=15, verbose_name='Status'),
        ),
    ]
