# Generated by Django 2.2 on 2019-04-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0009_auto_20190418_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('new', 'Not registered in the contest'), ('registered', 'Registered in the contest'), ('manual', 'Manual score input')], default='new', help_text='Choose `manual score input` to avoid synchronization with contest results', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('new', 'Not registered in the contest'), ('registered', 'Registered in the contest'), ('manual', 'Manual score input')], default='new', help_text='Choose `manual score input` to avoid synchronization with contest results', max_length=15, verbose_name='Status'),
        ),
    ]
