# Generated by Django 2.2.1 on 2019-05-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0010_auto_20190424_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='template_name',
            new_name='template_registration',
        ),
        migrations.AddField(
            model_name='campaign',
            name='template_appointment',
            field=models.CharField(blank=True, help_text='Template name for interview invitation email', max_length=255, verbose_name='Invitation Template'),
        ),
    ]
