# Generated by Django 2.2.1 on 2019-05-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0011_rename_campaign_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='template_registration',
            field=models.CharField(help_text='Template name for invitation email', max_length=255, verbose_name='Registration Template'),
        ),
    ]
