# Generated by Django 2.2.1 on 2019-05-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0012_auto_20190530_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='template_appointment',
            field=models.CharField(help_text='Template name for interview invitation email', max_length=255, verbose_name='Invitation Template'),
        ),
    ]
