# Generated by Django 2.2.1 on 2019-05-31 10:03

import admission.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0013_auto_20190530_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='template_appointment',
            field=models.CharField(help_text='Template name for interview invitation email', max_length=255, validators=[admission.models.validate_template], verbose_name='Invitation Template'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='template_registration',
            field=models.CharField(help_text='Template name for invitation email', max_length=255, validators=[admission.models.validate_template], verbose_name='Registration Template'),
        ),
    ]
