# Generated by Django 2.2.1 on 2019-05-31 13:17

import admission.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0014_auto_20190531_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='template_registration',
            field=models.CharField(help_text='Template name for contest registration email', max_length=255, validators=[admission.models.validate_template_name], verbose_name='Registration Template'),
        ),
        migrations.AlterField(
            model_name='interviewstream',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_streams', to='admission.Campaign', verbose_name='Campaign'),
        ),
    ]
