# Generated by Django 2.2.1 on 2019-06-21 08:30

import admission.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0015_auto_20190531_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='template_interview_reminder',
            field=models.CharField(default='admission-interview-reminder', help_text='Template name for interview reminder email', max_length=255, validators=[admission.models.validate_template_name], verbose_name='Interview Reminder Template'),
            preserve_default=False,
        ),
    ]
