# Generated by Django 2.2.3 on 2019-07-27 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0018_auto_20190727_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='branch',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='branch_new',
            new_name='branch',
        ),
    ]
