# Generated by Django 2.2.3 on 2019-07-27 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0019_auto_20190727_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='learning.Branch', to_field='code', verbose_name='Branch'),
        ),
    ]
