# Generated by Django 2.2.4 on 2019-08-09 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0020_auto_20190727_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='city',
        ),
    ]
