# Generated by Django 2.2.4 on 2019-08-09 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190809_1402'),
        ('admission', '0021_remove_campaign_city'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=None,
            state_operations=[
                # Copy the auto-generated operations here.
                migrations.CreateModel(
                    name='University',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(help_text='Perhaps also the faculty.', max_length=255, verbose_name='University')),
                        ('abbr', models.CharField(blank=True, max_length=100, null=True, verbose_name='University abbreviation')),
                        ('sort', models.SmallIntegerField(blank=True, null=True, verbose_name='Sort order')),
                        ('city', models.ForeignKey(default='spb', on_delete=django.db.models.deletion.CASCADE, to='core.City', verbose_name='City')),
                    ],
                    options={
                        'verbose_name': 'University',
                        'verbose_name_plural': 'Universities',
                    },
                ),
                # migrations.AlterField(
                #     model_name='applicant',
                #     name='university',
                #     field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to='admission.University', verbose_name='Applicant|University'),
                # ),
            ],
        ),

    ]
