# Generated by Django 2.2.4 on 2019-08-09 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0022_auto_20190809_1402'),
        ('core', '0004_delete_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to='admission.University', verbose_name='Applicant|University'),
        ),
        migrations.AlterField(
            model_name='interviewinvitation',
            name='expired_at',
            field=models.DateTimeField(help_text='Time in UTC since information about the timezone stored in m2m relationship', verbose_name='Expired at'),
        ),
    ]
