# Generated by Django 2.2.4 on 2019-08-09 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0022_invitation_branch'),
        ('admission', '0023_auto_20190809_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='branch',
            field=models.ForeignKey(default='spb', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='learning.Branch', to_field='code', verbose_name='Branch'),
            preserve_default=False,
        ),
    ]
