# Generated by Django 2.2.4 on 2019-08-09 15:04

from django.db import migrations


def copy_branch(apps, schema_editor):
    University = apps.get_model('admission', 'University')
    for sp in University.objects.all():
        sp.branch_id = sp.city_id
        if sp.branch_id == 'online':
            sp.branch_id = 'distance'
        sp.save(update_fields=['branch_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0024_university_branch'),
    ]

    operations = [
        migrations.RunPython(copy_branch)
    ]
