# Generated by Django 2.2.4 on 2019-08-09 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0025_auto_20190809_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='city',
        ),
        migrations.AlterField(
            model_name='university',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='learning.Branch', to_field='code', verbose_name='Branch'),
        ),
    ]
