# Generated by Django 2.2.4 on 2019-08-13 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0026_auto_20190809_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(django.db.models.deletion.SET_NULL), to=settings.AUTH_USER_MODEL),
        ),
    ]
