# Generated by Django 2.2.4 on 2019-08-14 08:49

from django.db import migrations


def copy_branch(apps, schema_editor):
    University = apps.get_model('admission', 'University')
    Campaign = apps.get_model('admission', 'Campaign')
    Branch = apps.get_model('core', 'Branch')
    for o in University.objects.select_related('branch'):
        if o.branch_id:
            o.branch_new2_id = o.branch.id
            o.save(update_fields=["branch_new2_id"])
    for o in Campaign.objects.select_related('branch'):
        if o.branch_id:
            o.branch_new2_id = o.branch.id
            o.save(update_fields=["branch_new2_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0029_auto_20190814_0849'),
    ]

    operations = [
        migrations.RunPython(copy_branch)
    ]
