# Generated by Django 2.2.4 on 2019-08-14 08:57

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0030_auto_20190814_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='branch',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='branch_new2',
            new_name='branch',
        ),
        migrations.RemoveField(
            model_name='university',
            name='branch',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='branch_new2',
            new_name='branch',
        ),

    ]
