# Generated by Django 2.2.4 on 2019-08-14 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0031_auto_20190814_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='core.Branch', verbose_name='Branch'),
        ),
    ]
