# Generated by Django 2.2.4 on 2019-08-14 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0032_auto_20190814_0917'),
        ('core', '0011_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewstream',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='streams', to='core.Venue', verbose_name='Interview venue'),
        ),
    ]
