# Generated by Django 2.2.4 on 2019-08-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0033_auto_20190814_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='github_id',
            new_name='github_login',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='yandex_id',
            new_name='yandex_login',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='yandex_id_normalize',
            new_name='yandex_login_q',
        ),
    ]
