# Generated by Django 2.2.4 on 2019-08-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0034_auto_20190828_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='github_login',
            field=models.CharField(blank=True, help_text='Applicant|github_login', max_length=255, null=True, verbose_name='Github Login'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='yandex_login',
            field=models.CharField(blank=True, help_text='Applicant|yandex_login', max_length=80, null=True, verbose_name='Yandex Login'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='yandex_login_q',
            field=models.CharField(blank=True, help_text='Applicant|yandex_id_normalization', max_length=80, null=True, verbose_name='Yandex Login (normalized)'),
        ),
    ]
