# Generated by Django 2.2.4 on 2019-08-30 08:14

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('name', models.CharField(max_length=255, verbose_name='Course|name')),
                ('teachers', models.TextField(help_text='How to style text read <a href="/commenting-the-right-way/" target="_blank">here</a>. Partially HTML is enabled too.', verbose_name='Online Course|teachers')),
                ('description', models.TextField(help_text='How to style text read <a href="/commenting-the-right-way/" target="_blank">here</a>. Partially HTML is enabled too.', verbose_name='Online Course|description')),
                ('link', models.URLField(verbose_name='Online Course|Link')),
                ('photo', sorl.thumbnail.fields.ImageField(blank=True, upload_to='online_courses/', verbose_name='Online Course|photo')),
                ('is_au_collaboration', models.BooleanField(default=False, verbose_name='Collaboration with AY')),
                ('is_self_paced', models.BooleanField(default=False, verbose_name='Without deadlines')),
            ],
            options={
                'verbose_name': 'Online course',
                'verbose_name_plural': 'Online courses',
                'db_table': 'online_courses',
                'ordering': ['name'],
            },
        ),
    ]
