# Generated by Django 3.0.9 on 2020-09-02 09:15

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('online_courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinecourse',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(blank=True, max_length=200, upload_to='online_courses/', verbose_name='Online Course|photo'),
        ),
    ]
