# Generated by Django 2.1.5 on 2019-02-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190109_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('canceled', 'Canceled'), ('continued', 'Continued without intermediate results')], max_length=10, null=True, verbose_name='StudentProject|Status'),
        ),
    ]
