# Generated by Django 2.1.5 on 2019-02-12 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='canceled',
        ),
    ]
