# Generated by Django 2.2.1 on 2019-05-21 15:07

import core.db.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20190517_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='final_score',
            field=core.db.models.ScoreField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Final Score'),
        ),
        migrations.AlterField(
            model_name='report',
            name='project_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='projects.ProjectStudent'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporting_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='projects.ReportingPeriod'),
        ),
    ]
