# Generated by Django 2.2.1 on 2019-05-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20190522_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='score_global_issue',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_global_issue_note',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_plans',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_plans_note',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_problems',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_problems_note',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_progress',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_progress_note',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_technologies',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_technologies_note',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_usefulness',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_usefulness_note',
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('sent', 'New Report'), ('review', 'Review'), ('rating', 'Waiting for final score'), ('completed', 'Completed')], default='sent', max_length=15, verbose_name='Status'),
        ),
    ]
