# Generated by Django 2.2.4 on 2019-08-14 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20190814_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='branch',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='branch_new2',
            new_name='branch',
        ),
        migrations.RemoveField(
            model_name='reportingperiod',
            name='branch',
        ),
        migrations.RenameField(
            model_name='reportingperiod',
            old_name='branch_new2',
            new_name='branch',
        ),
    ]
