# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hint',
            options={'ordering': ['sort'], 'verbose_name': 'Hint', 'verbose_name_plural': 'Warehouse'},
        ),
    ]
