# Generated by Django 2.1.1 on 2018-10-31 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_auto_20181031_1308'),
        ('post_office', '0006_attachment_mimetype'),
        ('surveys', '0002_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseOfferingSurvey',
            new_name='CourseSurvey',
        ),
    ]
