# Generated by Django 2.1.1 on 2018-10-10 13:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0020_auto_20180903_1354'),
        ('surveys', '0002_data_form_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldentry',
            name='is_choice',
            field=models.BooleanField(default=False, verbose_name='Is Choice'),
        ),
        migrations.AlterField(
            model_name='field',
            name='conditional_logic',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Array of dictionaries with logic rules', null=True, verbose_name='Conditional Logic'),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.SmallIntegerField(choices=[(1, 'Single line text'), (2, 'Multi line text'), (3, 'Email'), (13, 'Number'), (14, 'URL'), (4, 'Check box'), (5, 'Check boxes'), (15, 'Check boxes with textarea'), (6, 'Drop down'), (7, 'Multi select'), (8, 'Radio buttons'), (10, 'Date'), (11, 'Date/time')], verbose_name='Field Type'),
        ),
        migrations.AlterField(
            model_name='fieldchoice',
            name='field',
            field=models.ForeignKey(limit_choices_to={'field_type__in': [5, 15, 6, 7, 8]}, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='surveys.Field'),
        ),
        migrations.AlterField(
            model_name='fieldentry',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='surveys.FormSubmission'),
        ),
        migrations.AlterUniqueTogether(
            name='courseofferingsurvey',
            unique_together={('course_offering', 'type')},
        ),
    ]
