# Generated by Django 2.1.1 on 2018-10-16 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0006_attachment_mimetype'),
        ('surveys', '0002_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='email_template',
        ),
        migrations.AddField(
            model_name='courseofferingsurvey',
            name='email_template',
            field=models.ForeignKey(blank=True, help_text='Students will receive notification based on this template after form publication', null=True, on_delete=django.db.models.deletion.CASCADE, to='post_office.EmailTemplate'),
        ),
    ]
