# Generated by Django 2.1.1 on 2018-10-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20181016_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseofferingsurvey',
            name='students_notified',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
