# Generated by Django 2.1.1 on 2018-10-31 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_auto_20181031_1308'),
        ('surveys', '0003_auto_20181031_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursesurvey',
            old_name='course_offering',
            new_name='course',
        ),
        migrations.AlterUniqueTogether(
            name='coursesurvey',
            unique_together={('course', 'type')},
        ),
    ]
