# Generated by Django 2.1.1 on 2018-11-06 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20181031_1428'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesurvey',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='courses.Course'),
        ),
    ]
