# Generated by Django 2.1.1 on 2018-10-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_courseofferingsurvey_students_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='is_template',
        ),
        migrations.AlterField(
            model_name='form',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Published'), (2, 'Template')], default=1, verbose_name='Status'),
        ),
    ]
