# Generated by Django 2.1.1 on 2018-10-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_fix_form_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldentry',
            name='value',
            field=models.TextField(null=True),
        ),
    ]
