# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-12 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_auto_20170412_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='patronymic',
            field=models.CharField(max_length=255, verbose_name='Patronymic'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='surname',
            field=models.CharField(max_length=255, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='score',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Score'),
        ),
    ]
