# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-17 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_auto_20170412_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='university2',
            field=models.CharField(blank=True, help_text='Applicant|university_legacy', max_length=255, null=True, verbose_name='University_legacy'),
        ),
    ]
