# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 13:59
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admission', '0006_auto_20170524_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start_at', models.TimeField(verbose_name='Interview start')),
                ('end_at', models.TimeField(verbose_name='Interview end')),
            ],
            options={
                'verbose_name': 'Interview slot',
                'ordering': ['start_at'],
                'verbose_name_plural': 'Interview slots',
            },
        ),
        migrations.CreateModel(
            name='InterviewStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField(verbose_name='Interview day')),
                ('start_at', models.TimeField(verbose_name='Period start')),
                ('end_at', models.TimeField(verbose_name='Period end')),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(10)], verbose_name='Slot duration')),
                ('with_assignments', models.BooleanField(help_text='Based on this flag, student should arrive 30 min before or not', verbose_name='Has assignments')),
                ('interviewers', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Interview|Interviewers')),
            ],
            options={
                'verbose_name': 'Interview stream',
                'verbose_name_plural': 'Interview streams',
            },
        ),
        migrations.CreateModel(
            name='InterviewVenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Venue|Name')),
                ('address', models.CharField(blank=True, help_text='Should be resolvable by Google Maps', max_length=500, verbose_name='Venue|Address')),
                ('description', models.TextField(help_text='How to style text read <a href="/commenting-the-right-way/" target="_blank">here</a>. Partially HTML is enabled too.', verbose_name='How to get')),
                ('city', models.ForeignKey(blank=True, default='spb', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.City')),
            ],
            options={
                'verbose_name': 'Interview venue',
                'verbose_name_plural': 'Interview venues',
            },
        ),
        migrations.AddField(
            model_name='interview',
            name='secret',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, verbose_name='Secret key for interview assign'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='When'),
        ),
        migrations.AddField(
            model_name='interviewstream',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venues', to='admission.InterviewVenue', verbose_name='Interview venue'),
        ),
        migrations.AddField(
            model_name='interviewslot',
            name='interview',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slot', to='admission.Interview', verbose_name='Interview'),
        ),
        migrations.AddField(
            model_name='interviewslot',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='admission.InterviewStream', verbose_name='Interview stream'),
        ),
    ]
