# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 17:10
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0007_auto_20170607_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 8, 17, 10, 57, 709939, tzinfo=utc), verbose_name='When'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('approval', 'Approval'), ('deferred', 'Deferred'), ('canceled', 'Canceled'), ('waiting', 'Approved'), ('completed', 'Completed')], default='approval', max_length=15, verbose_name='Interview|Status'),
        ),
        migrations.AlterField(
            model_name='interviewstream',
            name='duration',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(10)], verbose_name='Slot duration'),
        ),
    ]
