# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-09 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0008_auto_20170608_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='secret',
        ),
        migrations.AlterField(
            model_name='interviewslot',
            name='interview',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot', to='admission.Interview', verbose_name='Interview'),
        ),
        migrations.AlterField(
            model_name='interviewvenue',
            name='description',
            field=models.TextField(verbose_name='How to get'),
        ),
    ]
