# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-13 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0009_auto_20170609_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewstream',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='streams', to='learning.Venue', verbose_name='Interview venue'),
        ),
    ]
