# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-14 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0010_auto_20170613_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('secret_code', models.UUIDField(default=uuid.uuid4, verbose_name='Secret code')),
                ('expired_at', models.DateTimeField(blank=True, null=True, verbose_name='Expired at')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interview_invitations', to='admission.Applicant', verbose_name='Applicant')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interview_invitations', to='admission.InterviewStream', verbose_name='Interview stream')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='interviewvenue',
            name='city',
        ),
        migrations.DeleteModel(
            name='InterviewVenue',
        ),
    ]
