# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-14 14:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0011_auto_20170614_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewinvitation',
            name='date',
            field=models.DateField(default=datetime.date(2017, 6, 14), editable=False, verbose_name='Estimated interview day'),
            preserve_default=False,
        ),
    ]
