# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-26 14:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0013_auto_20170623_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewinvitation',
            name='date',
            field=models.DateField(verbose_name='Estimated interview day'),
        ),
        migrations.AlterField(
            model_name='interviewinvitation',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 26, 14, 44, 12, 712844, tzinfo=utc), verbose_name='Expired at'),
            preserve_default=False,
        ),
    ]
