# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-28 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0014_auto_20170626_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='access_token',
            field=models.CharField(blank=True, help_text='Yandex.Contest Access Token', max_length=255, verbose_name='Access Token'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='application_ends_at',
            field=models.DateField(default=django.utils.timezone.now, help_text='Last day for submitting application', verbose_name='Application Ends At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='refresh_token',
            field=models.CharField(blank=True, help_text='Yandex.Contest Refresh Token', max_length=255, verbose_name='Refresh Token'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='template_name',
            field=models.CharField(blank=True, help_text='Template name for invitation email message', max_length=255, verbose_name='Template Name'),
        ),
    ]
