# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-28 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0015_auto_20180228_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='contest_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Yandex.Contest ID'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='participant_id',
            field=models.IntegerField(blank=True, help_text='Participant ID if user registered in Yandex Contest', null=True, verbose_name='Participant ID'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='status_code',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Yandex API Response'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='yandex_id',
            field=models.CharField(blank=True, help_text='Applicant|yandex_id', max_length=80, null=True, verbose_name='Yandex ID'),
        ),
    ]
