# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-28 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0016_auto_20180228_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='type',
            field=models.IntegerField(choices=[(1, 'Testing'), (2, 'Exam')], default=1, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
