# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0017_contest_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicant',
            unique_together=set([('email', 'campaign')]),
        ),
    ]
