# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-23 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0018_auto_20180301_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='participant_id',
            field=models.IntegerField(blank=True, editable=False, help_text='Participant ID if user registered in Yandex Contest', null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='status_code',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Yandex API Response'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='preferred_study_programs',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ds', 'Анализ данных'), ('cs', 'Современная информатика'), ('se', 'Разработка ПО')], help_text='Applicant|study_program', max_length=255, verbose_name='Study program'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='current',
            field=models.BooleanField(default=False, help_text='Show in application form list', verbose_name='Current campaign'),
        ),
        migrations.AlterField(
            model_name='test',
            name='details',
            field=jsonfield.fields.JSONField(blank=True, default='', verbose_name='Details'),
            preserve_default=False,
        ),
    ]
