# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-23 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0019_auto_20180323_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='participant_id',
            new_name='contest_participant_id',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='status_code',
            new_name='contest_status_code',
        ),
        migrations.AddField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('new', 'Not submitted'), ('in_progress', 'In progress'), ('completed', 'Finished')], default='new', max_length=15, verbose_name='Status'),
        ),
    ]
