# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-23 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0020_auto_20180323_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Score'),
        ),
    ]
