# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-23 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0021_auto_20180323_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='contest_id',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='participant_id',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='status_code',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('registered', 'Registered'), ('in_progress', 'In progress'), ('completed', 'Finished')], default='new', max_length=15, verbose_name='Status'),
        ),
    ]
