# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-27 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0022_auto_20180323_1806'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='applicant',
            managers=[
                ('subscribed', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='is_unsubscribed',
            field=models.BooleanField(db_index=True, default=False, help_text='Unsubscribed from future notifications', verbose_name='Unsubscribed'),
        ),
    ]
