# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-30 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0023_auto_20180327_1238'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='applicant',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='applicant',
            name='is_unsubscribed',
            field=models.BooleanField(db_index=True, default=False, help_text='Unsubscribe from future notifications', verbose_name='Unsubscribed'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='where_did_you_learn',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('uni', 'плакат/листовка в университете'), ('social_net', 'пост в соц. сетях'), ('friends', 'от друзей'), ('other', 'другое'), ('habr', 'Прочитал в статье на habr.ru'), ('club', 'Из CS клуба'), ('tandp', 'Теории и практики')], help_text='Applicant|where_did_you_learn_about_cs_center', max_length=44, verbose_name='Where did you learn?'),
        ),
    ]
