# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-03 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0026_auto_20180403_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='has_job',
            field=models.NullBooleanField(help_text='Applicant|has_job', verbose_name='Do you work?'),
        ),
    ]
