# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0027_auto_20180403_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='application_ends_at',
            field=models.DateTimeField(help_text='Last day for submitting application', verbose_name='Application Ends At'),
        ),
    ]
