# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-17 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0028_auto_20180410_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('registered', 'Registered'), ('auto', 'Auto updating score'), ('manual', 'Manual score input')], default='new', max_length=15, verbose_name='Status'),
        ),
    ]
