# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-30 11:54
from __future__ import unicode_literals

import core.db.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0029_auto_20180417_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='score',
            field=core.db.models.GradeField(decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)], verbose_name='Score'),
        ),
    ]
