# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-28 09:13
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0030_auto_20180530_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='details',
            field=jsonfield.fields.JSONField(blank=True, verbose_name='Details'),
        ),
    ]
