# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 15:20
from __future__ import unicode_literals

import core.db.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import learning.admission.models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0031_contest_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewinvitation',
            name='streams',
            field=models.ManyToManyField(related_name='interview_invitations', to='admission.InterviewStream', verbose_name='Interview streams'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='details',
            field=jsonfield.fields.JSONField(blank=True, validators=[learning.admission.models.validate_json_container], verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='score',
            field=core.db.models.GradeField(decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)], verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='interviewinvitation',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='old_interview_invitations', to='admission.InterviewStream', verbose_name='Interview stream'),
        ),
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('registered', 'Registered in contest'), ('manual', 'Manual score input')], default='new', max_length=15, verbose_name='Status'),
        ),
    ]
