# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 15:26
from __future__ import unicode_literals

import core.db.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0033_auto_20180705_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewinvitation',
            name='stream',
        ),
    ]
