# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 15:32
from __future__ import unicode_literals

import core.db.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0034_auto_20180705_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewinvitation',
            name='date',
        ),
        migrations.AlterField(
            model_name='exam',
            name='score',
            field=core.db.models.GradeField(decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)], verbose_name='Score'),
        ),
    ]
