# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-30 15:37
from __future__ import unicode_literals

import core.db.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0036_create_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='city',
            field=models.ForeignKey(default='spb', on_delete=django.db.models.deletion.PROTECT, to='core.City', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='score',
            field=core.db.models.GradeField(decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)], verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='interviewinvitation',
            name='expired_at',
            field=models.DateTimeField(help_text='Time in UTC since information about city timezone stored in m2m relationship', verbose_name='Expired at'),
        ),
    ]
