# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 14:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import learning.admission.models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0041_auto_20160706_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=models.SET(django.db.models.deletion.SET_NULL), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='code',
            field=models.CharField(help_text='Campaign year', max_length=140, verbose_name='Campaign|Code'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='file',
            field=models.FileField(blank=True, help_text='Make sure file does not include solutions due to it visible with direct url link', upload_to=learning.admission.models.contest_assignments_upload_to, verbose_name='Assignments in pdf format'),
        ),
    ]
