# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-07 13:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0042_auto_20160802_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='name',
        ),
        migrations.AddField(
            model_name='campaign',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2011)], verbose_name='Campaign|Year'),
        ),
    ]
