# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-07 13:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import learning.admission.models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0043_auto_20170207_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='code',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='year',
            field=models.PositiveSmallIntegerField(default=learning.admission.models.current_year, validators=[django.core.validators.MinValueValidator(2011)], verbose_name='Campaign|Year'),
        ),
    ]
