# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-07 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160318_1936'),
        ('admission', '0044_auto_20170207_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='city',
            field=models.ForeignKey(default='RU SPB', on_delete=django.db.models.deletion.CASCADE, to='core.City'),
        ),
    ]
