# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-14 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0045_campaign_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='yandex_id_normalize',
            field=models.CharField(blank=True, help_text='Applicant|yandex_id_normalization', max_length=80, null=True, verbose_name='Yandex ID normalisation'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='city',
            field=models.ForeignKey(default='RU SPB', on_delete=django.db.models.deletion.CASCADE, to='core.City', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='details',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='test',
            name='details',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Details'),
        ),
    ]
