# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-27 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0046_auto_20170214_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='university',
            new_name='university2',
        ),
    ]
