# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-27 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0047_auto_20170227_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='university_other',
            field=models.CharField(blank=True, help_text='Applicant|university_other', max_length=255, null=True, verbose_name='University (Other)'),
        ),
    ]
