# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-03 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0049_applicant_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='preferred_study_programs_cs_note',
            field=models.TextField(blank=True, help_text='Applicant|study_program_cs', null=True, verbose_name='Study program (CS note)'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='preferred_study_programs_dm_note',
            field=models.TextField(blank=True, help_text='Applicant|study_program_dm', null=True, verbose_name='Study program (DM note)'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='preferred_study_programs_se_note',
            field=models.TextField(blank=True, help_text='Applicant|study_program_se', null=True, verbose_name='Study program (SE note)'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='where_did_you_learn_other',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Where did you learn? (other)'),
        ),
    ]
