---
- name: restore production backup for CSC website
  hosts: "{{ host }}"
  user: ubuntu
  sudo: True

  tasks:
  - name: fetching backup and applying it
    sudo_user: "{{ app_user }}"
    django_manage:
      command: "{{ item }}"
      app_path: "/home/{{ app_user }}/site/repo/cscsite"
      settings: "{{ app_user }}.settings.production"
      virtualenv: "/home/{{ app_user }}/site/env/"
    with_items:
      - cscrestore
    notify: reload uwsgi

  handlers:
    - include: roles/app/handlers/main.yml
