---
- name: Backup data and save it to S3 bucket
  hosts: "{{ aws_ec2_host }}"
  user: ubuntu

  tasks:
  - fail: msg="site_user value should one of [cscenter, csclub]"
    when: site_user not in ["cscenter", "csclub"]
    tags:
      - always

  - name: Run management command for making db backup
    become_user: "{{ site_user }}"
    django_manage:
      command: "dbbackup"
      app_path: "/home/{{ site_user }}/site/repo"
      settings: "{{ site_user }}.settings.production"
      virtualenv: "/home/{{ site_user }}/site/env/"
    tags:
      - db

  - name: Run management command for making media backup
    become_user: "{{ site_user }}"
    django_manage:
      command: mediabackup --compress
      app_path: "/home/{{ site_user }}/site/repo"
      settings: "{{ site_user }}.settings.production"
      virtualenv: "/home/{{ site_user }}/site/env/"
    tags:
      - media
