---
- name: Make a backup of db and media/ folder for CSCenter website
  hosts: "{{ aws_ec2_host }}"
  become: yes
  become_user: ubuntu
  vars_files:
    - vars/aws.yml

  tasks:
  - name: Check app_user value
    fail:
      msg: "app_user value should one from [cscenter, csclub]"
    when: app_user != "cscenter" and app_user != "csclub"

  - name: making a backup for {{ app_user }} site
    become_user: "{{ app_user }}"
    django_manage:
      command: "{{ item }}"
      app_path: "/home/{{ app_user }}/site/repo"
      settings: "{{ app_user }}.settings.production"
      virtualenv: "/home/{{ app_user }}/site/env/"
    with_items:
      - cscbackup
