- name: Setup application for compscicenter.ru
  hosts: "{{ hosts_override | default(aws_ec2_host) }}"
  user: "{{ aws_ec2_user }}"
  become: yes
  become_user: "{{ aws_ec2_root_user }}"
  tasks:
    - import_role:
        name: app
        vars_from: cs_center.vault.yml
      vars:
        main_domain: "compscicenter.ru"
        site_user: "cscenter"
        site_user_group: "shared"
        app_root: "/home/{{ site_user }}/site"
        repo_root: "{{ app_root }}/repo"
        virtualenv_root: "{{ app_root }}/env"
        static_root: "{{ repo_root }}/apps/static"
        media_root: "/shared/media"
        media_directory_permissions: "775"
        backup_root: "/shared/backup_tmp"
        site_dir_name: "{{ main_domain|replace('.', '_') }}"
        apps_dir_name: apps
        app_environment: production
        setup_cronjobs: yes
        nginx_configs:
          - "{{ main_domain }}"
          - "my.{{ main_domain }}"
        certbot_config_dir: "/etc/letsencrypt/live/compscicenter.ru"
        certbot_domains:
          - "{{ main_domain }}"
          - "www.compscicenter.ru"
          - "my.compscicenter.ru"
        rq_workers:
          - default
          - high
        rq_workers_target_service_name: "rqworker_cscenter"
        processes_num: 5
        log_to_file: no
        repo_url: git@github.com:cscenter/site.git
