- name: Setup EC2 instance
  hosts: "{{ hosts_override | default(aws_ec2_host) }}"
  user: "{{ aws_ec2_user }}"
  become: yes
  become_user: "{{ aws_ec2_root_user }}"
  tasks:

    - name: Setup application for compsciclub.ru
      import_role:
        name: app
      vars:
        app_config: "{{ available_sites['compsciclub.ru'] }}"
      tags:
        - app-role
        - compsciclub.ru