- name: Setup application for compsciclub.ru
  hosts: "{{ hosts_override | default(aws_ec2_host) }}"
  user: "{{ aws_ec2_user }}"
  become: yes
  become_user: "{{ aws_ec2_root_user }}"
  tasks:
    - import_role:
        name: app
        vars_from: cs_club.vault.yml
      vars:
        main_domain: "compsciclub.ru"
        site_user: "csclub"
        site_user_group: "shared"
        app_root: "/home/{{ site_user }}/site"
        repo_root: "{{ app_root }}/repo"
        virtualenv_root: "{{ app_root }}/env"
        static_root: "{{ repo_root }}/apps/static"
        media_root: "/shared/media"
        media_directory_permissions: "775"
        backup_root: "/shared/backup_tmp"
        site_dir_name: "{{ main_domain|replace('.', '_') }}"
        apps_dir_name: apps
        app_environment: production
        setup_cronjobs: no
        certbot_domains:
          - "{{ main_domain }}"
          - "www.compsciclub.ru"
          - "kzn.compsciclub.ru"
          - "nsk.compsciclub.ru"
        nginx_configs:
          - "{{ main_domain }}"
        certbot_config_dir: "/etc/letsencrypt/live/compsciclub.ru"
        rq_workers: []
        rq_workers_target_service_name: "rqworker_csclub"
        processes_num: 3
        log_to_file: no
        repo_url: git@github.com:cscenter/site.git
