- name: Setup application for compsciclub.ru
  hosts: "{{ hosts_override | default(aws_ec2_host) }}"
  user: "{{ aws_ec2_user }}"
  become: yes
  become_user: "{{ aws_ec2_root_user }}"
  tasks:
    - import_role:
        name: app
      vars:
        main_domain: "compsciclub.ru"
        site_user: "csclub"
        site_user_group: "shared"
        app_root: "/home/{{ site_user }}/site"
        repo_root: "{{ app_root }}/repo"
        virtualenv_root: "{{ app_root }}/env"
        static_root: "{{ repo_root }}/apps/static"
        media_root: "/shared/media"
        backup_root: "/shared/backup_tmp"
        site_dir_name: "{{ main_domain|replace('.', '_') }}"
        apps_dir_name: apps
        app_environment: production
        db_name: cscdb
        db_user: csc
        db_user_password: FooBar
        setup_cronjobs: no
        certbot_domains:
          - "{{ main_domain }}"
          - "www.compsciclub.ru"
          - "kzn.compsciclub.ru"
          - "nsk.compsciclub.ru"
        nginx_configs:
          - "{{ main_domain }}"
        certbot_config_dir: "/etc/letsencrypt/live/compsciclub.ru"
        rq_workers: []
        rq_workers_target_service_name: "rqworker_csclub"
        processes_num: 3
        log_to_file: no
        repo_url: git@github.com:cscenter/site.git
        deploy_ssh_key: |
          -----BEGIN RSA PRIVATE KEY-----
          MIIEowIBAAKCAQEAxG7bqot6KC5Jww3wqILoaeWGFOro7v865HEr9+I0inzq0N9O
          i3gs8gC6e2qm8g0vvxijdo0VvdJHRVo6eQB0pywNS8xhzxnDfLVZ+cwMiA2loc9b
          IdGjOYEMxQVyxMU6TCRs9ydIpwKU/p8bx+qtxEdKqa249L63FtBxH+90g4KwtoQn
          KktawqyIXF9QKaDNYtuCppP9CmAVRWMTOLQWzXMORdq/hglYtnooO5+Lb/B6eYS1
          HIZynRubqHkJDdSWOSIQ7ovVwMylWSkYAjZXGH+uJdKv8CekW+DVnMcO0y4M8Xks
          q9zo+9NML8UbOOX6HuAGOU1BFNT7obIHZV8miQIDAQABAoIBAF0cU0Gm9ZOARXSQ
          8gdebf5sTr8xjpJjJy5LutS4Q8F1bvTtNNUFdQCNedeweUv5Fi3V5v316F1fBGuK
          Vncu0RzA09ifG6nIg5JkgC7ZGwOOvHlTydXhAibq1fu6FmnRN04KYiBRXa3Umn2L
          O+bqhc2pIWoGr8pLcIv+5/CEV81R2qCB+khRJGm4SdaHBoFUjtpphSi1+1y92dMF
          b2caCBDbNt3+2T/GMI8G+Xj8YU8LW/B1miVrdJnFQEQ/wYS/cfxz7cQbPZh30mOH
          BTUpndbDEj7NyRFYAbhey0Cq+sVhlRzaXBFKG2w0pRBhTNoD+b84M9Rx8R6BRFRq
          ab2035ECgYEA+7WAlhzybUGyxgyGqrmj9YDt44OFR3P9qCp+/yzIMwt+CerkijnE
          qrr+WCyPsWq35iAvEiGc0SvPMKhb4Ck8sdBicJ4SZ/nt8fxk1TBOc7Rpp8ZjffQ9
          R9WrkfzY63NTTfUguIrPSyZU3j5tH90x1pmT7QZqHFZPhTLfXT6DrB0CgYEAx8gf
          cE0DHmGMN8krEf+mFTG4fRNsbEV9vV8Ql27n+28xTPaRDPAKwrj+GooU4mO4iMfI
          A4VPyIKhTlW6LF/oozvP7tUPbhemoaqhZXzHqrD08kIQXp11f5G3WRrKSYKDJpGd
          ft6n3rPtuBOfUgg+DvmM6Wvuj4Qyt+Am/cc+IF0CgYB98tcRxhBEPUCQOwpTeSqi
          mM3wLwpMs6x0Ljd3xdezOwfpPID47WkMKR9FzZ5lH0o/u1DyWKFYRPyak1PNubSm
          IOhxA5egMX4vvKRTzKUk3lyT2ABGsSTMwgzkssl0HzPK6WJjFQoex2JmBoSiEhNz
          F0veqXwFC+ckdk0wIizOvQKBgAxxiJPEGDeiN8uZuhcK51tWl3ki5pPv2B8ddrkX
          7VcZ2+ZBTVOS9/ic8SbSBu766xmJ6AlgGlIQ4N8yM8Bj0Oep6A+mManXy0cyi474
          sK8PCpK0TrS19gWWG+du5b6iZGzYkQi/8ZDLgDkA7+F6JfNk08QONvO1djtBuOwB
          pvr5AoGBALZ0UeFUnbwLyaA3Q8GAwlDGrHwLyfJ8Ct9gCZW2GwC4FxB7N/xGqD9J
          raUaWa85AZ3xRIDUa+mzeVoNfg7w9eJiYBjZsObFFc6uc4DoXvxBydE7Q76Q5dp1
          H42VlZIYR4tVpKSeLLDyv5HtQ0gmIl6N6QCssFPrtbOliUoHieuI
          -----END RSA PRIVATE KEY-----