---
- name: Start deployment
  hosts: "{{ aws_ec2_host_new }}"
  user: ubuntu
  sudo: True
  vars_files:
    - vars/aws.yml

  tasks:
  - name: Check app_user value
    fail:
      msg: "`app_user` var should be one of [cscenter, csclub]"
    when: app_user != "cscenter" and app_user != "csclub"

  - name: Set variables for better readability
    set_fact:
      site_src: "/home/{{ app_user }}/site/repo"
      venv_dir: "/home/{{ app_user }}/site/env"

  - name: Get stuff from git
    git: repo=git@github.com:cscenter/site.git dest={{ site_src }}
    become: yes
    become_user: "{{ app_user }}"

  - name: Install requirements
    pip: requirements={{ site_src }}/requirements.txt virtualenv={{ venv_dir }}
    become: yes
    become_user: "{{ app_user }}"

  - name: Collectstatic
    sudo_user: "{{ app_user }}"
    django_manage:
      command: "collectstatic"
      app_path: "{{ site_src }}"
      settings: "{{ app_user }}.settings.production"
      virtualenv: "{{ venv_dir }}"

  - name: reload cscenter workers
    service: name=rqworkers state=reloaded
    become: yes
    become_method: sudo
    when: app_user == "cscenter"

  - name: reload club site worker
    service: name=rqworker_club state=reloaded
    become: yes
    become_method: sudo
    when: app_user == "csclub"

  - name: Migrate DB
    sudo_user: "{{ app_user }}"
    django_manage:
      command: "migrate"
      app_path: "{{ site_src }}"
      settings: "{{ app_user }}.settings.production"
      virtualenv: "{{ venv_dir }}"


  - name: Touch config file to reload uwsgi
    file: path=/etc/uwsgi/vassals/{{ app_user }}.ini state=touch
    become: yes
    become_method: sudo


