---
# heavily inspired by:
# https://github.com/tgerla/ansible-aws-examples
# http://answersforaws.com/episodes/2-ansible-and-aws/
# http://halberom.co.uk/setting-up-a-blog-environment-on-aws.html

- name: Provision ec2 instances
  hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - vars/aws-vars.yml

  tasks:
  - name: Create required security groups
    ec2_group:
      name: "{{ item.name }}"
      description: "{{ item.desc }}"
      rules: "{{ item.rules }}"
      region: "{{ ec2_region }}"
    with_items: security_groups

  - name: Launch instance
    ec2:
      region: "{{ ec2_region }}"
      keypair: csc-main
      instance_type: t2.micro
      group:
        - web
        - ssh
      image: ami-ac1524b1
      instance_tags:
        Name: cscweb
      exact_count: 1
      count_tag:
        Name: cscweb
      volumes:
        - device_name: /dev/sda1
          volume_size: 50
          volume_type: gp2
      wait: true
    register: ec2

  - name: Add launched instances to host group
    local_action: add_host hostname={{ item.public_ip }} groupname=cscweb
    with_items: ec2.tagged_instances

  - name: Display an IP of newly launched instance
    debug: msg="{{ groups['cscweb'][0] }}"

  - name: Wait for SSH to become available
    pause: minutes=1

- name: Setup provisioned servers
  hosts: cscweb
  user: ubuntu
  sudo: True
  tasks:
    - apt: name=git state=present
