---
# heavily inspired by:
# https://github.com/tgerla/ansible-aws-examples
# http://answersforaws.com/episodes/2-ansible-and-aws/
# http://halberom.co.uk/setting-up-a-blog-environment-on-aws.html

- name: provision ec2 instances
  hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - vars/aws-vars.yml

  tasks:
  - name: create required security groups
    ec2_group:
      name: "{{ item.name }}"
      description: "{{ item.desc }}"
      rules: "{{ item.rules }}"
      rules_egress: "{{ item.rules_egress }}"
      region: "{{ ec2_region }}"
    with_items: security_groups

  - name: launch instance
    ec2:
      region: "{{ ec2_region }}"
      keypair: csc-main
      instance_type: t2.small
      group:
        - web
        - ssh
      image: ami-ac1524b1
      instance_tags:
        Name: cscweb
      exact_count: 1
      count_tag:
        Name: cscweb
      volumes:
        - device_name: /dev/sda1
          volume_size: 50
          volume_type: gp2
      wait: true
    register: ec2

  - name: add launched instances to host group
    local_action: add_host hostname={{ item.public_ip }} groupname=tag_Name_cscweb
    with_items: ec2.tagged_instances

  - name: display an IP of newly launched instance
    debug: msg="{{ groups['tag_Name_cscweb'][0] }}"

  - name: wait for SSH to become available
    local_action: wait_for host="{{ groups['tag_Name_cscweb'][0] }}" port=22

- name: setup provisioned servers
  include: setup.yml
