VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.7.0"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    # Disable the new default behavior introduced in Vagrant 1.7, to
    # ensure that all Vagrant machines will use the same SSH key pair.
    # See https://github.com/mitchellh/vagrant/issues/5005
    config.ssh.insert_key = false

    config.vm.define "web" do |web|
        # Ubuntu 16.04
        web.vm.box = "ubuntu/xenial64"

        web.vm.provider :virtualbox do |vb|
            vb.name = "csc_vm"
        end

        web.vm.network "private_network", ip: "192.168.33.11"

        # Run vagrant up/provision
        web.vm.provision "ansible" do |ansible|
            ansible.verbose = "vv"
            ansible.tags = ["app-deployment"]
            ansible.skip_tags = ["cronjobs", "lvm-role"]
            ansible.extra_vars = {
              hosts_override: "vagrant-test-hosts",
              enable_https: false
            }
            ansible.playbook = "setup.yml"
            ansible.groups = {
                "vagrant-test-hosts" => ["web"]
            }
        end
    end
end