# This guide is optimized for Vagrant 1.7 and above.
# Although versions 1.6.x should behave very similarly, it is recommended
# to upgrade instead of disabling the requirement below.
Vagrant.require_version ">= 1.7.0"

Vagrant.configure(2) do |config|

  # Ubuntu 14.04
  config.vm.box = "trusty32"

  # Disable the new default behavior introduced in Vagrant 1.7, to
  # ensure that all Vagrant machines will use the same SSH key pair.
  # See https://github.com/mitchellh/vagrant/issues/5005
  config.ssh.insert_key = false

   # Run vagrant up/provision
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "vv"
    ansible.extra_vars = {
      hosts_override: "all"
    }
    ansible.playbook = "setup.yml"
  end
end