# Generated by Django 3.0.9 on 2020-08-27 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0022_auto_20200827_1142'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='GerritChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_id', models.CharField(help_text='Full ID of the change in Gerrit: `{project_name}~{branch_name}~{change_id}`', max_length=255)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sites.Site')),
                ('student_assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='learning.StudentAssignment', verbose_name='Student Assignment')),
            ],
            options={
                'verbose_name': 'Gerrit Change',
                'verbose_name_plural': 'Gerrit Changes',
            },
        ),
    ]
