# Generated by Django 2.1.1 on 2018-11-06 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_create_templates'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewstream',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='streams', to='courses.Venue', verbose_name='Interview venue'),
        ),
    ]
