# Generated by Django 2.1.3 on 2018-11-08 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
        ('core', '0002_auto_20180730_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursenews',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='coursenews',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.Course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='courseclassattachment',
            name='course_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseClass', verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.Course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.Venue', verbose_name='CourseClass|Venue'),
        ),
        migrations.AddField(
            model_name='course',
            name='city',
            field=models.ForeignKey(default='spb', on_delete=django.db.models.deletion.PROTECT, to='core.City', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='course',
            name='meta_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.MetaCourse', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.Semester', verbose_name='Semester'),
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(related_name='teaching_set', through='courses.CourseTeacher', to=settings.AUTH_USER_MODEL, verbose_name='Course|teachers'),
        ),
        migrations.AddField(
            model_name='assignmentattachment',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Assignment', verbose_name='Assignment'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.Course', verbose_name='Course offering'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='notify_teachers',
            field=models.ManyToManyField(blank=True, help_text='Leave blank if you want to populate list from the course settings', to='courses.CourseTeacher', verbose_name='Assignment|notify_settings'),
        ),
        migrations.AlterUniqueTogether(
            name='courseteacher',
            unique_together={('teacher', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('meta_course', 'semester', 'city')},
        ),
    ]
