# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-31 19:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import learning.gallery.models
import mptt.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0002_auto_20170331_2209'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(help_text='Short name in ASCII, used in images upload path', max_length=70, unique=True, verbose_name='Slug')),
                ('order', models.IntegerField(default=100, verbose_name='Order')),
                ('brief', models.CharField(blank=True, default='', help_text='Short description', max_length=255, verbose_name='Brief')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'ordering': ('order', 'name'),
                'verbose_name_plural': 'Albums',
                'verbose_name': 'Album',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('image', sorl.thumbnail.fields.ImageField(max_length=255, upload_to=learning.gallery.models.gen_path_to_image, verbose_name='File')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.Album', verbose_name='Album')),
                ('course_offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='learning.CourseOffering', verbose_name='Course offering')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ('order', 'id'),
                'verbose_name_plural': 'Images',
                'verbose_name': 'Image',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_of', to='gallery.Image', verbose_name='Head'),
        ),
        migrations.AddField(
            model_name='album',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Parent album', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='gallery.Album', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='album',
            name='semester',
            field=models.ForeignKey(blank=True, help_text='Set semester for album and all uploaded images will inherit it.', null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.Semester', verbose_name='Semester'),
        ),
    ]
