# Generated by Django 2.1.1 on 2018-10-19 13:39

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        ('gallery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='course_offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='learning.CourseOffering', verbose_name='Course offering'),
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='images',
                                    to=settings.AUTH_USER_MODEL,
                                    verbose_name='User'),
        ),
        migrations.AddField(
            model_name='album',
            name='head',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='head_of', to='gallery.Image',
                                    verbose_name='Head'),
        ),
        migrations.AddField(
            model_name='album',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True,
                                             help_text='Parent album',
                                             null=True,
                                             on_delete=django.db.models.deletion.CASCADE,
                                             related_name='children',
                                             to='gallery.Album',
                                             verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='album',
            name='semester',
            field=models.ForeignKey(blank=True,
                                    help_text='Set semester for album and all uploaded images will inherit it.',
                                    null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='learning.Semester',
                                    verbose_name='Semester'),
        ),
    ]
