# Generated by Django 2.1.1 on 2018-10-31 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_image_course_offering'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='course_offering',
            new_name='course',
        ),
    ]
