# Generated by Django 2.1.1 on 2018-11-06 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20181031_1514'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='semester',
            field=models.ForeignKey(blank=True, help_text='Set semester for album and all uploaded images will inherit it.', null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Semester', verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='image',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.Course', verbose_name='Course offering'),
        ),
    ]
