# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 13:32
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20160603_1715'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='album',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
