---
# Use default GPT partition
- name: Create volume group on {{ item.block_device_name }}
  lvg:
    vg: "{{ item.vg_name }}"
    pvs: "{{ item.block_device_name }}"
    state: present
  when: >
    (item.state is not defined or item.state == "present") and
    item.vg_name + "-" + item.lv_name not in lsblk_list.stdout

- name: Create logical volume
  lvol:
    vg: "{{ item.vg_name }}"
    lv: "{{ item.lv_name }}"
    size: "100%FREE"
  when: >
    (item.state is not defined or item.state == "present") and
    item.vg_name + "-" + item.lv_name not in lsblk_list.stdout

- name: Format volume
  filesystem:
    fstype: "{{ item.filesystem }}"
    dev: /dev/{{ item.vg_name }}/{{ item.lv_name }}
    opts: "{{ item.filesystem_mkfs_opts | default(omit) }}"
  when: >
    (item.state is not defined or item.state == "present") and
    item.vg_name + "-" + item.lv_name not in lsblk_list.stdout