# https://gist.github.com/mrlesmithjr/1da992b648771b9afd50#file-confg_lvm-yml

- name: Install LVM support
  apt:
    name:  '{{ item }}'
    state: 'present'
    install_recommends: False
  with_items: lvm_packages

- name: Configure global/use_lvmetad
  lineinfile:
    dest:        '/etc/lvm/lvm.conf'
    insertafter: '^global\s+{$'
    regexp:      '^\s+use_lvmetad\s=\s'
    line:        '    use_lvmetad = {{ lvm_global_use_lvmetad }}'
    state:       'present'

- name: Disable default devices/filter value
  lineinfile:
    dest:     '/etc/lvm/lvm.conf'
    regexp:   '^\s\s\s\sfilter\s=\s\[\s"a/.*/"\s\]$'
    line:     '    # filter = [ "a/.*/" ]'
    backrefs: True
    state:    'present'

- name: Create PV / VG on /dev/xvdf
  lvg: vg=vg0 pvs=/dev/xvdf

- name: Creating new LVM logical volume
  lvol: vg=vg0 lv=shared size=100%FREE

- name: Create filesystem on data LV
  filesystem: dev=/dev/vg0/shared fstype=ext4

- name: Ensure data mountpoint exists
  file: path=/shared state=directory owner=ubuntu group=ubuntu mode=0755

- name: Mount data LV
  mount: name=/shared src=/dev/vg0/shared fstype=ext4
         state=mounted opts="errors=remount-ro,noatime,barrier=0"
         dump=0 passno=2

- name: Again ensure shared/ folder has right owner
  file: path=/shared state=directory owner=ubuntu group=ubuntu mode=0755

# - name: Configure devices/filter
#   lineinfile:
#     dest:        '/etc/lvm/lvm.conf'
#     insertafter: '^devices\s+{$'
#     regexp:      '\s+filter\s+=\s+\[\s+\"'
#     line:        '    filter = [ "{{ lvm_devices_filter | join("\", \"") }}" ]'
#     state:       'present'
#   register: lvm_register_devices_filter

# - name: Configure devices/global_filter
#   lineinfile:
#     dest:        '/etc/lvm/lvm.conf'
#     insertafter: '^devices\s+{$'
#     regexp:      '\s+global_filter\s+=\s+\['
#     line:        '    global_filter = [ "{{ lvm_devices_global_filter | join("\", \"") }}" ]'
#     state:       'present'
#   register: lvm_register_devices_global_filter