# https://gist.github.com/mrlesmithjr/1da992b648771b9afd50#file-confg_lvm-yml

- name: Install necessary packages for LVM support
  apt:
    name:  '{{ item }}'
    state: 'present'
    install_recommends: False
  with_items: "{{ lvm_packages }}"

- name: Configure global/use_lvmetad
  lineinfile:
    dest:        '/etc/lvm/lvm.conf'
    insertafter: '^global\s+{$'
    regexp:      '^\s+use_lvmetad\s=\s'
    line:        '    use_lvmetad = {{ lvm_global_use_lvmetad }}'
    state:       'present'

- name: Disable default devices/filter value
  lineinfile:
    dest:     '/etc/lvm/lvm.conf'
    regexp:   '^\s\s\s\sfilter\s=\s\[\s"a/.*/"\s\]$'
    line:     '    # filter = [ "a/.*/" ]'
    backrefs: True
    state:    'present'

- name: Get partition list
  command: lsblk
  register: lsblk_list
  changed_when: false

- name: Create lvm volume(s)
  include: create-lvm.yml
  loop: "{{ lvm_volumes }}"
  when: lvm_volumes

- name: Mount data LV
  mount:
    name: "{{ item.mount }}"
    src: /dev/{{ item.vg_name }}/{{ item.lv_name }}
    fstype: "{{ item.filesystem }}"
    state: mounted
    opts: "{{ item.filesystem_mkfs_opts | default(omit) }}"
    dump: 0
    passno: 2
  loop: "{{ lvm_volumes }}"

- name: Ensure mounted folder has right owner
  file:
    path: "{{ item.mount }}"
    state: directory
    owner: "{{ item.owner | default(aws_ec2_user) }}"
    group: "{{ item.group | default(aws_ec2_user) }}"
    mode: "{{ item.mode | default ('0755') }}"
  loop: "{{ lvm_volumes }}"
