# https://gist.github.com/mrlesmithjr/1da992b648771b9afd50#file-confg_lvm-yml

- name: Install necessary packages for LVM support
  apt:
    name:  '{{ item }}'
    state: 'present'
    install_recommends: False
  with_items: "{{ lvm_packages }}"

- name: Configure global/use_lvmetad
  lineinfile:
    dest:        '/etc/lvm/lvm.conf'
    insertafter: '^global\s+{$'
    regexp:      '^\s+use_lvmetad\s=\s'
    line:        '    use_lvmetad = {{ lvm_global_use_lvmetad }}'
    state:       'present'

- name: Disable default devices/filter value
  lineinfile:
    dest:     '/etc/lvm/lvm.conf'
    regexp:   '^\s\s\s\sfilter\s=\s\[\s"a/.*/"\s\]$'
    line:     '    # filter = [ "a/.*/" ]'
    backrefs: True
    state:    'present'

- name: Create PV / VG on {{ item.block_device_name }}
  lvg: vg={{ item.vg_name }} pvs="{{ item.block_device_name }}"
  loop: "{{ lvm_volumes }}"

- name: Creating new LVM logical volume
  lvol: vg={{ item.vg_name }} lv={{ item.lv_name }} size=100%FREE
  loop: "{{ lvm_volumes }}"

- name: Create filesystem on data LV
  filesystem: dev=/dev/{{ item.vg_name }}/{{ item.lv_name }} fstype={{ item.filesystem }}
  loop: "{{ lvm_volumes }}"

- name: Ensure data mountpoint exists
  file: path={{ item.mount }} state=directory owner=ubuntu group=ubuntu mode=0755
  loop: "{{ lvm_volumes }}"

- name: Mount data LV
  mount: name={{ item.mount }} src=/dev/{{ item.vg_name }}/{{ item.lv_name }} fstype={{ item.filesystem }}
         state=mounted opts="errors=remount-ro,noatime,barrier=0"
         dump=0 passno=2
  loop: "{{ lvm_volumes }}"

- name: Again ensure mounted folder has right owner
  file: path={{ item.mount }} state=directory owner=ubuntu group=ubuntu mode=0755
  loop: "{{ lvm_volumes }}"
