# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-31 19:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def update_forward(apps, schema_editor):
    """Add sites list"""
    Site = apps.get_model('sites', 'Site')
    Site.objects.update_or_create(
        id=settings.CENTER_SITE_ID,
        defaults={
            "domain": "compscicenter.ru",
            "name": "compscicenter.ru"
        }
    )
    Site.objects.update_or_create(
        id=settings.CLUB_SITE_ID,
        defaults={
            "domain": "compsciclub.ru",
            "name": "compsciclub.ru"
        }
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='City name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='City name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='City name')),
                ('abbr', models.CharField(max_length=20, verbose_name='Abbreviation')),
                ('abbr_ru', models.CharField(max_length=20, null=True, verbose_name='Abbreviation')),
                ('abbr_en', models.CharField(max_length=20, null=True, verbose_name='Abbreviation')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('sort', models.SmallIntegerField(blank=True, null=True, verbose_name='Sort order')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'Questions&Answers',
                'db_table': 'faq',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='FaqCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Category name')),
                ('sort', models.SmallIntegerField(blank=True, null=True, verbose_name='Sort order')),
                ('site', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'FAQ category',
                'verbose_name_plural': 'FAQ categories',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Perhaps also the faculty.', max_length=255, verbose_name='University')),
                ('abbr', models.CharField(blank=True, max_length=100, null=True, verbose_name='University abbreviation')),
                ('sort', models.SmallIntegerField(blank=True, null=True, verbose_name='Sort order')),
                ('city', models.ForeignKey(default='spb', on_delete=django.db.models.deletion.CASCADE, to='core.City', verbose_name='City')),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.AddField(
            model_name='faq',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='categories', to='core.FaqCategory', verbose_name='Categories'),
        ),
        migrations.AddField(
            model_name='faq',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Site'),
        ),
        migrations.RunPython(update_forward),
    ]
