# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-27 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160318_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Perhaps also the faculty.', max_length=255, verbose_name='University')),
                ('city', models.ForeignKey(default='RU SPB', on_delete=django.db.models.deletion.CASCADE, to='core.City', verbose_name='City')),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'verbose_name': 'University',
            },
        ),
    ]
