# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-06 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='abbr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='University abbreviation'),
        ),
        migrations.AddField(
            model_name='university',
            name='sort',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Sort order'),
        ),
    ]
