# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-22 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170306_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='abbr',
            field=models.CharField(default='', max_length=20, verbose_name='Abbreviation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='abbr_en',
            field=models.CharField(max_length=20, null=True, verbose_name='Abbreviation'),
        ),
        migrations.AddField(
            model_name='city',
            name='abbr_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='city',
            name='code',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='university',
            name='city',
            field=models.ForeignKey(default='spb', on_delete=django.db.models.deletion.CASCADE, to='core.City', verbose_name='City'),
        ),
    ]
